### ISSUE TITLE
xrdfs query stats :: missing documentation of metrics

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1050]
Hi! It would be really useful to have documentation about the meaning of the metrics
reported by xrdfs query stats.
Thank you!

**Comment by abh3** [comment]
The documentation is located here:
http://xrootd.org/doc/dev50/xrd_monitoring.htm#_Toc7556956

Since the actual response is implementation dependent which is why the deferenceto this documentation was not included in the protocol spec. However, we can add a note saying this is an example implementation.
