### ISSUE TITLE
TPC ignores wildcard SAN entries in certificate

### ISSUE THREAD

**Issue by timadye** [xrootd/xrootd#1055]
At RAL we have 7 gateway machines behind a DNS alias `xrootd.echo.stfc.ac.uk`. This is reflected in each gateway machine's `/etc/grid-security/xrootd/hostcert.pem` certificate, which has, eg.

    X509v3 Subject Alternative Name:
        DNS:ceph-gw1.gridpp.rl.ac.uk, DNS:echo.stfc.ac.uk, DNS:*.echo.stfc.ac.uk, DNS:*.s3.echo.stfc.ac.uk

`xrootd.echo.stfc.ac.uk` should match the `*.echo.stfc.ac.uk` wildcard. but it doesn't work for `xrdcp --tpc`, eg. with xrootd v4.9.1 on client and gateway server:

    % xrdcp --tpc delegate only root://xrootd.echo.stfc.ac.uk:1094/dteam:test1/testKaty1 root://prometheus.desy.de:1095/VOs/dteam/testRAL1b
    secgsi: proxy delegation forbidden when trusting DNS!

On the other hand, this copy works fine if I use a specific host name (eg. `ceph-gw1.gridpp.rl.ac.uk`), or the `echo.stfc.ac.uk` alias (which isn't specified with a wildcard).

Although we can use one of those other names as a temporary workaround, that isn't a good long-term solution as it introduces other incompatibilities that I needn't go into here. We also can't change the certificate to add `xrootd.echo.stfc.ac.uk` explicitly.

So it would be good to have a fix fairly soon. If the fix is only required on the gateway machines, then we could apply it as soon as it becomes available. If it's needed on the xrdcp client, then we'll have to wait for the new release to be widely deployed. Which is it?

Thanks,
Tim.

**Comment by abh3** [comment]
The issue here is understood. From a historical perspective, RFC2818 does not require that wildcard entries in a certificate be supported. Additionally, RFC6125 deprecates wildcard certificates due to security consideration (that RFC is widely ignored for obvious reasons). Both however make it clear that wildcards are purely optional. Of course, it's understood that wildcard support in our environment is important. The solution for this, unfortunately,will likely wait for R5 as that's when we introduce TLS and that implementation supports wildcard certs. So, it would be only a matter of using that cert checking code for GSI. Some repackaging would be needed but it's not onerous.

My understanding is that you may have a temporary workaround. If that workaround doesn't work we will revisit the schedule.

**Comment by bbockelm** [comment]
Uh, wildcards are definitely supported:

https://github.com/xrootd/xrootd/blob/master/src/XrdCrypto/XrdCryptoX509.cc#L263-L268

The error message here is:

> secgsi: proxy delegation forbidden when trusting DNS!

That is, Xrootd is doing a reverse-DNS lookup at some point (maybe after being redirected? failing something else in the hostname wildcard matching?), which is inherently insecure when it comes to GSI auth.  Hence, the client is cowardly refusing to give their proxy over an insecure connection.

So, why is reverse-DNS being used?

- It could be, as you surmised, due to wildcard failure (i.e., bug in existing implementation).
- It could be the client code path isn't providing the X509 level with the right information.

I think we could distinguish between these cases from the client log at full debug.

**Comment by abh3** [comment]
OK, I looked at the code once again. It seems there is a bug in the logic 
when the SAN matches and trustDNS is on. I will investigate but I don't 
see it working the right way as of the moment.

Andy

**Comment by abh3** [comment]
OK, there is definitely a bug in the checking logic but it wouldn't 
explain that message unless the SAN check failed. So, the conclusion is 
that there is also a bug in the wildcard checking as well. Time could you

a) set the envars XrdSecDEBUG and XrdDEBUG to 1.
b) reissue the xrdcp with --tpc delegate only
c) Send the log output to me, and
d) use openssl to display the host's certificate including the SAN 
extension and send hat to me as well.

In the mean time I will correct the faulty cut-paste SAN checking logic 
(yeah, it was a cut-paste error).

Andy

**Comment by abh3** [comment]
OK, so the plot thickens here. The message about not delegating because DNS was used is incredibly misleading. That message comes out if DNS was used for the source or the target, In fact, you could potentially get the message twice, once for the source and once for the target, The reason is that once delegation is enabled it is enabled for anyone that is authenticating and asking for delegation. Here, the only DNS disapproval that maters is that we did not delegate to the destination. Unfortunately, there is no way that we can know that other than the copy would have failed. It did not, did it.

Looks to me what we need to correct is the message not anything else.

**Comment by abh3** [comment]
One more thing. The reason the the command worked was because dCache was the destination not RAL. I am told if we reverse this, the copy will fail because, presumably, a SAN mismatch. We are trying to reproduce this as the log you sent wasn't for that particular case.

**Comment by timadye** [comment]
Hi Andy,
You are right: it gives the same proxy delegation error going the other way round, but this one actually fails:

    xrdcp --tpc delegate only root://prometheus.desy.de:1095/VOs/dteam/testRAL3p root://xrootd.echo.stfc.ac.uk:1094/dteam:test1/testDESY3r
    secgsi: proxy delegation forbidden when trusting DNS!
    [0B/140B][  0%][>                                                 ][0B/s]
    Run: [ERROR] Server responded with an error: [3005] [FATAL] Auth failed

I attach the output from that command with `XrdSecDEBUG=1 XrdDEBUG=1`, [here](https://github.com/xrootd/xrootd/files/3626932/xrdcp2.log).

Thanks,
Tim.

**Comment by xrootd-dev** [comment]
Hi Tim,

Could you look at the xrootd.echo.stfc.ac.uk log at he same time you ran the command to see what the actual error was?

Andy

**Comment by timadye** [comment]
Hi Andy,

Here is another test with the same xrdcp command line, executed on lxplus772.cern.ch. I tracked down that it connected to ceph-gw5.gridpp.rl.ac.uk. Here are the snippets for the log files:

- [xrdcp](https://github.com/xrootd/xrootd/files/3631976/xrdcp3.log)
- [`/var/log/xrootd/proxy/xrootd.log`](https://github.com/xrootd/xrootd/files/3631977/xrootd3.log)
- [`/var/log/xrootd/ceph/xrootd.log`](https://github.com/xrootd/xrootd/files/3631978/ceph3.log)

I hope that helps,
Tim.

**Comment by abh3** [comment]
Hi Tim,

Well, that is interesting. First off, please always include the command line that goes with the log in the future. That said, I suspect that the issue was Ce[h simply didn’t have the file...

Resulting PFN: dteam:test1/testDESY3r190919 16:01:36 1578604 ofs_stat: adye.12904:37@lxplus772.cern.ch Unable to locate dteam:test1/testDESY3r; no such file or directory

I have no clue what that file was but it wasn’t there. I also suspect your proxy server might not be at the correct level to support delegated TPC. What is the release of that server?

Andy

**Comment by timadye** [comment]
Hi Andy,

> Hi Tim, Well, that is interesting. First off, please always include the command line that goes with the log in the future.

OK. In this case it was identical to the command I gave before:

    xrdcp --tpc delegate only root://prometheus.desy.de:1095/VOs/dteam/testRAL3p root://xrootd.echo.stfc.ac.uk:1094/dteam:test1/testDESY3r

> That said, I suspect that the issue was Ce[h simply didn’t have the file...
> Resulting PFN: dteam:test1/testDESY3r
> 190919 16:01:36 1578604 ofs_stat: adye.12904:37@lxplus772.cern.ch Unable to locate dteam:test1/testDESY3r; no such file or directory
> I have no clue what that file was but it wasn’t there.

That file is the destination file, so it shouldn't be there. :) Could this be an initial check to see that it doesn't overwrite the file? (I didn't use xrdcp -f.)

> I also suspect your proxy server might not be at the correct level to support delegated TPC. What is the release of that server?

We have xrootd 4.9.1, eg. xrootd-server-4.9.1-1.el7.x86_64.

Also the same command works fine if I use `root://echo.stfc.ac.uk:1094/dteam:test1/testDESY3r` instead of `root://xrootd.echo.stfc.ac.uk:1094/dteam:test1/testDESY3r`. The only difference is that echo.stfc.ac.uk doesn't have the wildcard in the certificate.

Thanks,
Tim.

**Comment by xrootd-dev** [comment]
Hi Tim,

Can I also do this using my ATLAS cert (I don't have a dteam cert) from SLAC, yes?

Andy

**Comment by timadye** [comment]
Hi Andy,

Yes, the RAL end works also for atlas. You can use the Atlas endpoint for DESY or use another site like SLAC.

Tim


---- xrootd-dev wrote ----

Hi Tim,

Can I also do this using my ATLAS cert (I don't have a dteam cert) from SLAC, yes?

Andy

**Comment by xrootd-dev** [comment]
Hi Tim,

Indeed that wildcard SAN check was faulty. I just pushed a fix and it 
should be in the next RC for 4.11. However, the copy fails anyway 
seemingly triggered by:

[2019-09-25 21:42:46.502059 -0700][Debug  ][ExDbgMsg          ] 
[prometheus.desy.de:1095] Calling MsgHandler: 0x1866fc0 (message: kXR_open 
(file: /VOs/dteam/testRAL3p?tpc.stage=placement, mode: 00, flags: 
kXR_open_read kXR_async kXR_retstat ) ) with status: [ERROR] Error 
response: No such file or directory.

So, he file doesn't exist. I have to follow up with Michal why this 
actually generates an "unsupported" error, which is wrong.

Andy

**Comment by timadye** [comment]
Hi Andy,

Thanks for the fix! Were you able to test it, or are you still missing a test example?

I was having problems with the DESY site earlier today, but it seems to work better now. Maybe it's fixed for you too. Here are a couple of examples, now with an `atlas` VOMS proxy.

    lxplus745> xrdcp --tpc delegate only -f root://echo.stfc.ac.uk:1094/dteam:test1/testKaty1 root://prometheus.desy.de:1095/VOs/atlas/testRAL1
    [140B/140B][100%][==================================================][70B/s]
    lxplus745> xrdfs echo.stfc.ac.uk:1094 rm dteam:test1/testDESY1
    lxplus745> xrdcp --tpc delegate only root://prometheus.desy.de:1095/VOs/atlas/testRAL1 root://echo.stfc.ac.uk:1094/dteam:test1/testDESY1
    [140B/140B][100%][==================================================][46B/s]

Note that `xrdcp -f` doesn't work for RAL Echo as destination (a minor issue), so if you use the same output file again, you have to delete it first - as I did with the `xrdfs rm` command here.

In those examples I used `echo.stfc.ac.uk` to be sure they would work without your fix. You can check your fix by substituting `xrootd.echo.stfc.ac.uk`:

    xrdcp --tpc delegate only -f root://xrootd.echo.stfc.ac.uk:1094/dteam:test1/testKaty1 root://prometheus.desy.de:1095/VOs/atlas/testRAL1
    xrdfs xrootd.echo.stfc.ac.uk:1094 rm dteam:test1/testDESY1
    xrdcp --tpc delegate only root://prometheus.desy.de:1095/VOs/atlas/testRAL1 root://xrootd.echo.stfc.ac.uk:1094/dteam:test1/testDESY1

Thanks,
Tim.

PS. I also tried to use `root://griddev03.slac.stanford.edu:2094//xrootd/atlas/tpctest` as the test peer, but couldn't get it to work. We had this working before.

**Comment by xrootd-dev** [comment]
Hi Tim,

I didn't get a chance to test again. But it appears you did and are happy 
with the fix, right?

Andy

**Comment by timadye** [comment]
Hi Andy,

No, I was just giving some examples of test transfers you could try - answering your other question.

I can't test it because we don't have the fix installed on our server. We could try the new code on our test gateway when the RC is available, but that still wouldn't show the fix because the bug only manifests with a DNS alias which we only have for our production servers.

So I don't think we can test this before it goes into production.

Thanks,
Tim.

**Comment by xrootd-dev** [comment]
Hi Tim,

OK, I will test it but it may have to wait until I get to CERN next week. 
At least we will be in the same timezone,roughly speaking :-)

Andy

**Comment by wyang007** [comment]
Just checked the path. It seems to fix the problem:

-bash-4.2$ xrdfs echo.stfc.ac.uk:1094 rm dteam:test1/testDESY1
-bash-4.2$ $HOME/xrd/el7/src/XrdCl/xrdcp --tpc delegate only root://prometheus.desy.de:1095/VOs/atlas/testRAL1 root://xrootd.echo.stfc.ac.uk:1094/dteam:test1/testDESY1
[140B/140B][100%][==================================================][35B/s]

--
Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338 (O)

**Comment by abh3** [comment]
Fixed by commit 19859d93 which will be included in 4.11.

**Comment by timadye** [comment]
Hi Wei and Andy,

Thanks for the fix!

I didn't realise that this fix was in the client only, so it is possible to test against the production server, as Wei showed.

I also tested with the incremental build (`v20190930-f9d0bee`), and it works both ways (RAL->DESY, DESY->RAL) where 4.9.1 gives the proxy delegation error. So I can confirm that the fix looks good.

Since the fix is in the client, we'll have to keep using the workaround (echo.stfc.ac.uk) for the smoke tests and Rucio transfers until the test client and FTS can be updated to the next release.

Thanks,
Tim.
