### ISSUE TITLE
XRootD client reports wrong error when copy fails at source with ENOENT

### ISSUE THREAD

**Issue by abh3** [xrootd/xrootd#1059]
Simple example and log trace showing the problem below.

xrdcp --tpc delegate only
root://prometheus.desy.de:1095/VOs/dteam/testRAL3p
root://xrootd.echo.stfc.ac.uk:1094/dteam:test1/testDESY3r
[0B/0B][100%][==================================================][0B/s]
Run: [ERROR] Operation not supported
Exit 50

[2019-09-25 21:42:46.328399 -0700][Debug  ][ExDbgMsg          ]
[prometheus.desy.de:1095] Moving MsgHandler: 0x1866fc0 (message: kXR_open
(file: /VOs/dteam/testRAL3p?tpc.stage=placement, mode: 00, flags:
kXR_open_read kXR_async kXR_retstat ) ) from out-queu to in-queue.
[2019-09-25 21:42:46.502014 -0700][Debug  ][XRootD            ]
[prometheus.desy.de:1095] Handling error while processing kXR_open (file:
/VOs/dteam/testRAL3p?tpc.stage=placement, mode: 00, flags: kXR_open_read
kXR_async kXR_retstat ): [ERROR] Error response: No such file or
directory.
[2019-09-25 21:42:46.502059 -0700][Debug  ][ExDbgMsg          ]
[prometheus.desy.de:1095] Calling MsgHandler: 0x1866fc0 (message: kXR_open
(file: /VOs/dteam/testRAL3p?tpc.stage=placement, mode: 00, flags:
kXR_open_read kXR_async kXR_retstat ) ) with status: [ERROR] Error
response: No such file or directory.
[2019-09-25 21:42:46.502148 -0700][Debug  ][File              ]
[0x1865c40@root://prometheus.desy.de:1095//VOs/dteam/testRAL3p?tpc.stage=placement&x
rdcl.requuid=427379b2-abc0-441f-8529-bc7db3fa672a]
Open has returned with status [ERROR] Server responded with an error:
[3011] No such file
[2019-09-25 21:42:46.502163 -0700][Debug  ][File              ]
[0x1865c40@root://prometheus.desy.de:1095//VOs/dteam/testRAL3p?tpc.stage=placement&x
rdcl.requuid=427379b2-abc0-441f-8529-bc7db3fa672a]
Error while opening at prometheus.desy.de:1095: [ERROR] Server responded
with an error: [3011] No such file

**Comment by simonmichal** [comment]
@abh3 : sorry for the delay, long story short: if `delegate only` is being used the failure of opening the source is no longer considered as a critical error as the destination might be able to open the file e.g. through a different protocol. To summarize, **TPC light does not require a successful open of source**, the open is done only so we can append the `oss.asize` hint to the opaque info and resolve the URL of the source data server.

Subsequently, the transfer fails because it cannot verify is the destination supports TPC Lite, issuing a `query config 'tpc tpcdlg'` yields  `[ERROR] Operation not supported`:

```
./xrdfs /xrootd.echo.stfc.ac.uk:1094 query config 'tpc tpcdlg'
[ERROR] Operation not supported
```

**Comment by xrootd-dev** [comment]
Hi Michal,

Thanks for the information. Could these kind of messages be changed to 
include wh doesn't support whateve. When we have two parties it becomes a 
nightmare figuring out which one failed. So, the message should be along 
the lines

[ERROR] Operation not supported by xrootd.echo.stfc.ac.uk

Then the questions would not have come up (as soon as it did).

Andy
