### ISSUE TITLE
IP version monitoring for TPC transfers

### ISSUE THREAD

**Issue by andrea-manzi** [xrootd/xrootd#1062]
Hello,
in FTS we currently have a way to mark a TPC  transfer as been executed via IPV4 or IPV6 when using gridftp. Given that we soon will run XrootD TPC transfers in production, i have  discussed with the HEPIX IPV6 WG to see if we could offer the same monitoring for XrootD, but i don't see a possible way of doing it now.
Internally we use the XrdCl client and we implement the XrdCl::CopyProgressHandler to know about the transfer status and performance, do you think it would be possible to report via that callback also if the TPC has been executed via IPV6 or IPV4 or alternatively report a list of IPs used for the connection to the source?
thanks
Andrea

**Comment by xrootd-dev** [comment]
Hi Andrea,

That is a tough one. However, since you are using a custom reporting 
mechanism with gridftp you may want to see if you can write a monitoring 
plugin for xrdcp via the client plugin mechanism. That plugin should get 
enough information to be able to report that kind of information using an 
outboard communication path (i.e. what you are using for gridftp). Of 
course, I hve no idea how you doing that for gridftp so it might not be 
completely applicable here.

Andy

**Comment by andrea-manzi** [comment]
Hi Andy,
for gridftp it's easier as the client contact both source and dest and knows the ip of the destination to tell the source to connect to. I was also thiking if we could somehow have the info about the ip used printed on the logs and simply parse them on our side,  i will also check if a client plugin can be used for this porpuse
thanks
cheers
Andrea

**Comment by abh3** [comment]
Hi Andrea, did this get resolved? Can we close this ticket?

**Comment by andrea-manzi** [comment]
HI Andy,
there has been no progress in this activity and also when i discussed about this during DOMA TPC calls i didn't see so much interest. So better that you close the ticket and if needed it will be reopened in the future.
cheers
Andrea

**Comment by abh3** [comment]
Hi Andrea,

Weird but that ticket has already been closed.

Andy
