### ISSUE TITLE
hostname can be longer than 64 chars

### ISSUE THREAD

**Issue by falu0** [xrootd/xrootd#1064]
https://github.com/xrootd/xrootd/blob/a9d548302045259c17f11709580f316a698fe697/src/XrdSys/XrdSysDNS.cc#L255

When deploying [EOS](http://eos.web.cern.ch/) on Kubernetes, I had some spare chances to get a truncated hostname when this was longer than 64 chars, resulting in misconfigurations/erroneous setup. Is this limit still necessary?

Perhaps https://github.com/xrootd/xrootd/blob/master/src/XrdSys/XrdSysDNS.hh#L182 
is involved too.

- faluchet@cern.ch

**Comment by xrootd-dev** [comment]
Hello,

Two things here:
1) XrdSysDNS is deprecated and should not be used because it only supports 
IPv4. The replacement is XrdNetAddr which is derived from XrdNetInfo.

2) There is no restriction to 64 characters and the what is being 
referenced here is a misleading comment. The comment suggests that 64 
characters is long enough but that is untrue, obviously. I don't think EOS 
uses XrdSysDNS anymore and if it does it likely specifies a buffer at 
least 256 bytes long.

Andy
