### ISSUE TITLE
http access do not play nice with squids

### ISSUE THREAD

**Issue by efajardo** [xrootd/xrootd#1073]
@abh3 ,

I was testing today getting some files of a stashcache with a squid in front of it.

```console
http_proxy="http://cvmfs-1.t2.ucsd.edu:3128" curl -v http://stashcache.t2.ucsd.edu:8000/user/dweitzel/public/blast/queries/query1 -O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* About to connect() to proxy cvmfs-1.t2.ucsd.edu port 3128 (#0)
*   Trying 169.228.130.85...
* Connected to cvmfs-1.t2.ucsd.edu (169.228.130.85) port 3128 (#0)
> GET http://stashcache.t2.ucsd.edu:8000/user/dweitzel/public/blast/queries/query1 HTTP/1.1
> User-Agent: curl/7.29.0
> Host: stashcache.t2.ucsd.edu:8000
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 OK
< Content-Length: 103
< Date: Tue, 22 Oct 2019 16:03:59 GMT
< X-Cache: MISS from cvmfs-1.t2.ucsd.edu
< Via: 1.1 cvmfs-1.t2.ucsd.edu (squid/frontier-squid-4.4-2.1.osg34.el7)
< Connection: keep-alive
< 
{ [data not shown]
100   103  100   103    0     0  10496      0 --:--:-- --:--:-- --:--:-- 11444
* Connection #0 to host cvmfs-1.t2.ucsd.edu left intac
```

And as you can see it is always a miss. From the squid logs it seems as Xrootd always tells it the file has changed, but clearly it has not:

```
[0903] root@cvmfs-1 /var/log/squid# tail -f -n 100 access.log | grep query1
169.228.130.5 - - [22/Oct/2019:09:03:59.781 -0700] "GET http://stashcache.t2.ucsd.edu:8000/user/dweitzel/public/blast/queries/query1 HTTP/1.1" 200 315 TCP_REFRESH_MODIFIED:HIER_DIRECT 2 "- -" "-" "curl/7.29.0"
169.228.130.5 - - [22/Oct/2019:09:10:48.349 -0700] "GET http://stashcache.t2.ucsd.edu:8000/user/dweitzel/public/blast/queries/query1 HTTP/1.1" 200 315 TCP_REFRESH_MODIFIED:HIER_DIRECT 3 "- -" "-" "curl/7.29.0"
```

@bbockelm  any ideas? @DrDaveD am I understanding the squid message correctly?

**Comment by efajardo** [comment]
I must add I was using this docker image `opensciencegrid/stash-cache:stable` but I have tried it against even simpler setups and I cannot get the squid to cache anything.

**Comment by osschar** [comment]
I assume the file in cache is fully downloaded, right? Can you do xrdfs stat against it, please.

**Comment by DrDaveD** [comment]
Edgar, this is because of a lack of `Cache-control: max-age` header combined with a `Date` that is updated every time.

However, what's the use case for this?  In general the data that we store in stashcache is not suitable for caching in squid.  That's the reason why we use stashcache instead of squid for data files.

**Comment by efajardo** [comment]
@osschar it is there

```
$ xrdfs stashcache.t2.ucsd.edu:8000 stat /user/dweitzel/public/blast/queries/query1
Path:   /user/dweitzel/public/blast/queries/query1
Id:     -9171444997482870751
Size:   103
MTime:  2019-07-25 16:33:53
Flags:  48 (IsReadable|IsWritable)
```
@DrDaveD ,

The use case was the following we had a studet that had a couple of O(100MB) files the same files for thousands of jobs. Our xrootd doors were configured to use http and we could curl wget them. 

```
wget -d -c -v http://gftp-2.t2.ucsd.edu:1094/store/user/smay/ttH/tarballs/package_ttH_Babies_RunIIv4.4_ttZ.tar.gz 
```
However this was destryoing hadoop since this was running all over US T2 so we wanted to profit from the squid caches at all sites but the squid was alwauys requesting the file from scratch. The header `Cache-control` is it on the origin or in the client?

**Comment by efajardo** [comment]
@DrDaveD do I understand the problem is that the HTTP header that Xrootd is sending to client (in this case the squid) does not contain the appropiate header on how long ago the file changed?

**Comment by DrDaveD** [comment]
Not quite.  File modification times, when included, are sent in a Last-Modified header.  That is treated differently and introduces its own set of challenges, I don't recommend it.  What's missing is the header to say how long to cache things.  When that's missing, squid makes a calculation based on how old the Date header is, but the better thing to do is to include the Cache-control header so squid doesn't need to guess.

In any case, the best solution would be to put those data files into regular CVMFS instead of caching them in squid via stashcache.  Then they would be able to take advantage of the cvmfs client cache in addition to squid.  Data files such as those which behave a lot like code as far as the infrastructure is concerned should be distributed with the code.  See the [cvmfs documentation on repository content](https://cvmfs.readthedocs.io/en/stable/cpt-repo.html#limitations-on-repository-content).

**Comment by efajardo** [comment]
@DrDaveD but I am still lost this header `Cache-control: max-age` who is responsible  for setting it up the client (the curl) or the (xrootd http server). I tried this without much luck:

```console
efajardo@uaf-7 ~$http_proxy="http://cvmfs-1.t2.ucsd.edu:3128" curl -H "Cache-Control: max-age=86400" -v http://stashcache.t2.ucsd.edu:8000/user/dweitzel/public/blast/queries/query1 -O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* About to connect() to proxy cvmfs-1.t2.ucsd.edu port 3128 (#0)
*   Trying 169.228.130.85...
* Connected to cvmfs-1.t2.ucsd.edu (169.228.130.85) port 3128 (#0)
> GET http://stashcache.t2.ucsd.edu:8000/user/dweitzel/public/blast/queries/query1 HTTP/1.1
> User-Agent: curl/7.29.0
> Host: stashcache.t2.ucsd.edu:8000
> Accept: */*
> Proxy-Connection: Keep-Alive
> Cache-Control: max-age=86400
> 
< HTTP/1.1 200 OK
< Content-Length: 103
< Date: Tue, 22 Oct 2019 16:54:31 GMT
< X-Cache: MISS from cvmfs-1.t2.ucsd.edu
< Via: 1.1 cvmfs-1.t2.ucsd.edu (squid/frontier-squid-4.4-2.1.osg34.el7)
< Connection: keep-alive
< 
{ [data not shown]
100   103  100   103    0     0  10200      0 --:--:-- --:--:-- --:--:-- 11444
* Connection #0 to host cvmfs-1.t2.ucsd.edu left intact```

**Comment by DrDaveD** [comment]
The server has to set it.  It's possible for a client to set it as well to decrease the time but I don't think it can increase the time.

**Comment by xrootd-dev** [comment]
I would recommend simply using Xcache in place of the squid caching server, It would perform a lot better and be able to handle a lot more clients. Frankly, for these kinds of things squid is not particularly well suited. Plus, if you have header issues, then it’s easy to go into the stack and straighten it out. We would all benefit from such changes.

Andy

**Comment by abh3** [comment]
Indeed, and what I’m saying is that perhaps one should start rethinking that configuration. I don’t think the cvmfs worker caches are impacted.

**Comment by DrDaveD** [comment]
In what way?  Are you suggesting that we put an xcache server at every site like we do squids?  Assuming they're all configured with high performing and relatively large disk caches, that's not something we can expect small sites to do.  Squids could be configured with high disk performance too, but that's more expensive and it wasn't needed for their current applications which have a very high hit rate and small working set, so that's why they have slow and small disks.  Edgar's use case is also high hit rate and small working set, so it fits naturally into the ordinary cvmfs existing infrastructure.  @bbockelm's design for the cvmfs integration with xcache was intended for partially shared & larger files, not for the completely shared smaller files of Edgar's use case.

**Comment by abh3** [comment]
Hmm, I wasn't anticipating that my comment would produce such a reaction. 
Xcache has nothing to do with high performance disk or whatver. The simple 
fact that Xcache is multithreaded and optmized for data files puts it 
ahead of squid for data applications, especially when resources may be
potentially scarce. It's generally a 1-for-1 replacement. I don't see any 
issue in suggesting that from a resource optimization perspective that 
Xcache would be a better choice.

Andy

**Comment by DrDaveD** [comment]
Squid can get as high of cpu performance as we need with multiple workers (one thread per cpu), and is the only implementation of a forward proxy cache that I have found that has any sizeable amount of user base.  There are lots of popular reverse proxies, but those have their own configuration challenges that don't fit well with collaborative administrative access.  I'm not fully familiar with xcache's forward proxy capabilities.  I do know that cvmfs uses it as kind of a hybrid, using a long URL on the server that it treats as an origin server but can still end up with client-specified different backend origin servers, but that's not the same thing as an http forward proxy which accepts any backend http URL.  I have years of experience working through squid http forward proxy caching bugs, and it would take a lot of convincing that another drop-in replacement would have enough significant advantages to go through the process again with another software package.

Dave

**Comment by abh3** [comment]
Discussion closed.
