### ISSUE TITLE
Unable to build 5.0.0 RC1 from GitHub tarball

### ISSUE THREAD

**Issue by chrisburr** [xrootd/xrootd#1088]
The GitHub release tarball doesn't contain `externals/crc32c` which causes the build to fail.

See
https://github.com/conda-forge/xrootd-feedstock/pull/16
and
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=97016

**Comment by simonmichal** [comment]
@chrisburr : thanks for reporting it, fixed in b1f669c23c1e4e3d7b417f6efafe6c0283ab040c

That said, the GitHub release tarball does not have the submodules checked out and it is stripped from git metadata so I cannot check it out from CMake either. Hence my advice to build from source RPM, which will allow you to build also submodules:
http://xrootd.web.cern.ch/xrootd/sw/releases/5.0.0-rc1/rpms/source/

**Comment by chrisburr** [comment]
I'm not sure if that is the best fix. It's probably better for it to fail loudly and require people to pass `-DBUILD_CRC32C=OFF` if that's what they want.

I don't know what your release process it like but you can also upload your own source tarballs to GitHub releases which might be a better solution? It's nice having them on GitHub as it makes it easier for generic updater bots to find new versions (I think conda-forge's bot is smart enough to also find it on http://xrootd.web.cern.ch/ but the point remains).

**Comment by simonmichal** [comment]
@chrisburr : again thanks for your feedback, I've reverted b1f669c and added on option for enabling CRC32C submodule to the cmake infrastructure: `-DENABLE_CRC32C=ON/OFF` (339452b40deee606f1064c3354980d7b112fbe3d).

Regarding the release tarballs I can have a look on that, could you please create a separate issue for that (so I don't forget)?
