### ISSUE TITLE
Default XrdAcc requires AuthFile from /opt/xrd/etc/AuthFile

### ISSUE THREAD

**Issue by esindril** [xrootd/xrootd#1124]
The default XrdAcc will fail to load if it does not find an AuthFile at the following location:
`/opt/xrd/etc/AuthFile`
First of all, this path is not owned nor created by any of the XRootD packages therefore to have this working the directory structure would need to be created by manually. This requirement is hard-coded and seems quite arbitrary:
https://github.com/xrootd/xrootd/blob/master/src/XrdAcc/XrdAccConfig.cc#L107
I would suggest to move this file in one of the directories created by the rpm packages and owned by the XRootD daemon like for example: /etc/xrootd/ or /var/spool/xrootd/.
Moreover if this file does not exits then the plugin loading fails. This is fine in principle, but the XrdAccSciTokens plugin relies on the default XrdAcc being able to load, therefore if this AuthFile is not there then the XrdAccSciTokens doesn't load properly.
Maybe it would be reasonable to ship the rpm packages with an empty AuthFile that already makes the XrdAcc loading happy and leave it to the sysadmin to further configure it if need be.

**Comment by abh3** [comment]
That is only true because we need some kind of default. We don't expect anyone to use the default (unless it's convenient). The correct way to handle this is to specify the location of the authfile in he config file using the acc.authdb directive. See:

https://xrootd.slac.stanford.edu/doc/dev49/sec_config.htm#_Toc517294126

This has always been true. If this isn't specified, the hard-coded default applies, as documented in that reference.
