### ISSUE TITLE
Unable to DELETE non-empty directory

### ISSUE THREAD

**Issue by djw8605** [xrootd/xrootd#1222]
This was originally reported in https://github.com/scitokens/xrootd-scitokens/issues/26.

XRootD HTTP interface is unable to delete non-empty directories.  Is this expected behavior?  I don't think this is a SciTokens restriction.

**Comment by abh3** [comment]
Perhaps not. Since the HTTP plugin uses the standard xrootd framework and 
that framework follows the POSIX standard, deleting non-empty directories 
is forbidden to simply save you from a misguided and potentially 
disastorous deletion. Imagine "rm /" which has happened in the past (not 
that we could do that but the idea is basically the same).

**Comment by vokac** [comment]
Other storage implementation follow WebDAV DELETE behavior https://tools.ietf.org/html/rfc4918#section-9.6.1

**Comment by abh3** [comment]
There has been no response to our resistance to allow deletion of non-empty directories. So, I assume it has become a non-issue and I am closing this ticket.
