### ISSUE TITLE
Possibly wrong adminpath generated for cmsd

### ISSUE THREAD

**Issue by smithdh** [xrootd/xrootd#1255]
Hi,

While testing a build based on master, (approx ~v5) I noticed that for a cmsd with adminpath set like this:

all.adminpath /var/spool/xrootd

The cmsd was listening here:

cmsd    500 xrootd   17u     unix 0xffff9d096115e000      0t0 755209640 /var/spool/xrootd/xxx.cern.ch/.olb/olbd.admin

(xxx.cern.ch was the host name of the test machine, the xrootd instance name was 'clustered'). The xrootd daemon with similar adminpath setting was attempting to connect:

200720 16:35:31 489 cms_Finder: Waiting for cms path /var/spool/xrootd/clustered/.olb/olbd.admin

I thought the problem might be:

XrdCmsConfig.cc
```
1394: int XrdCmsConfig::xapath(XrdSysError *eDest, XrdOucStream &CFile)
...
1423:    AdminPath = XrdOucUtils::genPath(pval,XrdOucUtils::InstName(myName,0));
```

With myName possibly used instead of myInsName.

**Comment by abh3** [comment]
Yes, unfortunate regression. Until a patch comes along you can avoid this problem by doing one of the following:
1) Use the command line -a or -A options to set the adminpath instead of using the 'all.adminpath' directive. See https://xrootd.slac.stanford.edu/doc/dev50/xrd_config.htm#_Toc39615217

2) Bracket the 'all.adminpath' directive so that the cmsd does not see it, for instance:
if exec xrootd
all.adminpath <path>
fi

Head will be patched shortly.
