### ISSUE TITLE
XRootD fails to start if ofs.tpc directive is given and xrootd client is not installed

### ISSUE THREAD

**Issue by efajardo** [xrootd/xrootd#1279]
In XRootD5 it fails to start with this error:

```
200910 21:25:31 017 ofs_Run: Unable to set up xrdcp; no such file or directory
```

When using the directive

```
ofs.tpc streams 5,10
```

When the xrootd-client RPM is not installed. This was not the case in XRootD4 and should not be the case since one can do HTTPS TPC transfers without xrdcp.

I consider this a bug

**Comment by efajardo** [comment]
@aaarora can you upload your `xrootd config`

**Comment by aaarora** [comment]
cms.space min 2g 5g
if defined ?~XRDHTTPPORT
   set eXRDHTTPPORT = $XRDHTTPPORT
else
   set eXRDHTTPPORT = 8080
fi
all.export    /
if exec xrootd
  http.exthandler xrdtpc libXrdHttpTPC.so
  xrd.port $eXRDHTTPPORT
  xrd.protocol http:$eXRDHTTPPORT /usr/lib64/libXrdHttp.so
fi
all.sitename TPC-HTTP-PRPSite
ofs.tpc streams 5,12
oss.localroot /mnt/ramdisk

**Comment by xXxrAinZyian** [comment]
Thanks

**Comment by aaarora** [comment]
XRootD initializes successfully using
`ofs.tpc streams 5,12 pgm /usr/bin/xrdcp`
and 
`ofs.tpc streams 5,12 pgm /usr/bin/curl`

**Comment by abh3** [comment]
I believe that the resolution to this problem is that the program to be used was specified without an absolute path. Hence, the server was not able to verify its existence. I agree that we should make that a requirement (.e. absolute path) but hat would likely break backward compatibility in instances where a relative path actually resolves the executable. So, I am closing this with the admonition to always use absolute paths. We will change the documentation to make this more clear.
