### ISSUE TITLE
Cancel a transfer when throughput is lower than a configured treshold

### ISSUE THREAD

**Issue by ddavila0** [xrootd/xrootd#1303]
When dealing with TPC-HTTP transfers we have noticed that in many cases[1] a transfer starts with a decent throughput (e.g. tens of MB/s) but after some time the throughput drops very badly (e.g. tens of KB/s or even 0) and the transfers keeps going until the client-defined timeout is met (sometimes hours later depending on the size of the file). 

Would it be possible to configure:
 a) a minimum amount of data that has to be transferred in 
 b) a max amount of time 
otherwise the transfer gets canceled?
similar to curl options: --speed-time  and --speed-limit

[1]
INFO    Fri, 09 Oct 2020 14:48:17 +0200; [1602247697088] BOTH http_plugin	TRANSFER:TYPE	3rd pull
INFO    Fri, 09 Oct 2020 14:48:25 +0200; bytes: 0, avg KB/sec:0, inst KB/sec:0, elapsed:7
INFO    Fri, 09 Oct 2020 14:48:31 +0200; bytes: 0, avg KB/sec:0, inst KB/sec:0, elapsed:13
INFO    Fri, 09 Oct 2020 14:48:36 +0200; bytes: 190398464, avg KB/sec:10329, **inst KB/sec:37187**, elapsed:18
INFO    Fri, 09 Oct 2020 14:48:41 +0200; bytes: 439484416, avg KB/sec:18660, inst KB/sec:48649, elapsed:23
INFO    Fri, 09 Oct 2020 14:48:46 +0200; bytes: 641482752, avg KB/sec:22373, inst KB/sec:39452, elapsed:28
INFO    Fri, 09 Oct 2020 14:48:51 +0200; bytes: 819216384, avg KB/sec:24242, inst KB/sec:34713, elapsed:33
INFO    Fri, 09 Oct 2020 14:48:57 +0200; bytes: 945258496, avg KB/sec:24292, inst KB/sec:24617, elapsed:38
INFO    Fri, 09 Oct 2020 14:49:01 +0200; bytes: 945520640, avg KB/sec:21473, **inst KB/sec:51**, elapsed:43
INFO    Fri, 09 Oct 2020 14:49:06 +0200; bytes: 945782784, avg KB/sec:19242, inst KB/sec:51, elapsed:48
INFO    Fri, 09 Oct 2020 14:49:13 +0200; bytes: 946421760, avg KB/sec:16804, inst KB/sec:89, elapsed:55
INFO    Fri, 09 Oct 2020 14:49:18 +0200; bytes: 946683904, avg KB/sec:15408, inst KB/sec:51, elapsed:60

... continues like this for hours then it drops to 0

INFO    Fri, 09 Oct 2020 17:02:35 +0200; bytes: 994607104, avg KB/sec:120, **inst KB/sec:0**, elapsed:8057
INFO    Fri, 09 Oct 2020 17:02:40 +0200; bytes: 994607104, avg KB/sec:120, inst KB/sec:0, elapsed:8062
INFO    Fri, 09 Oct 2020 17:02:45 +0200; bytes: 994607104, avg KB/sec:120, inst KB/sec:0, elapsed:8067
INFO    Fri, 09 Oct 2020 17:02:50 +0200; bytes: 994607104, avg KB/sec:120, inst KB/sec:0, elapsed:8072
INFO    Fri, 09 Oct 2020 17:02:55 +0200; bytes: 994607104, avg KB/sec:120, inst KB/sec:0, elapsed:8077

... until the timeout is hit
INFO    Fri, 09 Oct 2020 20:48:17 +0200; bytes: 994607104, avg KB/sec:44, inst KB/sec:0, elapsed:**21599**
INFO    Fri, 09 Oct 2020 20:48:22 +0200; [1602269302722] BOTH http_plugin	TRANSFER:EXIT	ERROR: Copy failed with mode 3rd pull, with error: Connection terminated abruptly; Status of TPC request unknown

**Comment by vokac** [comment]
This is "normal" (bad) behavior caused by old libcurl 7.29 shipped with CentOS7
https://github.com/xrootd/xrootd/blob/d3c1e340a2bf2ffa8aa32b107434474f8435b1df/src/XrdTpc/XrdTpcState.cc#L73-L80
I recently found several stuck FTS transfers to EOS that wait several hours for long FTS transfer timeout (calculated ± using filesize in MB divided by minimum speed 0.25MB/s). This is not really robust behavior, because number of active FTS transfers is limited (per site and per link).

**Comment by bbockelm** [comment]
Hi @vokac -

I do think this is something we can fix.  We break out of the transfer loop every 5 seconds to send out performance markers; we could check for how long it's been since the last forward progress.  Do you think we should make this configurable (in HTCondor, we have one hardcoded timeout for the first byte to transfer and a second, shorter one, for any subsequent period without data movement)?

That said, I am confused as to why FTS isn't cancelling these transfers - that's exactly what it does for GridFTP, right?

Brian

**Comment by vokac** [comment]
Hi @bbockelm,

you are right that FTS/gfal2 should provide more robust behavior for stuck HTTP-TPC transfers. There is now [DMC-1227](https://its.cern.ch/jira/browse/DMC-1227) ticket for gfal2 to implement something similar to `GRIDFTP PLUGIN:PERF_MARKER_TIMEOUT`.

Petr

**Comment by abh3** [comment]
I believe this has been implemented via various config client envars in 5.3.
