### ISSUE TITLE
"xrdfs host ls -l dir" not reporting all dirents under 5.0.3

### ISSUE THREAD

**Issue by wyang007** [xrootd/xrootd#1340]
This doesn't looks like a xrdfs problem but rather like a server side problem. for example:

$ hostname -f
cent7a.slac.stanford.edu
$ which xrootd
/bin/xrootd
$ xrootd -version
v5.0.3
$ xrootd

On another host, i run 

$ xrdfs cent7a.slac.stanford.edu ls /tmp |wc -l
130
$ xrdfs cent7a.slac.stanford.edu ls -l /tmp | wc -l
5

the "ls -l" only shows a few dirents. The same tests against a xrootd 4.12.1 server gives consistent result.

**Comment by xrootd-dev** [comment]
Actually, this appears to be a client problem. I tried with a different 
protocol testing program and the server returned the correct information 
but xrdfs exhibited the behaviour you saw. The reason this works with a 
4.x server is because the 4.x series does not return some additional 
information which appears to confuse the 5.x xdfs. Could you cut a tickt 
on this? It would be nice to include a fix in 5.1.0 while it's still in RC 
status.

Andy
