### ISSUE TITLE
v4<->v5 communication (in)compatibility?

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1356]
Hi! is there a known communication incompatibility between v4 redirector and v5 server?
I try to make this work but no success .. i commented out the monPerf (from cms.sched)
to reduce the number of potential problems, now the logs on the data server are seemingly
without errors but the data server is not subscribed to redirector ...
Moreover i see no message in the redirector logs about some subscription request ... 
configuration and logs :  https://cernbox.cern.ch/index.php/s/qzeEISru1gbL3uS

**Comment by abh3** [comment]
There are no known issues. That doesn't mean there aren't any. I will look at the logs.

**Comment by abh3** [comment]
The issue here is that the xrootd@storage06 is not rendezvousing wit the cmsd@storage02 and hence the cmsd will not start talking to the redirector until that happens. The line here in he cmsd.log:
201209 12:26:29 17136 Start: Waiting for primary server to login.

On the other hand, the xrootd thinks it's connected to the cmsd as shown in the xrd.log:
201209 12:26:30 17160 cms_Finder: Connected to cmsd via /tmp/xrootd_1000/storage01/storage01/.olb/olbd.admin

When this happens it means that the path to the named pipe for the xrootd is not the same as the one the cmsd is using. The xrootd wants to use "/tmp/xrootd_1000/storage01/storage01/.olb/olbd.admin". Unfortunately, we don't display that in the cmsd log and we will correct that in a future release.

How does this happen? Usually because a) the instance names differ (i.e. the -n command line option), or b) the adminpaths differ. Since there was no all.adminpath directive in the config file, it must have been supplied by on the command line using the -a or the -A command line option. Unfortunately, we do not display the command line in the log file so I can't tell (we will coret that in a future release).

Some unrelated observations:
1) Placing he adminpath in "/tmp" is highly discouraged. Various control files are placed in this path and many sites (perhaps not yours) run a /tmp cleanup daemon that happily deletes old files in /tmp. If that happens to files in the adminpath the system will likely stop working. The message in the log draws attention to this:
Config warning: adminpath resides in /tmp and may be unstable!

2)  There is an error in the config file as noted by the message:
Config warning: ignoring unknown directive 'e/aliprod/data'.
=====> oss.namelib /usr/lib64/libXrdAggregatingName2Name.so /home/aliprod/data 
This is a bug (thank you for tripping over it) and will be corrected in 5.1.0.

3) There is no reason to scan idle links for the cmsd and, in fact, is discouraged as it causes unnecessary disconnections. The xrd.timeout directive should only apply to the xrootd. This is especially true because of the remarkably short idle timeout of 10 seconds that causes the system to scan all the links every 6 seconds. Is it necessary to have such a short timeout?

4) I hope starting the servers in debugging mode was for my benefit. Running servers at this debugging mode easily reduces performance by as much as 50% along with creating huge log files.

So, all I need to see is what the startup command line was for each server (xrootd and cmsd) and that will tell the story.

**Comment by adriansev** [comment]
I will try to answer point by point

> The issue here is that the xrootd@storage06 is not rendezvousing wit the cmsd@storage02 and hence the cmsd will not start talking to the redirector until that happens. The line here in he cmsd.log:

erm, is that storage02 above is a typo, or is something wrong in settings? the configuration specify the rd.spacescience.ro as redirector and i see not storage02 mentions

> 201209 12:26:29 17136 Start: Waiting for primary server to login.
> 
> On the other hand, the xrootd thinks it's connected to the cmsd as shown in the xrd.log:
> 201209 12:26:30 17160 cms_Finder: Connected to cmsd via /tmp/xrootd_1000/storage01/storage01/.olb/olbd.admin
> 
> When this happens it means that the path to the named pipe for the xrootd is not the same as the one the cmsd is using. The xrootd wants to use "/tmp/xrootd_1000/storage01/storage01/.olb/olbd.admin". Unfortunately, we don't display that in the cmsd log and we will correct that in a future release.

ooh.. that fencing !! so the problem is that pidfile is not fenced and admin path is .. and i did:
https://github.com/adriansev/alicexrd/blob/master/xrdctl#L218
https://github.com/adriansev/alicexrd/blob/master/xrdctl#L242
i fixed this, but it still does not work, i updated the logs in the cernbox share.

> How does this happen? Usually because a) the instance names differ (i.e. the -n command line option), or b) the adminpaths differ. Since there was no all.adminpath directive in the config file, it must have been supplied by on the command line using the -a or the -A command line option. Unfortunately, we do not display the command line in the log file so I can't tell (we will coret that in a future release).

the starting commands are:
https://github.com/adriansev/alicexrd/blob/master/xrdctl#L234
https://github.com/adriansev/alicexrd/blob/master/xrdctl#L257

> 
> Some unrelated observations:
> 
> 1. Placing he adminpath in "/tmp" is highly discouraged. Various control files are placed in this path and many sites (perhaps not yours) run a /tmp cleanup daemon that happily deletes old files in /tmp. If that happens to files in the adminpath the system will likely stop working. The message in the log draws attention to this:
>    Config warning: adminpath resides in /tmp and may be unstable!

yes, i know, i wanted a general available directory so i used /tmp .. that that you mention i could just use /var/tmp or just use the user home and be done with it ... but so far was safe... on centos /tmp is not tmpfs (like in fedora) and for certain there is NO periodic cleaning of /tmp in any systems that use systemd

> 2. There is an error in the config file as noted by the message:
>    Config warning: ignoring unknown directive 'e/aliprod/data'.
>    =====> oss.namelib /usr/lib64/libXrdAggregatingName2Name.so /home/aliprod/data
>    This is a bug (thank you for tripping over it) and will be corrected in 5.1.0.

oohh .. ok...  will this require another recompilation/rebuild of XrdAggregatingName2Name plugin? (this is an ALICE specific plugin, packaged by me and in use by the ALICE vanilla xrootd installations)


> 3. There is no reason to scan idle links for the cmsd and, in fact, is discouraged as it causes unnecessary disconnections. The xrd.timeout directive should only apply to the xrootd. This is especially true because of the remarkably short idle timeout of 10 seconds that causes the system to scan all the links every 6 seconds. Is it necessary to have such a short timeout?

well, it's always better to free unused resources as not to have contention of any kind .. so, if idle then the job is done, let's close it ..  but i do not get 2 things:
1. given that xrd.timeout is prefixed with xrd i imagine that automatically works only for xrootd .. i imagine that it would have been a general instruction, there could be a all.timeout and specific for cmsd a cms.timeout ... isn't it like this?
2. i do not get the scan thing... is this a hidden implication? like to kill after N seconds then the connection list must be checked every `N - safe_value` ?

> 4. I hope starting the servers in debugging mode was for my benefit. Running servers at this debugging mode easily reduces performance by as much as 50% along with creating huge log files.

obvious, given that things does not work of course i enabled the debug :)

> So, all I need to see is what the startup command line was for each server (xrootd and cmsd) and that will tell the story.

https://github.com/adriansev/alicexrd/blob/master/xrdctl#L234
https://github.com/adriansev/alicexrd/blob/master/xrdctl#L257

We can discuss over email to give you a reminder about your access to the machine :)

**Comment by abh3** [comment]
Yes, that was a typo. Looking back at the logs, the hostnames match.

As for fencing. We still do fencing for the all.pidpath directive but not for the '-s' command line option. This is in keeping of what systemd expects.

Point (2) No you don't have to do anything. This was a config re-parse error. It shouldn't have happened but, in practice, didn't affect anything other than put out a misleading message.

Point (3) Idle links produce almost no contention. The only reason you want to trim idle links is to make more file descriptors available. Generally, you likely have more than enough. Most sites, if they use this directive, specify an idle timeout on the order of 10 to 20 minutes. A timeout of 20 seconds may actually decrease the performance of root jobs as many of them read some data and then take a minute or so to process what they read. In the mean time the links gets closed and has to get re-established. Of course, that depends on the kind of jobs you are running.

As what directives apply, the "xrd." prefixed directive applies to anything that uses the "xrd" protocol driver framework. So, in this case, xrootd and cmsd. Note that each of those has a different directive prefix. In other scenarios it would apply to DPM, EOS, and other similar systems that use the "xrd" framework. I strongly suggest you increase that to about 20 minutes.

I will look at the new logs. One thing that is for sure is there is a mismatch between what the xrootd thinks the environment is and what the cmsd thinks.

**Comment by adriansev** [comment]
> Yes, that was a typo. Looking back at the logs, the hostnames match.
> 
> As for fencing. We still do fencing for the all.pidpath directive but not for the '-s' command line option. This is in keeping of what systemd expects.

by the way, talking about what systemd and an administrator would expect, i would say that all directives that do fencing
(-a, -w) should have the `=` option of log option. to give full control and expectations to the administrator

> 
> Point (2) No you don't have to do anything. This was a config re-parse error. It shouldn't have happened but, in practice, didn't affect anything other than put out a misleading message.

ok, got it

> 
> Point (3) Idle links produce almost no contention. The only reason you want to trim idle links is to make more file descriptors available. Generally, you likely have more than enough. Most sites, if they use this directive, specify an idle timeout on the order of 10 to 20 minutes. A timeout of 20 seconds may actually decrease the performance of root jobs as many of them read some data and then take a minute or so to process what they read. In the mean time the links gets closed and has to get re-established. Of course, that depends on the kind of jobs you are running.
> 
> As what directives apply, the "xrd." prefixed directive applies to anything that uses the "xrd" protocol driver framework. So, in this case, xrootd and cmsd. Note that each of those has a different directive prefix. In other scenarios it would apply to DPM, EOS, and other similar systems that use the "xrd" framework. I strongly suggest you increase that to about 20 minutes.

ok, increased to 300s :)

> 
> I will look at the new logs. One thing that is for sure is there is a mismatch between what the xrootd thinks the environment is and what the cmsd thinks.

i added in the cernbox directory also the /proc content and the .env files of the services

**Comment by adriansev** [comment]
and i noticed a really strange thing:
```
aliprod@storage06: storage01 $ echo -ne "query config version\nspaceinfo /\nexit\n" |/usr/bin/xrdfs localhost:1094
[localhost:1094] / > query config version
v5.0.3

[localhost:1094] / > spaceinfo /
[ERROR] Server responded with an error: [3011] Unable to locate /; no such file or directory
```

**Comment by abh3** [comment]
OK, once you start it up could you do "ps -ef | grep cms"? I have a sneaky suspicion that there are two of those things running.

**Comment by adriansev** [comment]
@abh3  nope..
```
aliprod@storage06: ~ $ ps -ef | grep cms | grep -v grep
aliprod  29598     1  0 Dec11 ?        00:00:01 /usr/bin/cmsd -b -d -n storage01 -s /home/aliprod/xrd_srv/xrootd_1000/storage01/cmsd.pid -a /home/aliprod/xrd_srv/xrootd_1000 -w /home/aliprod/xrd_srv/xrootd_1000 -l /home/aliprod/alicexrdrun/logs/cmsd.log -c /home/aliprod/alicexrdconf/xrootd1.xrdcfg
```

**Comment by adriansev** [comment]
> and i noticed a really strange thing:
> 
> ```
> aliprod@storage06: storage01 $ echo -ne "query config version\nspaceinfo /\nexit\n" |/usr/bin/xrdfs localhost:1094
> [localhost:1094] / > query config version
> v5.0.3
> 
> [localhost:1094] / > spaceinfo /
> [ERROR] Server responded with an error: [3011] Unable to locate /; no such file or directory
> ```

so, it seems that if directory specified by N2N mapping layer is not created, no error is thrown but also there is the error above..  now, with directory created i have
```
echo -ne "query config sitename\nquery config version\nspaceinfo /\nexit\n" |/usr/bin/xrdfs storage06.spacescience.ro:1094
[storage06.spacescience.ro:1094] / > query config sitename
ALICE::ISS::FILE

[storage06.spacescience.ro:1094] / > query config version
v5.0.3

[storage06.spacescience.ro:1094] / > spaceinfo /
Path:               /
Total:              0
Free:               0
Used:               0
Largest free chunk: 0
[storage06.spacescience.ro:1094] / > exit
Goodbye.
```

**Comment by adriansev** [comment]
another thing to note is that xrootd process is consuming 100% cpu and the strace shows nothing ...

**Comment by adriansev** [comment]
well, it seems that that 100% cpu was because of debug mode...

**Comment by adriansev** [comment]
ping @abh3 whenever you have time, can you take a further look? just a reminder: the redirector is 4.12.3, and i would be really reluctant to upgrade, because if it does not work then all cluster would be dead. thanks a lot!!

**Comment by abh3** [comment]
Hi Adrian,

I will look. I've just been overwhelmed with many other activities. So, 
please bear with me.

Andy

**Comment by adriansev** [comment]
@abh3 of course, there is no problem at all! whenever you have time is fine :)

**Comment by abh3** [comment]
Hi Adrian,

I finally looked and indeed it's gotten itself in a situation where they 
won't talk to each other I though we had fixed that. Could you install the 
debug RPM on that machine. Giving access to the source files would also be 
helpful but not necessary if that is too difficult. Once you tell me the 
RPM is installed, I'll dig deeper. That said, I see a similar situation 
develop in my test setup but it doesn't result in a problem.

Andy

**Comment by adriansev** [comment]
@abh3 would you prefer to use the packages from xrootd.org instead of epel?

**Comment by adriansev** [comment]
i installed the epel one .. let me know if you need any other tools/packages

**Comment by abh3** [comment]
OK, so the problem is due to this seemingly innocuous directive in xrootd1.xrdcfg
 xrd.protocol xrootd *

What happens with this directive? It says load a protocol naming it xrootd using whatever protocol was bound to the executable (that is what the asterisk says). In this case the cmsd protocol. Since the framework automatically loads the protocol determined by the executable's name (i.e. cmsd) it is considered bound to the executable. Since the name of the protocol didn't match the one that was already loaded (i.e. cmsd); the framework loaded it once again under the name xrootd. So, internally, you actually had two cmsd protocol stacks running. Unfortunately, the cmsd protocol can only be safely configured once (it can't be run multiple times in the same process). This caused the second configuration attempt to create an inconsistent cmsd that simply would not work properly, though it wouldn't crash either.

What's the solution? Please follow these steps:
1) Kill the xrootd and cmsd daemons.
2) Remove all files in the admin path starting at /aliprod/xrd_srv/xrootd_1000/storage01
3) Remove the xrd.protocol xrootd * directive and associated comments; it is not needed in any context here.
4) Start the daemons once more.

This points out that we need to make additional checks to avoid such a problem in the future.

I will keep this ticket open until you verify this solves the problem.

**Comment by adriansev** [comment]
@abh3 i can confirm that now the servers appear to be subscribed to the redirector.  while is strange that it used to work and now no longer works, in hindsight, i could just protect the declaration in the same fashion that i do it just below for http part.
At this point, to close the ticket, i would like to know is this (commented) declaration is required, when could/should be required and how safe for the xrootd + http usage is to be removed.
Thanks a lot!!

**Comment by abh3** [comment]
Yes, you can do that (i.e. put the xrd.protocol for xroot with the http declaration protected by 'if exec xrootd') but it's unnecessary as the xroot protocol will be loaded anyway. In fact, the test we are putting in will check if you are trying to override what is considered the "static" protocol with a conflicting name. Technically, the protocol is named "xroot" not "xrootd". Yes, the documentation is wrong and will be corrected. This was changed in R5 to end the confusion between protocol and the executable running the protocol. The protocol for xrootd is xroot and for cmsd is cms. That change made is possible to fall into the trap of double loads (that was an oversight on out part). Fortunately, almost no one specifies the default protocol in the config file. With our new patch we will warn about the discrepancy and simply ignore the directive; which is safe to do as it changes nothing. So, it's up to you but I would suggest just getting rid of it as it is unnecessary.

**Comment by abh3** [comment]
So, thinking a bit more about it. To make this work in R5 you need to use the actual protocol name in the directive (i.e. "xroot") otherwise we get a double load issue. That is solved in R5.1 but that doesn't help you now.  So, in the end the safest approach is to not specify "xrd.protocol xrootd *" directive no matter the context. Once you are using 5.1.0 then you can safely do it (use "xroot" protocol to avoid nasty messages).

**Comment by adriansev** [comment]
@abh3 got it, i really do not wish to have settings that have no use, so i will just erase the mention to it.
