### ISSUE TITLE
Close errors and implications and other TLS issues

### ISSUE THREAD

**Issue by abh3** [xrootd/xrootd#1437]
What does it really mean when I issue a close() but get back an error saying "invalid session". This happens after the client has lost it's connection, typically due to a timeout or TLS error. Are there still requests that are queued for a retry in that situation?

Essentially,  XrdClFile has entered into an undefined state. While that corresponds to the POSIX definition of what happens when an error is returned on close() it doesn't play that well in the real world. Can the XrdClFile object be deleted? The current assumption is that it cannot be deleted which causes a memory leak. So, this needs to be resolved.

Second issue. It appears when you do a forced disconnect on a TLS socket it appears that the client is not going through the TLS shutdown procedure but simply closing the socket. That is bad because it generates lots of TLS errors and who knows what that triggers. Can this be investigated?

BTW The server always calls XrdTlsSocket::Shutdown() before physically closing the socket. The Shutdown() code in XrdTlsSocket skips the shutdown if a TLS error occurred. In the forced disconnect case, that is not a TLS error.

**Comment by simonmichal** [comment]
@abh3 : the client calls now `XrdTlsSocket::Shutdown` before closing the socket (e810e31908b49bbb8445c91118ae1b38c5577aa8).

**Comment by simonmichal** [comment]
Regarding the `invalid session` error on close, this could happen due to a TTL or stream timeout. In case of TTL the connection is being closed gracefully. In case of a stream timeout the server will get the `kXR_endsess` request on reconnect so it will also terminate the original connection. Hence, we know that in both cases the server is aware that the connection has been dropped. Now, as far as I understand, when a connection is shutdown the server also closes all files associated with that connection, @abh is this correct? If yes, I think we can safely say that the file has been actually closed.

Now, currently when there is a `errInvalidSession` error on close and the file is in read-only mode, the file state is set to `Closed`, however the `errInvalidSession` is propagated to the user:
https://github.com/xrootd/xrootd/blob/e810e31908b49bbb8445c91118ae1b38c5577aa8/src/XrdCl/XrdClFileStateHandler.cc#L995-L1002

If the answer to my question is yes, then I would say we could relax this and assume the file is successful closed in general (and not only for read-only files), furthermore we can return success to the user instead of returning `errInvalidSession`.

@abh3 : let me know your thoughts!

**Comment by abh3** [comment]
Indeed, the server closes all files opened by that connection. So, the 
behaviour you described would be the nehaviour that is wanted to prevent 
any memory leaks because the application thinks it cannot safely delete 
the file object. The only thing you should keep in mind is the following 
edge case:

1) A I/O was started,
2) The connection was lost (for whatever reason),
3) The outstanding I/O was queued for retry. Since yje I/O is queued the 
connection has not yet been re-established,
4) The application issues a close.
5) If you ignore the queue I/O and return successbecause the connection is 
gone then you will get a SEGV whe the queued I/O resumes.

So, it would seem you also need to be sensitive to the fact of whether or 
not there is still something queued for that connection and return failure 
on the close as would be the normally be the case.

**Comment by simonmichal** [comment]
absolutely, if there are any in-fly requests the close will fail

**Comment by xrootd-dev** [comment]
Perfect! Now we won't be leaking memory!

**Comment by simonmichal** [comment]
Done, the client will now treat an invalid-session error as success in case of the `File::Close` call: bf0af93ef8670eddf2c7d81965c94dea70f05ce9

I suppose we can close this one?

**Comment by abh3** [comment]
Great!
