### ISSUE TITLE
non-ASCII char in xroot error message

### ISSUE THREAD

**Issue by belforte** [xrootd/xrootd#1501]
looks like recent xroot (4.12.3-llifpc2) insert (at least at times) a non ASCII character at the end of an error message, see screenshot below.
This breaks current code which reports and parse those messages.
Can it be avoided ?
While I only have an example from using CMS code , @makortel  says that in this case it just prints xrootd message "as is"
![Screenshot from 2021-08-31 17-48-12](https://user-images.githubusercontent.com/1837785/131671605-0d4d1ba3-6ff0-463c-87f6-2ce8ce6d19fd.png)
Of course we can filter for non-ASCII on our side, but  @klannon suggested to report this to you as well for a proper resolution. In this I am the current maintainer of a tool which relies on CMS framework reports, so am 2 software layers (CMSSW and CMS/WMCore) away from xroot, simply acting as messenger here, but I doubt I can be of further help. 
Thanks

**Comment by simonmichal** [comment]
@belforte : thank you for reporting this issue and sorry for replaying with such a delay!

Could you you test with the latest release, I believe this should have been fixed in: https://github.com/xrootd/xrootd/commit/22d308a3dd689607ee0396860d377145836ef55b

**Comment by belforte** [comment]
thanks @simonmichal . Unfortunately I am stuck with what version of xroot is built with  CMSSW. But this should be easy to check on your side, just try to open a non-existing file. In any case I believe you can close.

**Comment by amadio** [comment]
Commit 22d308a likely fixes this, but it looks like commit a20fe39385 could have introduced a potential off by one error. The function where the message comes from is below.

https://github.com/xrootd/xrootd/blob/v5.5.1/src/XrdCms/XrdCmsCluster.cc#L2031-L2045

If `n` could be off by one here, it could cause an extra `'\0'` character to be shown in the output due to `Sel.Resp.Data` containing two `NUL` characters at the end instead of just one.
