### ISSUE TITLE
support stat() and unlink() in XrdEc

### ISSUE THREAD

**Issue by wyang007** [xrootd/xrootd#1559]
Is it possible to add support of stat() and unlink() in XrdEc ?

**Comment by xrootd-dev** [comment]
In a native xrootd cluster? Well, anything is possible because it's simply 
software. Is it easy? No, not in this case. No individual server knows 
it's part of an EC group as that is externally layered on the servers. So, 
a stat(0 or unlink() call would only affect an individual server leaving 
the stripes on other servers unaffected. Now, yes, to do an EC layout you 
need a redirector and, yes, unlink is supported across multiple servers 
but as you and I have found it is unreliable because a server may be down 
at the time an unlink happens. A true stat call in an EC layout would 
require that the redirector do some additional work or at least delegate 
it to a particular server. Doable but the code is simply not there to do 
it.  Alll of this requires some amount of architectural thinking in order 
to implement something that resembles a central metadata repository 
but is actually distributed (unless what you want is a central repo with a 
single point of failure). That is not an easy task but certainly doable. 
However, that said, today nothing you mentioned exists or if it does exist 
no one is happy with it.

Andy

**Comment by simonmichal** [comment]
@wyang007 : sorry for the late reply! I pushed recently two enhancements: 673dabf82fe98de1d4cf369e95f5206cd9067d76 and 080d8729dab9e60d1b12381d9a4db8bb998a103e, with those two `stat` will at least return correct file size. Also, now if some stripes are missing since the client will now the correct file size, `xrdcp` will be able to correctly copy the file out of the storage.

**Comment by wyang007** [comment]
I think we can close this one as we already made many changes. these requests are no longer relevant.
