### ISSUE TITLE
ZTN and Scitokens auth

### ISSUE THREAD

**Issue by jthiltges** [xrootd/xrootd#1584]
When using ZTN to pass the scitoken, the token reaches `XrdAccSciTokens::Validate()` as expected. However, a later call to `XrdAccSciTokens::Access()` fails.

https://github.com/xrootd/xrootd/blob/10d27966ce0a6637e988df5a7c43bdaad7d09b24/src/XrdSciTokens/XrdSciTokensAccess.cc#L312-L314

`Access()` expects to find the token with `env->Get("authz")` which I believe is only true for HTTPS.

With the current flow, it seems `Validate()` does a `scitoken_deserialize()` to process the token, and leaves ACLs to `Access()`. Then `Access()` generates ACLs, and puts them into a cache (keyed by the JWT).

As for possible solutions, the token could be stored in `Validate()` (which seems like something to avoid). Or we could refactor to instead generate the ACLs in `Validate()`.

**Comment by xrootd-dev** [comment]
That wasn't the intention and the ZTN should avoid doing any caching of 
ACLs because, if fact, ACLs are meaningless for ZTN. Why this happens 
would appear to be some kind of regression or oversight. For ZTN all we 
care about is that token was issued by a trusted token issuer. As for the 
authz key, that should be the case for http and xroot (assuming the token 
case in on a file url as "authz=....").

Andy

**Comment by bbockelm** [comment]
Hi all,

Took a quick look at the setup this morning.  I think it's behaving correctly but, unfortunately, the correct behavior isn't all that useful.

@abh3 - when we discussed ZTN with the dCache folks, one item discussed is what the ZTN token should do beyond authorizing a session creation (which is all it does today).

Particularly, my recollection was that if the user didn't present a token in a subsequent operation, we wanted to utilize the token from the session to determine whether the operation was authorized.

Implementing the "session token" behavior is fairly straightforward (preserve the session token in a XrdSecEntity attribute, utilize the token later in the authorization later) -- any objections to doing that?

Otherwise, we probably need an XrdCl update to always send a token with operations in addition to the session token.

Thoughts?

Brian

**Comment by abh3** [comment]
I don't have a problem with recording the session token in the attributes. However, we already have a field in the secentity structure for this (i.e. creds and credslen). So, I can do that which is what all other protocols do that are credentials based. When do you want it?

**Comment by bbockelm** [comment]
Ah, an existing mechanism is even better!  The code change is relatively simple, just wanted input on how to approach it.

@alrossi -- does the above proposal match what dCache does?

**Comment by alrossi** [comment]
No, it is precisely what I thought we were not supposed to do.  Perhaps I misunderstood the discussion I had with @abh3 but  the ZTN token is considered a "throw away" ... that the authorization token which appears as the opaque 'authz=' value needs to be there.  I remember this because I originally implemented authorization to fallback on the ZTN token if there is no authz= and then changed it.   Obviously, if the fallback is what we want, I can reimplement.

**Comment by alrossi** [comment]
Then the original ZTN needs things like the subject attribute which was not required to be there originally.

One of the other issues about the current way it works is that of redirect to dCache pools.   We are compelled to force TLS on the pools to protect the token sent with the opaque data, even though dCache does not reauthorize/re-authenticate on the pool.  It would be great if the client had a way not to send the token if it does not receive an authentication data request on login.  

(Of course, if we ever do implement TPC with tokens in xroot, then all bets are off because the TPC channel would need TLS to protect the token needed by the client on the destination side to authenticate with the source server ...)

**Comment by alrossi** [comment]
(Of course, a way around that issue is to implement control vs data channel kXR_bind, which I have considered and is on the back burner ... )

**Comment by bbockelm** [comment]
> Then the original ZTN needs things like the subject attribute which was not required to be there originally.

I'm not quite following.  There's a subject in the token (among many other things, some of which may or may not be useful for authorization).  I assume the semantics should be, if the token was not presented with a request, then the token from the session can be used as if it was presented with the request.

> We are compelled to force TLS on the pools to protect the token sent with the opaque data

I think TLS should be forced on the pools regardless, token or no token, unless you differentiate between trusted LAN and WAN transfers.

Redirection is another case where using the session token is probably useful - the client doesn't have to keep track as to whether the `authz` CGI header should be sent or dropped.

**Comment by alrossi** [comment]
```
Redirection is another case where using the session token is probably useful - the client doesn't have to keep track as to whether the authz CGI header should be sent or dropped.
```

Yes that is what I was implying (fallback would have that advantage).

```
I'm not quite following. There's a subject in the token 
```
ZTN does not check for the user.   It only checks issuer and audience.   A ZTN token does not require authorization data, only enough to demonstrate it is from a trusted issuer.   At least that is how I understood our original discussion.

**Comment by abh3** [comment]
OK, there is a lot of stuff going on here. So, let's go through what zrn was *supposed* to be for and what it seems people want it to do.

If you go back to the original discussion, we wanted to know that a client connecting to a server was capable of getting valid tokens. That's all. We didn't care who that was, what they were going to do, or anything else. All we cared about is showing proof of capability.

This is why it was implemented the way it was. The token only needs to be validated. We don't need any generated acls. All we need is that the token is for the acceptable audience issued by a known token issuer. Period, nothing more. That's why we never saved that token.

Now, it seems people want feature creep and want access to the token "just in case". We can do that by using the standard mechanism of placing the token in the creds field of the SecEntity structure and I would strongly resist any other approach as this is the standard way X509, Krb5 and other credential protocols do. As for exposure due to a core file, the token has an expiration date and hopefully these tokens are issued with a reasonably short lifetime so by the time the core file is exposed to unauthorized people (which would have a lot of other security implications outside of SciTokens), the token would have expired. So, I don't see this as very serious concern beyond exposing a core file no matter what.

So, my understanding that all that is wanted is to be able to access the ztn token in the case that a request does not have a url token. This, of course, runs in the face of narrow tokens and we might get stuck with fat tokens which is counter to what everyone wants. So, I don't see how this will play well in the future.

Have I missed something here?

**Comment by bbockelm** [comment]
> Have I missed something here?

I think the question is "how does one use token authorization using XrdCl or xrdcp?"

With the various issues around redirection @alrossi pointed out above, it's not clear that there's a great way to do this as a user.  The proposal above, to utilize the ZTN token as a session token, rather neatly addresses things with neither client nor protocol changes.

Let's say that a user has a single token and would like to download a single file with `xrdcp`.  How does one do this?

**Comment by abh3** [comment]
The way you would do it is to place the token on the url in the standard way:

xroot;//host//my/path?authz=[brearer%20]<token> 

Yes, this is very inconvenient but no worse than what you have to do for AWS. The nit here is "bearer%20" you may need to add that if the token you got doesn't have it. I've seen tokens both ways and I wish we could standardize that because it will confuse people to no end. Generally, the idea was that a url provider would give you a fully formed url so you don't think twice about it. Of course, for the one-off copies or whatever there is no url provider and, in fact, I have no idea how a person would get a token for a one-off copy (probably harder than we think ; enough to and make a user want x509 back).

Now, to other stuff. Whatever cgi a user specified should be carried across redirection. If that is not being done then it is a bug. I think we corrected that problem for certain edge cases some time ago. I don't know if that is also true for dCache but it should be as it's part of the protocol specification.

As for @alrossi getting confused, he should be confused because the "backup token" idea came out of the blue. So, Al you are right, the original plan was exactly what you thought it was. That said, I don't mind extending things. I just want to make sure it doesn't create new problems. I think @alrossi is on board with that and can make the appropriate changes. I can place the token in the creds field as it's a no-brainer.  Then you can use it as you see fit in the SciTokens plug-in.

Anyway, let me know whether or not you want access to the ztn token. Please @bbockelm finish off the review comments in the voms mapfile pull request. We are almost there.

**Comment by alrossi** [comment]
Just a quick reply to @***@***.***>.  Andy is correct that fallback or fall-through from the ZTN token or whatever we wish to call it can be (re-)implemented in dCache if so desired.   As for carrying tokens across redirects, that is largely the client's responsibility, so dCache just uses what it receives.  The only moment in which we would have to make sure this is happening inside of dCache is when we all agree upon native xroot TPC using tokens.   I have not heard anything specific about whether we are moving forward with that or not, so if I am behind the times, please let me know!

Thanks, Al

________________________________________________
Albert L. Rossi
Senior Software Developer
Scientific Computing Division, Scientific Data Services, Distributed Data Development
FCC 229A
Mail Station 369 (FCC 2W)
Fermi National Accelerator Laboratory
Batavia, IL 60510
(630) 840-3023

________________________________

**Comment by bbockelm** [comment]
> The way you would do it is to place the token on the url in the standard way:
> xroot;//host//my/path?authz=[brearer%20]

But this doesn't really work, does it?  You can't put secrets into the command line because they are visible across the system.  One would need to re-implement the token discovery logic external to the ZTN library and put it in `xrdcp` and `XrdCl` to have it auto-discover the token and/or have the user explicitly provide a token file.

Secondly, this doesn't work because the above invocation is only safe when TLS is used on the transport layer.  Again, this is only known at the XrdCl level and not a priori by the individual invoking the client.

**Comment by abh3** [comment]
Well, i believe it does because that's what the code allows. Indeed, you are correct that the user should use TLS to transmit the token via the URL. Unfortunately, nothing stops the user from not using TLS. I suppose we could test for the presence of 'authz' cgi in the client and force using TLS if it's there. I think the basic problem is that there is no defined way of how a user gets a one-off token, is there? ATLAS (and likely CMS) plans on having Rucio add the authz to the UR before handing back to the user who asked for it. Well, that's the idea anyway. Like I said, I have no issues of pointing to the ztn token from the SecEntity object. My question is whether the ztn token is valid for all file accesses the user wants to make; and if so, doesn't it make it a fat token?

**Comment by abh3** [comment]
OK, so now ztn will point to the initial token via the Entity.creds field. Can I close this?

**Comment by abh3** [comment]
After a 2.5 hour discussion on this topic, I do see the benefit of extending what ztn does as it's very much the same what a user would do in many circumstances. There is one caveat, if we allow the ztn token to be used as the default token(which is now possible to do in he SciToken authorization plug-in) then it either we do it always or we never do it. There is nothing in between if we want to provide reliable and consistent SciToken authorization. That mean a bit of work for @alrossi but I don't think he minds as long as the result leads to a better user experience. So, what is the verdict here?

**Comment by wyang007** [comment]
In is currently way, I have to put a token in both $BEARER_TOKEN, etc. and in CGI. Perhaps there is good reason behind it but this is not what users are expected. 

In fact, what appear in the CGI doesn't have to be a SciToken. It can be a macaroon token (passing a macaroon token is independent from Sec). I wonder whether there is a value to explore this - I view a macaroon token as something similar to the function of a signed URL. Maybe this one belongs to a different topic.

**Comment by alrossi** [comment]
I agree that the policy should be standard and expected.   I don't think it will take much for the dCache door to hang on to the ZTN token and "override" it with anything sent as CGI ... as I said, my original approach when I was first implementing this was precisely to do that.

I won't go ahead and make this change, however, until I get the green light from you all.

Also, I am curious:  aside from proprietary uses like ALICE, when GSI/x509 goes by the wayside, is native xroot third-party copy basically dead, or do we at some point plan to have a discussion about token support there?  I know last year Andy and I had this discussion and the conclusion was basically wait and see what other people want.   Any sense of this?

Thanks, Al

________________________________________________
Albert L. Rossi
Senior Software Developer
Scientific Computing Division, Scientific Data Services, Distributed Data Development
FCC 229A
Mail Station 369 (FCC 2W)
Fermi National Accelerator Laboratory
Batavia, IL 60510
(630) 840-3023

________________________________

**Comment by wyang007** [comment]
I expect the native xrootd TPC will not dead. xrootd TPC operations in two modes: X509 delegation and rendezvous key. The latter is used in cases where X509 is not used.

**Comment by alrossi** [comment]
As I recall, rendezvous key was prior to proxy delegation, but still required some sort of robocert on the destination host.  So it is still x509.  At least that is how it worked at the beginning.  Have I missed something?  If so, if the dCache third-party client needs to support this we will need to have a discussion.

________________________________________________
Albert L. Rossi
Senior Software Developer
Scientific Computing Division, Scientific Data Services, Distributed Data Development
FCC 229A
Mail Station 369 (FCC 2W)
Fermi National Accelerator Laboratory
Batavia, IL 60510
(630) 840-3023

________________________________

**Comment by wyang007** [comment]
robocert is not rendezvous key. It is something prior to x509 delegation so we no longer need robocert. rendezvous key is a time limited shared secret sent by the client to both endpoints, to facilitate TPC. It needs TLS. 
Whether dCache want to support rendezvous key is something to be discussed. The primary TPC in HEP is http though not exclusive. The rendezvous key in xrootd is used where x509 infrastructure is not available (and likely the token infrastructure is also not available, somewhere outside of HEP). 
When x509 goes away, in principle, we can use token for authentication and then use rendezvous key for TPC (to avoid a more complexed token chain reaction), though someone will say that token is only for authorization :-)

**Comment by alrossi** [comment]
Well yes, then, we need to discuss this.  I will need to know how to pass the secret key through from the destination server to the client on the destination side initiating the TPC with the source server.

This is new to me.

Al

________________________________________________
Albert L. Rossi
Senior Software Developer
Scientific Computing Division, Scientific Data Services, Distributed Data Development
FCC 229A
Mail Station 369 (FCC 2W)
Fermi National Accelerator Laboratory
Batavia, IL 60510
(630) 840-3023

________________________________

**Comment by abh3** [comment]
Hi Albert,

Here is where to start:

https://xrootd.slac.stanford.edu/doc/dev49/tpc_protocol.htm

Andy

**Comment by bbockelm** [comment]
> OK, so now ztn will point to the initial token via the Entity.creds field. Can I close this?

Yes, I think this is good enough to close!  Will try to send a corresponding PR today / tomorrow.

**Comment by alrossi** [comment]
Just so I understand the upshot of this:  essentially nothing changes on the server end for dCache with this because the client puts the ztn token in the CGI?

Sorry if I am a bit out of the loop here, have been quite busy with other things, but I want to make sure dCache doesn't get out of sync ...

Thanks, Al

________________________________________________
Albert L. Rossi
Senior Software Developer
Scientific Computing Division, Scientific Data Services, Distributed Data Development
FCC 229A
Mail Station 369 (FCC 2W)
Fermi National Accelerator Laboratory
Batavia, IL 60510
(630) 840-3023

________________________________

**Comment by abh3** [comment]
Hi Albert,

No, the upshot is as follows:

1) If the client specified a ScoToken in the CGI use it, otherwise
2) If ztn was used, use the ztn SciToken (if it is a SciToken), otherwise
3) Passthrough the authorization.

Brian's pull request will implement the above in the SciToken library as 
xrootd aleady supplies access to the token obtained via ztn.

So, dCache should do the same.

Andy

**Comment by alrossi** [comment]
OK, I misunderstood slightly from the last couple exchanges.  What you describe below is what I thought originally.

Will do,  Al

________________________________________________
Albert L. Rossi
Senior Software Developer
Scientific Computing Division, Scientific Data Services, Distributed Data Development
FCC 229A
Mail Station 369 (FCC 2W)
Fermi National Accelerator Laboratory
Batavia, IL 60510
(630) 840-3023

________________________________

**Comment by alrossi** [comment]
Hello again,

I'm reviewing the state of our code with respect to the rendezvous key.

We support it on open because it was what was needed before TPC Lite, although it is currently not protected by TLS, since this was with x509 originally.

The issue here is that before, the third-party client was being told to authenticate to the door (the source server).  I am unsure whether dCache as it is right now would be able to allow an override of authentication in the case of a rendezvous key being present.

Would this be done, for example, by giving to the open by the third-party client the same permissions given to the initiating client when it authorizes via JWT to the source (on open)?  Is that the idea?

Thanks, Al

________________________________________________
Albert L. Rossi
Senior Software Developer
Scientific Computing Division, Scientific Data Services, Distributed Data Development
FCC 229A
Mail Station 369 (FCC 2W)
Fermi National Accelerator Laboratory
Batavia, IL 60510
(630) 840-3023

________________________________

**Comment by abh3** [comment]
Hi Albert,

Correct, while TLS would have been preferable the additional safeguards put in place to protect the rendezvous token  made it highly unlikely to be subverted (you would need to accomplish at least three other subversion before the token became vulnerable).  Now that TLS is widely available nothing prevents the token being transmitted using TLS, though for backward compatibility, it's not required.

As you state it, the door is not in a position to use the rendezvous token presented by the destination since it needs to authenticate the destination first.  So, if that's how the code sits then, yes, without skipping authorization in the presence of a token, it would not work. Mind you rendezvous tokens are only meant to be used for pull requests so they are incapable of performing and destructive action.

So, presumably you are wondering that one could get around the problem by having the destination use a JWT along with the rendezvous token. The issue here is how does one get the JWT? I was told that it can't be the requesting clients JWT as these are not delegable, though I still don't see what prevents them from being used by someone else, hence why they need TLS. The destination server is also not really in a position of getting a JWT. Seems like an issue here.

Of course, that all hinges on whether the requesting client's JWT cannot be used by the destination server. If it can be (or at least if the client can get a delegable token) then, yes, we could handle the rendezvous in that way. That said, why bother with a rendezvous token at all since we could do the same thing with JWT's can't we?

So, in the end we need to get all of this straightened out to figure out the positioning of a rendezvous TPC.  Maybe @bbockelm will see this post and expand on how a requesting client's JWT can and cannot be used in a TPC context by the destination server.

**Comment by alrossi** [comment]
Hi Andy,

Thank you for this very good summary of the situation.  It reflects perfectly what I remember discussing with you last year.

I am interested to know what Brian thinks of all of this.

It would be nice to keep dCache on the same page as everyone else in this regard.

Cheers, Al

________________________________________________
Albert L. Rossi
Senior Software Developer
Scientific Computing Division, Scientific Data Services, Distributed Data Development
FCC 229A
Mail Station 369 (FCC 2W)
Fermi National Accelerator Laboratory
Batavia, IL 60510
(630) 840-3023

________________________________

**Comment by alrossi** [comment]
Just as a follow, and perhaps to state the obvious here.

The way ALICE's authorization scheme for TPC works (with dCache) is:


  1.   the directive --tpc delegate only is used.   This ensures that the tpc.scgi element is included in the opaque data given to the destination.
  2.   that tpc.scgi contains a separate authz= token.
  3.  The scgi becomes the cgi of the path used by the third-party client when communicating with the source server.

In this schema, it is then a matter of having the initiator/moderator of the TPC (in this case, xrdcp) pass two tokens, not one.   The second token is the one in the tpc.scgi, which I suppose we could refer to as the 'delegated' token, though it is not so in the sense that it should be used and then reused, but simply a token destined for the TPC client.

Is such a strategy not generalizable?

Al

________________________________________________
Albert L. Rossi
Senior Software Developer
Scientific Computing Division, Scientific Data Services, Distributed Data Development
FCC 229A
Mail Station 369 (FCC 2W)
Fermi National Accelerator Laboratory
Batavia, IL 60510
(630) 840-3023

________________________________

**Comment by alrossi** [comment]
With a couple of small tweaks, I have found a way to get dCache to support rendezvous TPC with bearer token primary authorization by the initiating client.   Most of the mechanism was actually in place for this, it was just a case of allowing this when a bearer token was actually present (which I made short-circuit the rendezvous check).

I just have to allow ZTN authentication not to fail if the client does not present a ZTN (i.e., the third-party client).  Otherwise, the bearer tokens must be expressed as the authz CGI ... unless xrdcp could optionally provide the authorization token from a file the way it does for ZTN.

Or maybe it does?  BEARER_TOKEN_FILE doesn't see to work when I point it at a token.  And if ZTN is not requested, the client doesn't seem to bother with XDG_RUNTIME_DIR either.

Anyway, we're close to conformity.

Al

________________________________________________
Albert L. Rossi
Senior Software Developer
Scientific Computing Division, Scientific Data Services, Distributed Data Development
FCC 229A
Mail Station 369 (FCC 2W)
Fermi National Accelerator Laboratory
Batavia, IL 60510
(630) 840-3023

________________________________

**Comment by bbockelm** [comment]
Chatting with Al at the WLCG BDT meeting today -- we think this ticket can be closed.  The xrootd-TPC discussion is alive and healthy on the mailing list but not exactly relevant to the original ticket item.  Would be good to create a fresh issue if we want to bring it to GitHub.

**Comment by abh3** [comment]
As requested.

**Comment by alrossi** [comment]
Not only that, we will need to be able to access it/check it in the dCache server on the source end.

________________________________________________
Albert L. Rossi
Senior Software Developer
Scientific Computing Division, Scientific Data Services, Distributed Data Development
FCC 229A
Mail Station 369 (FCC 2W)
Fermi National Accelerator Laboratory
Batavia, IL 60510
(630) 840-3023

________________________________
