### ISSUE TITLE
meta4:: operation expires but no fallback to 2nd source

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1597]
Hi! I have new reports (reproductible with 20220106-30c089925 but the reports comes from 5.3.3)
where it seems the first source timeouts but no fallback to second one is followed. a few dump logs can be found here: https://asevcenc.web.cern.ch/asevcenc/xrootd_expired_no_fallback/

**Comment by adriansev** [comment]
@simonmichal Hi!
well, i could not properly asses the difference between:
`Default value for the time after which an error is declared if it was impossible to get a response to a request.`
and
`Default value for the time after which a connection error is declared (and a recovery attempted) if there are unfulfilled requests and there is no socket activity or a registered wait timeout`
hence i choose the REQUESTTIMEOUT instead of STREAMTIMEOUT
My intent was: if the redirector(and server) cannot answer and allocate/initiate the request, then fail (there is no point to wait for an overloaded/unresponsive server), to be able to move to next replica.
So, what would be the best setting for my intent above? also, i would argue against non-recoverability: given that i (can) have multiple replica in a metafile, why should be unrecoverable? just fail on the particular request, move to next replica if any, then respect the -retry parameter if any .. 
Thanks a lot!

**Comment by simonmichal** [comment]
@adriansev : the `STREAMTIMEOUT` is definitely what you need, recall that metalinks are treated as virtual redirectors, this means that if there is an error recovery it would happen directly at the metalling level as we have this data already at hand. You might ask what does it even mean to do error recovery, well, it means to resend a request that failed (e.g. due to `STREAMTIMEOUT`) to a different server, in our case the next server in the metalink file (which is exactly what you want).
I do realise that the naming convention is, well let's say bit misleading, but unfortunately there's no way we can change it now.
For more detailed explanation on how the timeouts of XRootD client work please visit:
https://xrootd.slac.stanford.edu/doc/xrdcl-docs/www/xrdcldocs.html#x1-580004.3.6

> also, i would argue against non-recoverability: given that i (can) have multiple replica in a metafile, why should be 
> unrecoverable? just fail on the particular request, move to next replica if any, then respect the -retry parameter if any ..

The `REQUESTTIMEOUT` is non-recoverable by policy, the goal is to have an API that allows the user to tell here's an operation timeout if it elapses please do abort (it should have been probably called operation t/o but the times when this has been decided predates me ;-)

**Comment by adriansev** [comment]
@simonmichal thanks a lot for info!!! then i will change the settings :) thanks a lot!
