### ISSUE TITLE
Functionality for HTTPS-TPC (based on ofs.tpc directives)

### ISSUE THREAD

**Issue by snafus** [xrootd/xrootd#1601]
Hi, 
  TPC transfers via HTTPS miss some of the functionality provided by the parameters available in the ofs.tpc directive. 
I'd like to ask if some of these could be considered to be added back into http transfers (perhaps just for TPC, but whatever would make most sense). 
I've added a (non-exhaustive) list below with some brief motivation;

1) Documentation: It's not clear to me if some or non of the ofs.tpc directives would apply to http-tpc transfers; a bit of clarification here would be great. 

2) autorm  :  The ability for the site to remove files that it knows are corrupt / failed is quite important; else it relies of things like FTS to manage cleanup, which may not work in all situations.

3) streams ; can the server specify already how many streams for a connection via HTTP?

4) xfr  max:  There was some discussion in the mailing list regarding this parameter (and motivates this posting). I believe it would be good for a site to be able to set some limit itself on the number of connections per-host. 

5)cksum ; I believe this parameter is respected in http-tpc transfers; is that true ?

6) Anything else? I'm not sure if there's any other functionality that could be added to this list? 

Thanks a lot in advance for considering some / all of  these.
James

**Comment by wyang007** [comment]
Comment on 1 and 5.
1) In addition to those in DOMA Twiki pages, I started a new doc site that to collect info with regards to large complex setup like this: you can find it at https://xrootd-howto.readthedocs.io. This is not a replacement of what you requested here: we need detail of the HTTP-TPC reference doc in https://www.slac.stanford.edu/docs.html
5) yes.

**Comment by bbockelm** [comment]
Since Wei left comments about 1 and 5, here's some thoughts on the others:
- 2: Not obvious how to bootstrap autorm-type concepts onto the HTTP protocol  If there is some part of HTTP that has similar ideas, we can certainly look at implementing it... but would be slightly reluctant to invent something new.
- 3: Just checked the code.  Number of streams has a sanity limit (can't go over 100 / transfer) but otherwise is based on the client request.
- 4: This was recently added to the throttling plugin.  I think the filesystem level is an appropriate place to put limits given that the storage resources are shared between HTTP and XRootD.

**Comment by afortiorama** [comment]
Hi Brian,

> 4: This was recently added to the throttling plugin. I think the filesystem level is an appropriate place to put limits given that the storage resources are shared between HTTP and XRootD.

A transfer protocol should have the option to limit the number of connections to the server that it serves the data from. I think limiting the file system assumes the file system isn't supporting other applications.

**Comment by abh3** [comment]
Frankly, varioous options introduce their own peculiar side effects that 
may make the system annoying enough that people simply consider it broken 
and move on. In this particular case the simplest solution is to limit the 
number of TPC requests that can happen at the same time. We did that right 
off the bat for xroot TPC and that worked really well. I am suprised that 
no such limit was envisioned for the http side. Saying they share the same 
storage is, in my opinion, architecturally misguided and very much 
complicates the whole storage backend when a simple solution exists.

Andy

**Comment by bbockelm** [comment]
> A transfer protocol should have the option to limit the number of connections to the server that it serves the data from. I think limiting the file system assumes the file system isn't supporting other applications.

This isn't limiting the filesystem but rather the filesystem plugin for XRootD.

Why is it obvious there's a different set of limits when doing this via the XRootD protocol versus HTTP and that these should be handled independently?

That is, let's say the server can support 100 concurrent file transfers at a time. What's the value we should have for the xrootd and HTTP?  I would claim it's better to just say "transfer up to 100 files at a time, regardless of how they came in the door".

**Comment by afortiorama** [comment]
Hi Brian, 

I would agree if RAL with the xrootd plugin was the only use case. The problem with limiting the transfers at the source is that we have several independent sources. Even counting only FTS we have one per experiment in WLCG and outside. And in some cases the gateways might also be used for internal access from the WNs.

**Comment by abh3** [comment]
Where do we really stand on this at this point?

**Comment by bbockelm** [comment]
Hi @abh3 -

I still find that connection limits alone are quite crude; typically, they start simple and quickly need additional features to make them useful.  Given we already have a mechanism - albeit in a different layer - I'd rather spend the (quite limited) effort available to make the existing mechanism better as opposed to creating a new one with overlap.

Given the discussion's died down a bit here and there are no immediate development items, I'd suggest we can close out the ticket.

Brian

**Comment by abh3** [comment]
I certainly can close this out but I really want to point out this is not a "connection" limit here. It's really what I would call a job limit. Each copy is a job and it uses resources across many domains (i.e. disk, network, memory, etc). So, what we are limiting is the number of these can run at the same time which is quite reasonable and is quite similar to what batch systems do. If we were just talking about one resource utilization then I would agree with you. But this is not the case here and trying to come up with a limit across all of these domains is not really practical. That's why a copy limit winds up being a reasonable  solution.
