### ISSUE TITLE
XrdSciTokens: `storage.create` and `storage.modify` for WLCG JWTs not correctly handled

### ISSUE THREAD

**Issue by olifre** [xrootd/xrootd#1655]
WLCG JWTs specify `storage.create` and `storage.modify` claims, which are currently both interpreted as the same set of "write permissions" in the existing code:
https://github.com/xrootd/xrootd/blob/5babd8c81c6ec201a265cb8f1d66064d2128dd68/src/XrdSciTokens/XrdSciTokensAccess.cc#L705-L713
This relies on the translation done here:
https://github.com/scitokens/scitokens-cpp/blob/3b36ea8c38539b1ed8dcfcf63494829852034b93/src/scitokens_internal.cpp#L611-L616

This violates the WLCG JWT specification, which differentiates between `create` (which must not allow to replace, delete or overwrite data) and `modify` (which is a superset allowing that). Renaming a file (without overwriting an existing one) is allowed by `storage.create`. The driving use case is stage-out of data from jobs on a worker node (which should only have `storage.create` but not `storage.modify`). 

This currently breaks JWT Compliance tests as outlined in:
https://github.com/indigo-iam/wlcg-jwt-compliance-tests/issues/34#issuecomment-1069437945
(i.e. the test `storage.create does not allow overwriting files` fails). 

@bbockelm already mentioned this requirement in the commit message here:
https://github.com/xrootd/xrootd-scitokens/commit/e3fe21991058dc74e2922f3f48919db8515a494e

I'm not sure about the best way to implement this without breaking the use case for SciTokens— while `scitokens-cpp` exposes `create`, `modify` and `write`, in case the token was a SciToken and not a WLCG token, I believe only `write` will arrive in the ACL list, while for a WLCG token, both will arrive. So a simple change of the `if` / `else` ladder is not sufficient, and I wonder whether a new config parameter to decide whether the SciToken interpretation or the WLCG interpretation should be used is needed — or whether there is a better way. 

@bbockelm Any proposal (or maybe even solution / code) already in mind?

**Comment by bbockelm** [comment]
@olifre - looked a bit at this this morning.  A WLCG token will additionally provide explicit create / modify authorization.  So, we should be able to implement logic around the lines of:

1.  When examining authorizations in the loop, add the appropriate permissions for create & modify.
2.  If write is encountered, note this but do not generate new permissions for that.
3.  Once the loop has completed, if we saw only write but neither create nor modify then we have encountered a SciToken and add back in all write permissions.

That should handle the WLCG case correctly and make the compliance tests happy.  Right?

Brian

**Comment by olifre** [comment]
@bbockelm I have the code ready (it was a bit more fiddling than expected to ensure the check is done by path, but I succeeded) and could open a PR, but there is a problem:

- `AOP_Create` translates into `open()` with `create`, as documented and POSIXly expected. However, that does not allow us to express "upload without replace, delete or overwrite", unless I am missing something, since `AOP_Create` is needed to create and at the same time allows to create and overwrite. 
- The same seems true for renaming: While there are `AOP_Rename` and `AOP_Insert`, there is no match for "allow to rename, unless the target already exists", correct? 

Do you have (another) good idea on how to express the WLCG JWT requirement to express `create` (as in "upload to non-existent file", "rename to non-existent target")?

**Comment by abh3** [comment]
You may be able to compose these to get the desired result or at least close to it. For instance, create is really a composition of insert + read + write. Upload without delete/replace means you do not have delete privileges. Unfortunately, there is no distinction on overwrite. But the operation should fail anyway because the intention is to create the file but only if it does not exist and that is a file system operation not an authorization issue. The same is true for rename, the file system does not allow a rename to clobber an existing file and the client has to do than manually and have the correct privileges' to do so. So, I think the issue here is a bit of confusion of what should be expressed via authorization scheme and how the file system coposes those operations to effect the desired result. In general, file system operations are conservative and do not allow you to mistakenly delete files. To do so, you need to perform the steps in sequence and there the privileges you have will indicate whether you can actually perform those steps.

**Comment by olifre** [comment]
Thanks, that does indeed clarify things. It seems my mind was not yet fully wrapped around the different layers, but this makes a lot of sense (as expected :wink: ). 

So if I understand correctly, to do things in sequence via XrdHttp, we need some changes:
- `HTTP PUT` by definition means "replace the resource such that I can get it back with `GET`", which is also how it is implemented. 
- However, this currently translates into a single request (`open` with `kXR_mkpath | kXR_open_wrto | kXR_delete`), which basically is an "all-in-one" request to the file system. That's true to the definition of `PUT`, but does not allow granular application of privileges. 
- This should be separated into doing things step by step (check existence, if so, delete, then create, then write to the file) to allow granular privileges to be applied. 

That seems very reasonable, but requires more code changes than I expected (which is surely not a bad thing, doing things right often requires more changes than expected). However, it means that I (currently, and in the near future) lack the time to go through with it — if somebody else steps up earlier than I can come back to it, I can surely support (e.g. share the implementation of the part @bbockelm suggested which I have already finished, but which needs to be done in-sync with the other changes to really have an effect).

**Comment by bbockelm** [comment]
@olifre - coming back to this.

Can you please share your partial fix via a PR?  I'd like to see it go in simply because it iterates us toward a better implementation.

We've found there's a number of places where HTTP-style operations or WLCG token authorization maps poorly to POSIX.  Where we can, we aim for practical solutions.  I could see where we might need to do something that has a race condition (e.g., check for file existence then create a file) but is "mostly correct".

@abh3 - to some extent, the WLCG token authorizations are _more_ fine grained than what's in XRootD.  What are your thoughts on adding two new finer-grained authorization levels in XRootD?

**Comment by bbockelm** [comment]
Ok, I think I have an approach here.

- Introduce two now `Access_Operation` values, `AOP_Excl_Create` and `AOP_Excl_Insert`.
- If the user has authorization for the respective full-power operations (`AOP_Create` and `AOP_Insert`), then proceed as normal.
- Otherwise, refuse to overwrite data in `XrdOfsFile::open` and `XrdOfs::rename`.

Doing this in `XrdOfsFile::open` is easy given it already has the concept of `O_EXCL`.  I _think_ we can handle `XrdOfs::rename` by internally creating a file with `O_EXCL`; if the thread successfully creates the file, then it is permitted to rename.

With this, all existing authorizations happen as normal (providing backward compatibility with existing operations) -- but any plugin aware of the newly-introduced operation can give a user additional authorization that wasn't there before.

**Comment by olifre** [comment]
@bbockelm Sure, I've pushed my work here for now:
https://github.com/olifre/xrootd/commit/ce973882ae887dd5a9b7fda5a01830624c47b258

Given you have an idea how to implement the more granular authorizations, it might be easiest if you pull this change and implement these changes in subsequent commits, so a full PR (which then uses the new `AOP` values) could go in — this would avoid having an intermediate state which has somewhat changed (but still not correct) permissions. 
What do you think?

**Comment by bbockelm** [comment]
@olifre - I rebased your commit to my branch and sent in a new PR.

Oddly enough, I don't have a great test bench for the `storage.modify` scopes; instead, I mostly tested the approach with macaroons (as those are easier to do with a single host).  Everything looked good to me when running through the quite similar macaroon code paths; I would appreciate it if you could give it a whirl!

**Comment by olifre** [comment]
@bbockelm Many thanks, that was fast!
I rebuilt out test instance from your PR. Indeed, I can confirm that an upload with `storage.create` is now prevented if it would clobber an existing file. It also does not allow clobbering a file by renaming (`MOVE`ing to an already existing file. So I think the major part is done :+1: . 

I think my tests covered everything the WLCG JWT acceptance tests cover (I replicated things with `curl` manually). However, I found one detail of the WLCG JWT specification which is not honoured yet (the acceptance tests do not seem to test it) — the spec says:`
> note the server implementation MUST NOT automatically create directories for a client

However, this currently happens (both with `create` or `modify`) when using `PUT`. Arguably, this is not so much an authorization thing, since of course `create` and `modify` should to create directories, but the spec seems to ask for `PUT`, `MOVE` and other operations not creating directories automatically.

**Comment by abh3** [comment]
@bbockelm I can't say I am thrilled on making the authorization any more complicated than it already is. In practice, people are already confused with all the various levels of authorization. Adding two ore simply is not going to fly all that well for the regular admin folks. Plus, we have been trying very hard to keep dCache and xrootd semantically consistent. This change would undo that and I don't think the dCache folks would be particularly happy introducing these changes as they seem to have very limited benefit (more like authorization gone berserk). However, I am always capable of being convinced otherwise.

As for automatically creating directories, the default xrootd actions is to create such directories for mkdir, open, and even rename. This has been historical and cannot be changed, at least on the xroot side, since people depend on this action. I suppose you can change it on the http side but be aware that you may get howls of defiance and spec be damned as people want paths to be automatically created. So, please don't blindly follow the spec without considering what the practical side effects will be. 

As for checking existence using open+EXCL that uis a bad idea as you may leave empty files lying about. Better to use stat().

**Comment by olifre** [comment]
> As for automatically creating directories, the default xrootd actions is to create such directories for mkdir, open, and even rename. This has been historical and cannot be changed, at least on the xroot side, since people depend on this action.

I'm with you on that — I'm also not sure how "hard" the statement in the spec is meant. Since it's not tested in the acceptance tests, my feeling would also be to just ignore it until somebody comes by and makes a strong point out of that. 

The mapping of scopes to activities in dCache is implemented here:
https://github.com/dCache/dcache/blob/master/modules/gplazma2-scitoken/src/main/java/org/dcache/gplazma/scitoken/WlcgProfileScope.java
Indeed, there does not seem to be an extension of the authorization model to achieve the desired effect.

**Comment by bbockelm** [comment]
Yeah, I don't want to touch the directory creation stuff right now.  We can iterate on it later if it becomes critical -- and, at most, I'd want to work on the HTTP side and not the xrootd side.

dCache already does the authorization "correctly" (i.e., dCache's behavior should match this PR) because this is the same model Macaroons uses.  StoRM handles this correctly as well.
