### ISSUE TITLE
Forwarding X509_Proxy for data access authentication

### ISSUE THREAD

**Issue by HerrHorizontal** [xrootd/xrootd#1693]
Hi, I wonder if there is an intended way of forwarding X509_Proxies by the XRootD ProxyFileCache, when reading data, so that specific users can only access data they allowed to, based on their credentials. The workaround we have found is to deposit a robot certificate on the machine working as a ProxyFileCache, which is then used to authenticate against the data server. This however would allow users to access data through the proxy, which should in principle not have access to. It would be more reasonable, if there was a way which allows to forward the X509_proxy used to authenticate against the ProxyFileCache to the data server, so every user data access is authenticated by the user's certificate.

**Comment by abh3** [comment]
There is no way to forward user x509 proxies via the Xcache. However, you can still provide access control. Simply setup authorization within Xcache like you would do in a standard data server. This works because Xcache does authenticate clients based on the x509 cert, if so enabled. The client's identity can then be used for authorization purposes. That way, unauthorized users will not be able to access prohibited data even though Xcache itself can.

**Comment by abh3** [comment]
I am closing this discussion. Note that we will have a similar problem with tokens that will be even harder to resolve.
