### ISSUE TITLE
no OpenFlags.APPEND

### ISSUE THREAD

**Issue by ScottDemarest** [xrootd/xrootd#1731]
There appears to be no OpenFlags.APPEND and it seems that it was removed. The documentation still lists APPEND as a valid flag. Can it be brought back?

**Comment by simonmichal** [comment]
@ScottDemarest : we have removed the `append` flag in XRootD5 from the client because we actually never supported this functionality properly. From what I see it was also never really supported in the bindings, the `currentOffset`:

https://github.com/xrootd/xrootd/blob/dfa0586ae4ac75b6a61345783eb95b7b1e6a1b38/bindings/python/src/PyXRootDFile.hh#L67

is being used only for the `readline` functionality.

Why do you need the open flag? Is that you used to have it and now you are getting a build error (in this case I would ask you just to remove the flag), or do you need this functionality implemented?

**Comment by ScottDemarest** [comment]
I am working on an fsspec implementation for xrootd and append functionality would have been convenient. I have worked around it though and do not need anything more. I only asked because it is listed in the docs at this link https://xrootd.slac.stanford.edu/doc/python/xrootd-python/modules/client/flags.html

**Comment by abh3** [comment]
OK, I am closing this ticket. Indeed, the append flag was added as a place holder but the feature was never implemented. We have removed that flag from the client-side include files to avoid this misunderstanding.
