### ISSUE TITLE
Adding DN information to new connections

### ISSUE THREAD

**Issue by PerilousApricot** [xrootd/xrootd#1738]
At our site, we occasionally get abusive users who will open thousands of concurrent connections and degrade the service.

previously, under xrootd-lcmaps it was possible to increase the logging to get the user's DN, in order to advise and/or ban the user. However, it appears that in 5.4.X, the inbuilt xrootd authentication does not output the subject of connections, (just the remote username/hostname). Would it be possible to add the subject to the connection log?

thanks,
Andrew (USCMS)

**Comment by abh3** [comment]
I assume that the line in the log that says "<user> logged in as <target name>" where <target name> is what the security stack decided was the dn (usually the hash of actual dn) is insufficient.

It's possible but we would need to add that feature and it's not even clear where to put it in as the DN is not readily available outside of the particular security stack being used. It would need to be an option as the default EU GDPR does not allow displaying such information without additional privacy protections that we aren't able to implement. Finally, I assume you only care about x509, right?

**Comment by PerilousApricot** [comment]
I guess initially x509 is what we're looking for, but I presume that as CMS moves towards tokens, getting the token subject would also be good. Thanks!

**Comment by bbockelm** [comment]
> It's possible but we would need to add that feature and it's not even clear where to put it in as the DN is not readily available outside of the particular security stack being used

Why not have a trace level that dumps the contents of the `XrdSecEntity` at the beginning of the security session?  Looking quickly at the GSI plugin, it seems that you can ask it to drop the DN into the `moninfo` field.

This would also cover the other security plugins as well.

> default EU GDPR does not allow displaying such information without additional privacy protections that we aren't able to implement

I'm not entirely sure this is _entirely_ true - GDPR is more of a framework on what you need to do manage PII rather than a set of yes/no.  However, I can see several reasons why this would be off by default in many setups (some sites will simply object to the volume of data!).

 Note this may help with various site traceability requirements as well.

**Comment by PerilousApricot** [comment]
HI>

On Mon, Jul 18, 2022 at 8:18 PM Brian P Bockelman
***@***.***> wrote:
>
> It's possible but we would need to add that feature and it's not even clear where to put it in as the DN is not readily available outside of the particular security stack being used
>
> Why not have a trace level that dumps the contents of the XrdSecEntity at the beginning of the security session? Looking quickly at the GSI plugin, it seems that you can ask it to drop the DN into the moninfo field.
<snip>

That, *along with the TID/PID* would be nice, Especially logging for
why the credential was approved/rejected.

Thanks!
Andrew

**Comment by bbockelm** [comment]
> What is wanted here is the actual DN string which is not an official part of the SecEntity structure

But the GSI plugin can be instructed to either put the DN into the user structure or the monitoring info (personally, I'd do that latter!).  So, if XRootD logged the SecEntity, Andrew could do either.

> look at SciTokens where there really is no DN equivalent

The token subject is quite similar to the DN (and also located in the SecEntity).  The difference is the contents of the string is often privacy-preserving (having no part you can type into Google and have a good guess as to the human's name); another difference is that a single human being can have a different subject for each unique user (I might be "user1234" in ATLAS and "user5678" in CMS).

(I think Andrew Melo could even get away without the DN and just use the hash if all he wants to correlate heavy levels of usage and be able to ban users.)

**Comment by PerilousApricot** [comment]
> (I think Andrew Melo could even get away without the DN and just use the hash if all he wants to correlate heavy levels of usage and be able to ban users.)

I'd be happy to ban an opaque hash then wait for an email to come from a user complaining. If there was a way to tie `some blob` to an email address, it'd be great

**Comment by PerilousApricot** [comment]
Well .. lemme rephrase: The minimal thing would be to get an opaque hash I could ban, but just in terms of someone running a service, having no way to know what person is connecting makes things hard.

**Comment by abh3** [comment]
Yes, that was what I though you were after in the first place. So, indeed, SciTokens will be a challenge in this regard.

**Comment by PerilousApricot** [comment]
Well, it's somewhat the case that `xrootd.trace auth` spits it out. This is what I get back from a GSI connection:

```
220718 21:02:37 68759 sysThrottleManager: Current IO counter is 0; total IO wait time is 601ms.
220718 21:02:37 69034 root.231196:70@cmsrucioprod1-la5qxltcbmcu-node-3.ipv6.cern.ch Xrootd_Protocol: more auth requested; sz=3353
root.231196:70@cmsrucioprod1-la5qxltcbmcu-node-3.ipv6.cern.ch Protocol 'gsi'
root.231196:70@cmsrucioprod1-la5qxltcbmcu-node-3.ipv6.cern.ch Name 'cmsprod'
root.231196:70@cmsrucioprod1-la5qxltcbmcu-node-3.ipv6.cern.ch Host 'cmsrucioprod1-la5qxltcbmcu-node-3.ipv6.cern.ch'
root.231196:70@cmsrucioprod1-la5qxltcbmcu-node-3.ipv6.cern.ch Vorg 'cms cms'
root.231196:70@cmsrucioprod1-la5qxltcbmcu-node-3.ipv6.cern.ch Role 'production NULL'
root.231196:70@cmsrucioprod1-la5qxltcbmcu-node-3.ipv6.cern.ch Grps '/cms /cms'
root.231196:70@cmsrucioprod1-la5qxltcbmcu-node-3.ipv6.cern.ch Caps ''
root.231196:70@cmsrucioprod1-la5qxltcbmcu-node-3.ipv6.cern.ch Pidn 'root.231196:70@cmsrucioprod1-la5qxltcbmcu-node-3.ipv6.cern.ch'
root.231196:70@cmsrucioprod1-la5qxltcbmcu-node-3.ipv6.cern.ch Crlen 0
root.231196:70@cmsrucioprod1-la5qxltcbmcu-node-3.ipv6.cern.ch ueid  172
root.231196:70@cmsrucioprod1-la5qxltcbmcu-node-3.ipv6.cern.ch uid   0
root.231196:70@cmsrucioprod1-la5qxltcbmcu-node-3.ipv6.cern.ch gid   0
```

... first off, none of this is the DN, so it's not at all what I could use to find a user, much less to ban them.

Secondly (and more minorly), this apparently comes through some other subsystem with a different logging facility, so the latter logs don't have the threadID with them letting you disambugate who is reading what file.

Thanks!

**Comment by abh3** [comment]
I am not sure what you mean by thread ID here as threads get reassigned as needed and are not meaningful over the life of a session. The more meaningful is root.231196:70@cmsrucioprod1-la5qxltcbmcu-node-3.ipv6.cern.ch where you see the host name and 231196:70 is the process ID of the client running on that host. That won't change during the whole session. I agree that you really don't get enough info here to ID the user (well there was hope), especially since lcmaps (or whatever mapping being used) mapped the user to cmsprod (which makes sense). But who is that? Well, who knows. Maybe I can conjure something up but it won't get in until the next release or one after that.

**Comment by PerilousApricot** [comment]
Ah, I thought that the `69034` in the line above was common throughout a user's session, and I could use that to divine what files the user is opening.

**Comment by abh3** [comment]
That's the thread ID. However, you can use the value of the SecEntity ueid member as this will be unique for the session.

**Comment by matyasselmeci** [comment]
I'm missing something. Andrew, you're not using lcmaps right now, right? How come https://github.com/xrootd/xrootd/blob/master/src/XrdSecgsi/XrdSecgsiAuthzFunDN.cc#L155 isn't printing the DN in the logs?

**Comment by PerilousApricot** [comment]
You're right that I'm not using LCMAPS. As to why it's not writing that
line, your guess is as good as mine!--
It's dark in this basement.

**Comment by abh3** [comment]
The reason it's not printing it is because it's a debug statement and "debug" mode is normally disabled as production use is not debugging. This is on the list of things to do.

**Comment by bbockelm** [comment]
So, to summarize the ticket so far:
- We can enable tracing for the XRootD authorization object (`xrootd.trace auth`).  This is currently missing the information @PerilousApricot is looking for (namely, the DN).
- It appears that the DN is put into the authorization object as monitoring information if the `-moninfo` flag is given to the `sec.protocol gsi` configuration.
- Unfortunately, the monitoring info was omitted from the trace log.  Here's a simple PR to do that:  https://github.com/xrootd/xrootd/pull/1819

With the above PR, the `xrootd.trace auth` level includes the following:

```
http Protocol 'gsi'
http Name 'bbockelm'
http Host '[2600:900:6:1301:5054:ff:fe0b:9cba]'
http Vorg 'cms cms cms'
http Role 'NULL NULL NULL'
http Grps '/cms /cms/integration /cms/uscms'
http Caps ''
http Pidn ''
http Mon  '/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=bbockelm/CN=659869/CN=Brian Paul Bockelman'
http Crlen 0
http ueid  0
http uid   0
http gid   0
http Attr gridmap.name = '1'
http Attr  = ''
```

Is that sufficient?

I do really dislike the formatting of the information (split across multiple lines, makes it difficult to grep).  Any reason we shouldn't also touch up the formatting?

PS - I agree with @abh3 above -- we likely really want to do a follow-up for request logging since, for tokens, requests are separately authorized from sessions.

**Comment by abh3** [comment]
Well, yes, that was the point and the plan was to make something linke 
this. One worry was that moninfo is not specified so it could be anything 
including binary information and printing it may cause problems. That's 
why it wasn't included in the first place. Given that the DN is specific 
to x509 we were leaning to add an option to gsi to simply print it.

Andy

**Comment by abh3** [comment]
OK, in R5.6 you will get a gsi option "-showdn' that will display the DN along with the entity name. This is displayed only when the entity name is not the subject DN. The documentation is:
https://xrootd.slac.stanford.edu/doc/dev56/sec_config.htm#_Toc119617433

This avoids all the issues associated with assuming the moninfo field has correct information and does not add additional unneeded attributes to the entity object.
