### ISSUE TITLE
XrdTpc pass transfer size info to XrdOfs layer

### ISSUE THREAD

**Issue by esindril** [xrootd/xrootd#1754]
Hi, 

The current XrdTpc implementation does not pass any information to the XrdOfs about the size of the file that is about to be transferred (written). It would be nice to pass this info just like xrdcp is doing, for example, by appending the `&oss.asize=<value>` opaque info in the open request done at the OFS layer. This can then be used by the OFS layer implementation to pre-allocate/reserve the necessary space so that a transfer does not fail half-way through (rare) and more importantly to avoid fragmentation at the file system level. You can find more details about this issue in this discussion thread:
`https://eos-community.web.cern.ch/t/difference-between-accounting-report-and-space-ls-for-default-space/767/12`

Thanks,
Elvin

**Comment by ccaffy** [comment]
Hi @abh3 and @bbockelm ,

I have an idea on how to implement it and I would like your feedback before proceeding ;)

This feature is needed for the HTTP TPC Pull side. If possible, I would like this to be included in the new XRootD release that will be done end of this week :)

I looked at the code and the problem is that before opening the file on the destination machine (the one that pulls), we do not have the size of the file from the source server.

I was thinking that we can do a HEAD query against the Source machine before opening the file locally. Once we get the "Content-Length" value from this query, we can then append to the file-to-open opaque infos the file size with `oss.asize=<value>`.

This code will be located after this line: https://github.com/xrootd/xrootd/blob/master/src/XrdTpc/XrdTpcTPC.cc#L940,
something like `uint64_t contentLength = GetContentLength();` and pass this contentLength value to the OpenWaitStall() method.

What do you think ?

Thanks in advance !
Cedric

**Comment by ccaffy** [comment]
I did a small proof of concept by reusing the `TpcHandler::DetermineXferSize(...)` and it works nicely :)

**Comment by abh3** [comment]
Hi Cedric,

Brilliant idea! Please go ahead.

Andy

**Comment by ccaffy** [comment]
The pull request is here: https://github.com/xrootd/xrootd/pull/1801

**Comment by ccaffy** [comment]
PR merged to master.
