### ISSUE TITLE
Default Chunk Size

### ISSUE THREAD

**Issue by alrossi** [xrootd/xrootd#1756]
I imagine you are aware that the documentation reports 

```
4.2.6 XRD CPCHUNKSIZE
Size of a single data chunk handled by xrdcp / XrdCl::CopyProcess.
Default: 16KiB
```

but the code (XrdClConstants.hh, line ), has

```
  const int DefaultCPChunkSize             = 8388608;
```

and this is what I see being used when I run xrdcp with `d -3`.

I do have a question, though.   Why 8 MiB?  Can you provide some clarification for this choice?

Thanks, Al

**Comment by xrootd-dev** [comment]
Correct, clearly the documentation is incorrect. That will be corrected. 
As for why 8 Mib? Well, there is no particular reason other than making it 
big enough but not too big to retransmit too much data when you have to 
recover a write or read. The original client used 4 Mib but that seemed 
too small so it was doubled as a stating point. Mind you that the server 
is free to manage the read or write  with whatever buffer size it wants to 
use so just because the chunk size is 8 Mib doesn't mean the server needs 
to use a matching buffer. Indeed, native xrootd uses a 2 Mib buffer.

Comparing other transfer agents we can find that they arguably usee an 
outlandishly large transfer chunk size (i.e. 32K Mib or even 64K Mib) -- 
just look at Amazon or Google.

Andy

**Comment by simonmichal** [comment]
@alrossi : I just noticed your question about the choice of **8MiB** for the default chunk size, AFAIR we run some tests over WAN between CERN and SLAC a while ago with @wyang007 and 8MiB gave best performance.
