### ISSUE TITLE
internal checksum and extended attributes

### ISSUE THREAD

**Issue by wyang007** [xrootd/xrootd#1773]
when using internal checksum on a storage that doesn't support extended attributes, clients get "Operation not supported" rather than a checksum

**Comment by abh3** [comment]
What do you propose as an alternative? This has been an ongoing battle for some time. Practically all widely used filesystems support extended attributes and all of them also support turning that feature off. The documentation can likely become more clear that if you choose to turn off the feature (or in the rare case it's not supported) then checksums are not supported as well. Frankly, I don't see any up side to spending a huge amount of effort in supporting checksums in the absence of extended attributes. Do you?

**Comment by wyang007** [comment]
why not just return the checksum and ignore the extended attribute ?  for now we use external script to work around this issue.

**Comment by xrootd-dev** [comment]
The problem here is that unbeknowst to the site admin we would be eating 
up an enornous amount of resource to recompute the checksum every time it 
is requested. There is already a ticket about that with Brian and I think 
he decided it was a loosing proposition. Yes, he complained about specific 
code in the server that prohibits constant recomputation of checksums. 
In the end, the site admins really need to know that they have to enable 
extended attributes to get checksums as it isn't all that hard and is 
broadly supported
