### ISSUE TITLE
problem with xrdfs query prepare call

### ISSUE THREAD

**Issue by maksiks** [xrootd/xrootd#1786]
Hi, 

I am having problems with executing this call on the redirector.
On any door this works fine, when I try it on redirector I get the error (and from I can tell this never goes to any door):

220922 13:36:01 14054 XrootdXeq: maksiks.28781:37@t2srv0017.cmsaf.mit.edu pub IPv4 login as maxi
220922 13:36:01 14054 maksiks.28781:37@t2srv0017.cmsaf.mit.edu Xrootd_Protocol: 0100 req=query dlen=102
220922 13:36:01 14054 maksiks.28781:37@t2srv0017.cmsaf.mit.edu Xrootd_Response: 0100 sending err 3000: Prepare requestid owned by an unknown server

Our redirector does not have direct access to the underlying FS, but commands like xrdfs ls work with no problems. Please help me to understand what needs to be done here.

Thank you, --Max

**Comment by abh3** [comment]
Hi Max,

What is it that you are actually trying to do with the query prepare call. 
Is it related to a previous prepare that is long running? In general, 
query prepares only work for tape staging as the prepare to prime the 
cache completes faster than you can query it.

Andy

**Comment by abh3** [comment]
I took a deeper dive into this and a properly constructed prepare request ID, a server (data or redirector) receiving a query using that id will redirect the client to the server that actually created that request id.  If a receiving sever created the id it will handle it. So, we need to find out what is wrong with that request id. It should only contains ASCII text so please either post one exhibiting this behavior or send it to me via email.

**Comment by maksiks** [comment]
Hi, here is the command that I try to execute from some server:
xrdfs tapexrd.cmsaf.mit.edu:1094 query prepare 111 /store/data/Run2022A/ZeroBias9/RAW/v1/000/352/322/00000/6a445e3f-4677-4af4-81dd-5f6809e982db.root 
[ERROR] Server responded with an error: [3000] Prepare requestid owned by an unknown server

111 is just some random number that I try to supply as a request id, I do not know how this id should look like. If I skip that field with id the outcome of the command will be the same. tapexrd is our redirector that does not have access to underlying FS. If I issue same command using any door the call goes through.
--Max

**Comment by maksiks** [comment]
Hi, any update on this issue?
Thank you, --Max

**Comment by abh3** [comment]
OK, the problem here is tat when yo issue a prepare the server hands back a prepare request ID.That request ID must be used for any future query as it encodes the actual request and the server can then use it to find the actual request. Handing a random number will never work. When you issued the prepare using xrdfs the request ID should have been displayed.

**Comment by maksiks** [comment]
That you for the explanation, but it got me lost. What should the command look like when I issue it? Above I pasted how it should look like in my head, from your reply I understand that I am doing something wrong, so what should it be?

**Comment by abh3** [comment]
Sorry for the late reply but I was away. When you issue a prepare for a resource that will take some time to prepare (e.g. get a file from a tape) the response will include a request handle. You use that request handle in a subsequent query to find out the request's status. For quick requests (e.g. prime a redirector's location cache) there is no point in the query because the request would have been processed by the time you get a response. So, the key here is that you need to use the request handle sent in he response (xrdfs or xprep should display it) in the subsequent query.

**Comment by abh3** [comment]
I hope the last comment clarified the situation. The query request simply needs to be issued with the server supplied request handle (.k.a ID). Then this should work if the request is still active.
