### ISSUE TITLE
Transfers failing. What is the difference between xrd.wantprot=gsi,unix and xrd.gsiusrpxy=/tmp/x509up_u1000

### ISSUE THREAD

**Issue by IgorPelevanyuk** [xrootd/xrootd#1813]
Hello dear colleagues, I would like to ask for your expert help.

I have faced with very strange issue during xrdcp operations. Depending on parameters transfers either finish successfully or blocked and finished with error after timeout. The only difference is parameters of transfers. 
This works:
xrdcp root://eos.server:1094///eos/project/bigfile.dat?xrd.wantprot=gsi,unix .
It starts with a speed of 100 MB/s, then it hangs for a little bit and after some time continues to download with final speed of 38 MB/s

This  hangs until timeout:
xrdcp root://eos.server:1094///eos/project/bigfile.dat?xrd.gsiusrpxy=/tmp/x509up_u1000
It also starts with a speed of 100MB/s but hangs after some time and fails with timeout. 

So, I wonder what is the difference from xrootd point of view between these commands. Both of them use proxy. One take it from ENV, the other takes path from parameter. I think that may be the key for fixing this problem.

If necessary I may include debug information.

**Comment by abh3** [comment]
The first xrdcp simply asks to use gsi and if that fails to use unix authentication. The second merely says that if gsi is being used, find the cert at the specified place (which should be the default anyway assuming your uid is 1000). Either way, a hang should not happen. So, please rerun the second case with envar setting XRD_LOGLEVEL=Debug to see what the issue is.

**Comment by IgorPelevanyuk** [comment]
Dear Andrew, 

I have performed download again and put all logs in https://gist.github.com/IgorPelevanyuk/c0514fd89801a13e9a9fc7878e2ebb70

**Comment by IgorPelevanyuk** [comment]
I have shortened log, removed timestamps and log line type information, and formed diff:
https://www.diffchecker.com/zh4OXQxV

As far as I see there is not much difference

**Comment by smithdh** [comment]
Hi @IgorPelevanyuk. Thanks a lot for your report and debug logs. I think there's been progress in understanding the underlying issue and there are now a couple of PR which aim to solve the problem. (Those are PR #1824 & PR #1829). Those will go through some more internal discussion or review and then I hope we'll be able to get the problem fixed.

There was another issue reported which is likely the same - in that case against xrdcp 5.5.0, but I've looked at your logs and as far as I understand it is the same problem:

Two issues; the hang of the transfer and subsequently the expected recovery of the transfer. As you reported, having certain parameters appears to change whether the recovery happens or not (with eventual timeout in case of no recovery). This is not because to the what the parameter itself is supposed to do, but rather an indirect consequence of the handling of certain options inside the xrootd client library. (In this case when xrd.gsiusrpxy is present I believe the recovery doesn't happen; the option xrd.wantprot does not impact the recovery in this way).

**Comment by IgorPelevanyuk** [comment]
Dear David, 

Thank you for your reply! It's great releaf to hear that. 
BTW, the problem appeared also through the gfal2 use as in #1808. 

Thanks to you and the team!

**Comment by abh3** [comment]
This appears to be resolved. If not please reopen with appropriate comments.

**Comment by IgorPelevanyuk** [comment]
Thank you!

**Comment by IgorPelevanyuk** [comment]
May I just ask, what version of xrootd client I need in order to avoid bug? Because the last release 5.5.1 is dated by 19th October 2022.

**Comment by abh3** [comment]
The fixes will appear in 5.5.2-RC2 this week and the actual release is planned for
next week. These are he fixes that @smithdh referred to.
