### ISSUE TITLE
X509_USER_* environment variable handling

### ISSUE THREAD

**Issue by stlammel** [xrootd/xrootd#1831]
Dear xrootd team,
   i want to limit the xrootd client to only GSI authentication based on an x509 proxy file.
   So, i set XrdSecPROTOCOL to gsi, X509_USER_PROXY to the proxy file and
X509_USER_CERT and X509_USER_KEY to "none" (to avoid the client trying a grid-proxy-init
on the key/cert file in the default location.
   The result is an error:

Run: [ERROR] Server responded with an error: [3012] Too many attempts to gain dfs read access to the file (source)

   If i don't set X509_USER_CERT and X509_USER_KEY the client works (without trying a grid-proxy-init).
   Is this a bug? If not, how could i achieve the desired only GSI based on proxy file (without removing my key/cert file from ~/.globus)?
   Thanks,
          cheers,  Stephan

% xrdcp -V
v5.5.1

**Comment by abh3** [comment]
Do the standard proxy-init (e.g. voms-proxy-init) this will place your proxy cert in a well known place.. Before using the client set the envar XrdSecPROTOCOL to "gsi" (e.g. export XrdSecPROTOCOL=gsi). That's basically it.

**Comment by stlammel** [comment]
Hallo Andy,
   even if the proxy is in the standard /tmp/x509up_u* location and X509_USER_PROXY is not set, the xrootd clients fail if X509_USER_CERT and X509_USER_KEY are set to none with the exact same error. (But this would also not work for me as i need to use the proxy certificate from an non-standard location.)
   Thanks,
        cheers,  Stephan

**Comment by stlammel** [comment]
Thanks Andy. Yes, i understand but in case the proxy certificate is expired xrootd triggers a grid-proxy-init i want to avoid, thus me setting X509_USER_CERT and X509_USER_KEY to none.

The issue is the xrootd client failing with valid proxy in case X509_USER_CERT and X509_USER_KEY are set to none.
- Stephan

**Comment by xrootd-dev** [comment]
Hi Stephan,

The problem is that that is not how it works. By setting the 
X509_USER_CERT and X509_USER_KEY to anything but undefined causes the gsi 
code to interpret that as the cert/key that should be used and that 
obviously won't work. So, give this a try....

export XrdSecGSICREATEPROXY=0

and that should stop the creation of a proxy cert. It's not a documented 
feature so it might not work exactly the way I think it should.

Andy


On Tue, 22 Nov 2022, Stephan Lammel wrote:

> Thanks Andy. Yes, i understand but in case the proxy certificate is 
expired xrootd triggers a grid-proxy-init i want to avoid, thus me setting X509_USER_CERT and X509_USER_KEY to none.

**Comment by stlammel** [comment]
Perfect, that does the trick! Many Thanks Andy!
 - Stephan
