### ISSUE TITLE
python xrootd caches authentication

### ISSUE THREAD

**Issue by stlammel** [xrootd/xrootd#1838]
The python interface of xrootd seems to be caching x509 authentication information. If i set a different X509_USER_PROXY environment variable value, a new XRootD.client.File() does not use it but setting of the initial/first XRootD.client.File(). The documentation does not mention this and, at least for me, the behavior is unexpected.
How can i force the python client to re-read the environment setting or is this an oversight/can the behavior be changed?
How extensive is the caching? Are XrdSecPROTOCOL, XRD_NETWORKSTACK, and BEARER_TOKEN_FILE also being cached?
Thanks,
 - Stephan

xrootd-client version 5.5.1

**Comment by abh3** [comment]
I wouldn't call it caching. Many of these environment variables are per instance variables. That is, they are used to initialize the client shared libraries with default values. For the client itself, you can override the default by placing the wanted value on the URL when creating a new file object. This would be of the form 'XrCl.<name>=<value> where <name> is the mixed case variable name shown in https://xrootd.slac.stanford.edu/doc/man/xrdcp.1.html#ENVIRONMENT in parenthesis with a '-DI' or '-DS' prefix; the name follows this prefix. The <value> is the appropriate value. Be aware that this will not always be successful since the client reuses connections whenever possible. You can inhibit the reuse by adding a unique username in front of the host name in the URL (i.e. xroot://<user>@<host>/).

Now that will work for the variables listed in the documentation I pointed to above, as these are client variables. For plugins, each plugin has its own scheme on how to handle envars. For gsi. determining where the proxy certificate resides is done only once. For ztn (bearer token) this is looked up each time an authentication occurs.

For managing the authentication scheme (this is a client function) the specific protocols to use comes from the URL via xrd.wantprot=<protlist> or, when not present, XrdSecPROTOCOL is reread for each authentication. Once again, authentication occurs on a per connection basis so once established it stays that way.

Hope that helps you to do what you need to do.

**Comment by stlammel** [comment]
Hallo Andy,
   sorry for the late reply, it was a busy day.
   This is exactly what i wanted to understand, many thanks!
   (So, for the GSI proxy file switch, i changed things to a subprocess call of an xrdfs stat command. For an access check that's good enough and will do the trick.)
   Thanks,
          cheers,  Stephan
