### ISSUE TITLE
Validate() interface used in ZTN

### ISSUE THREAD

**Issue by apeters1971** [xrootd/xrootd#1895]
Hello all, 
I try to use ZTN for EOS tokens or even ALICE tokens (not SciTokens!), but I stumble on a design problem in the interfaces.

ZTN is hardcoded to the API of "XrdSciTokens/XrdSciTokensHelper.hh" e.g. it calls the Validate() function. While the Access() function can call the passthrough for another Acc library, there is no such thing for the Validate() function of tokens.

Should I add a configuration switch to disable this Validate() call, since I don't really care to check tokens during the connection phase, since I have to check it anyway for the call in the OFS. 

Or you have another proposal how to shuffle these interfaces?

Thanks, Andreas.

**Comment by abh3** [comment]
Hmmm, the ztn protocol was specific to SciTokens though I suppose it could handle other types of tokens. The Va;lidate() call is supposed to enforce the ztn requirement that the token is actually valid and issued by a known token issuer. So, before I go spouting what can be done here I suppose I really need to know in detail what kind of token you wish to process and how you would wish to process it. For Alice tokens there is no need for ztn since Alice has accepted that users will always present an Alice token. Other types of tokens have different presentation rules.

**Comment by apeters1971** [comment]
I have added a trivial pull request: https://github.com/xrootd/xrootd/pull/1910

Since one can chain Acc libraries for example for HTTP access, I want to pass a non-sci token over ZTN. Since the SciToken library cannot pass through the Validate() calls to the chained Acc library (since it is not part of that interface), for me it is enough just to disable the Validation in the handshake and then let SciToken pass through the Access requests to the chained Acc library.  To be concrete, CMS asked to be able to use ZTN with EOS tokens. Since this token can be used also on a per file basis, the Validate in the handshake does not buy much here and I would just disable it for EOS setups. For me that would be sufficient.

**Comment by amadio** [comment]
I guess this has been fixed by #1921, right?

**Comment by abh3** [comment]
Indeed pull 1921 addressed this.
