### ISSUE TITLE
Monitoring of sub-second time transfers

### ISSUE THREAD

**Issue by kazeborja** [xrootd/xrootd#1900]
Hi all,

Following a new XRootD monitoring implementation for OSG/WLCG it looks like the XRootD monitoring streams might be rounding the time of the transfer to 0 if the transfer finishes under 1 second.

Reading the documentation it's understood that resolution timing is in seconds, the question is:

Is it possible to configure the XRootD servers to provide a better resolution somehow, in case it's not, is there a possibility to have this improved?

Please let me know if further information is needed to understand the issue.

Thanks in advance.
Borja

**Comment by abh3** [comment]
I suppose the fastest bypass is to assume it's about a second if the value is 0. The second fastest solution is to simply round up to a second. Doing anything more is somewhat disruptive since collectors likely assume there are no fractional digits. Something to discuss in the upcoming XRootD workshop https://indico.cern.ch/event/875381/

**Comment by kazeborja** [comment]
Thanks for the prompt reply, I agree any possible change to the format might be disruptive, still good to know it'll be discussed.

Anything that's rounding can be a good workaround but won't provide 100% correct monitoring data, so it will probably come with other implications

**Comment by abh3** [comment]
OK, I think we decided that while a second resolution wasn't the best choice, changing it would be too disruptive. So, I am closing this as a "won't do".
