### ISSUE TITLE
xrdcp:  possibly suppress unnecessary warning concerning TLS

### ISSUE THREAD

**Issue by alrossi** [xrootd/xrootd#1927]
Hello,

when running `xrdcp` against our multiprotocol xroot door (i.e., that supports ZTN and GSI, in that order), the client will warn that ZTN is not supported if the door/server does not also enforce TLS.   For example, 1095 has TLS optional:

```
[arossi@fndcatemp1 ~]$ httokendecode 
/run/user/8773/bt_u8773 not found
[arossi@fndcatemp1 ~]$ voms-proxy-init
Your identity: /DC=org/DC=cilogon/C=US/O=Fermi National Accelerator Laboratory/OU=People/CN=Al Rossi/CN=UID:arossi
Creating proxy ................................. Done

Your proxy is valid until Wed Feb 22 20:05:51 2023
[arossi@fndcatemp1 ~]$ xrdcp5x data/data_1b xroot://fndcatemp2.fnal.gov:1095///pnfs/fs/usr/fermilab/users/arossi/any/data-`suffix`
security protocol 'ztn' disallowed for non-TLS connections.
[1B/1B][100%][==================================================][1B/s]  
[arossi@fndcatemp1 ~]$
```

Now, since the client was not given a token, but just a GSI credential, it seems superfluous to warn about TLS, given the client will not try ZTN anyway.

Would it be possible to reverse the internal checks in the client, such that it looks for the bearer token first?  That way, if it does not find the token, it just skips the protocol and moves on to GSI?

Of course, the ordering of the protocols by the server would also take care of this case (i.e., telling the client to try GSI first).   But it does seem to me that the client itself ought to check for the presence of a token first.

This is not urgent, just a suggestion.

Thanks, Al

**Comment by abh3** [comment]
The issue here is that the server wanted the client to try the protocols in "ztn gsi' and, yes, the message about ztn failure due to non-TLS is forcibly displayed. That may not be the best option but we are working on figuring out how to display auth failures only when the whole authentication stack fails. It's not an easy problem, You can avoid this problem by reversing the order (i.e., gsi then ztn). Then you won't get the ztn error message (gsi never prints out error messages - another problem altogether). So, yes, we know the problem but we have yet to come up with a satisfactory solution.

**Comment by alrossi** [comment]
This has been solved by not sending 'ztn' if client does not support TLS or have it turned on.
