### ISSUE TITLE
logging remote debugging session

### ISSUE THREAD

**Issue by ivukotic** [xrootd/xrootd#198]
There is an excessive logging of the remote debugging session with millions of messages like this:

150209 17:41:19 3628 ivukotic.3314:7@atlint04.slac.stanford.edu XrootdResponse: 0100 sending 121 data bytes; status=4000
150209 17:41:19 3628 ivukotic.3314:7@atlint04.slac.stanford.edu XrootdResponse: 0100 sending 121 data bytes; status=4000

(observed at CSCS - root://atlas01.lcg.cscs.ch:1094)

**Comment by abh3** [comment]
I agree it is excessive but that's what you get if you turn on full debugging. I always suggested not to do that because it severely impacts server performance. Apparently, few people heed that advice, The solution is to use minimal debugging and only if it is really needed. This has nothing to do with remote debugging and everything to do with a bad configuration.
