### ISSUE TITLE
SEGV when using proxy module PSS

### ISSUE THREAD

**Issue by apeters1971** [xrootd/xrootd#205]
I debugged with Kilian a 100% reproducable proxy server crash with XRootD V4.1 and master branch status of this morning. It is connected to POSC processing.

Disabling with "ofs.persist off" obviously cures the SEGV but probably just hides this bug
```
ofs.osslib <....>/libXrdPss.so
pss.origin =
all.export /xroot:/
ofs.persist off
```
```
(gdb) where
#0  XrdPssSys::Unlink (this=<optimized out>, path=0x2591800 "/xroot:/alice-disk-se.gridka.de:1094/13/38322/d0b4e2b4-bc36-11e4-a78b-fffdac6bba8c", Opts=0, envP=0x0) at /home/alixrd/xrootd-4.1.1/src/XrdPss/XrdPss.cc:1160
#1  0x00007f3e0e1a5f74 in XrdOfsPoscq::Del (this=0x258ea70, Lfn=0x2591800 "/xroot:/alice-disk-se.gridka.de:1094/13/38322/d0b4e2b4-bc36-11e4-a78b-fffdac6bba8c", Offset=64, Unlink=1)
    at /home/alixrd/xrootd-4.1.1/src/XrdOfs/XrdOfsPoscq.cc:141
#2  0x00007f3e0e19b251 in ~OpenHelper (this=0x7f3e0c5333d0, __in_chrg=<optimized out>) at /home/alixrd/xrootd-4.1.1/src/XrdOfs/XrdOfs.cc:435
#3  XrdOfsFile::open (this=<optimized out>, path=<optimized out>, open_mode=1049088, Mode=16820, client=<optimized out>,
    info=0x2591855 "&authz=-----BEGIN SEALED CIPHER-----\nYSrnbDuKU3YjDKj8-KqGCb8RwYVZzvvkTD46AwO4xQNK3ucywUOW5u+LXGX8EXG3AETTN4+ndwO2\nXq01+OSv1uwojdBJYZ59cnk3dBfKoMkrwXVKgZ9U6b8+QrA2MdGk2iuHTo2WMbxWAu4L54M8+9Mr\nAbM+5SJMn"...) at /home/alixrd/xrootd-4.1.1/src/XrdOfs/XrdOfs.cc:659
#4  0x00007f3e0e192339 in XrdXrootdProtocol::do_Open (this=0x2590e90) at /home/alixrd/xrootd-4.1.1/src/XrdXrootd/XrdXrootdXeq.cc:1260
#5  0x00007f3e0df12d99 in XrdLink::DoIt (this=0x25903c8) at /home/alixrd/xrootd-4.1.1/src/Xrd/XrdLink.cc:397
#6  0x00007f3e0df16393 in XrdScheduler::Run (this=0x610018) at /home/alixrd/xrootd-4.1.1/src/Xrd/XrdScheduler.cc:333
#7  0x00007f3e0df16589 in XrdStartWorking (carg=<optimized out>) at /home/alixrd/xrootd-4.1.1/src/Xrd/XrdScheduler.cc:85
#8  0x00007f3e0dedb6ff in XrdSysThread_Xeq (myargs=0x2575a30) at /home/alixrd/xrootd-4.1.1/src/XrdSys/XrdSysPthread.cc:86
#9  0x00007f3e0da99b50 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#10 0x00007f3e0ce3c70d in clone () from /lib/x86_64-linux-gnu/libc.so.6
#11 0x0000000000000000 in ?? ()
```

**Comment by ljanyst** [comment]
Yeah, I got this report via email this morning. Thanks for the debugging! @abh3 can you please have a look?

**Comment by abh3** [comment]
Indeed, there are two problems here: 1) the pss implementation does not test for a nil environment pointer, and 2) it does not disable posc. The SEGV was caused by the posc code feeding it a nil environment pointer. While that's legal it never happens in any other code path but the posc code path. That's OK, I will change the pss to allow for nil environment pointers to avoid future problems. That said, I will also force posc to be off when the proxy plugin is being used because posc processing in proxy mode is meaningless and causes understandable error messages to be issued; especially in forwarding proxies. Why? Because you can't posc in a proxy. However, it does reveal that we do not pass the posc option through the proxy unless it's explicitly requested via cgi information. Something to look at but the immediate fix is to keep it from crashing in the next release.
