### ISSUE TITLE
Impossible to pass CMake options when building only python extension

### ISSUE THREAD

**Issue by StefanBruens** [xrootd/xrootd#2062]
When building the python bindings/extension only using `python3 -mpip wheel` from inside `python/bindings`, there is no longer any way to pass options to the subordinate CMake invocation.

`--global-option` does not work with PEP0517:
> DEPRECATION: --build-option and --global-option are deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use --config-settings. Discussion can be found at https://github.com/pypa/pip/issues/11859

There is no way to change the command line parameters passed to setup.py.

**Comment by amadio** [comment]
Hi, in order to pass options to the build, you can use `python setyp.py build ...` and pass the options there. When I wrote the build system, I was not aware of another way to pass the build options, but I will be happy to implement it if it's not too difficult. I will have a look at how `--config-settins` works and try to get this into the next patch release.

**Comment by amadio** [comment]
It seems that using `config_settings` is not so easy, due to the lack of documentation. See the discussion at https://github.com/pypa/setuptools/issues/3896, where workarounds are also discussed. I am thinking about using an environment variable (i.e. `PYXROOTD_CMAKE_ARGS` or just `CMAKE_ARGS`) to let you pass build options for now, and when `config_settings` becomes more mature, then we can switch to using that. From the discussions I read, I got the impression that it is a moving target, at least for now, so they should have likely waited a bit more before dropping `--global-option` and `--build-option`.

**Comment by amadio** [comment]
@StefanBruens I see that you specifically ask about building just the python extensions (presumably linking against a pre-installed XRootD client), so I wonder what options were you intending to pass to CMake, so I can cover your use case in 5.6.2. The patch above is for the main setup.py, but I plan to also add a patch which takes CMake arguments from the environment, as `config_settings` seems to be hard to do with setuptools for the moment (we'd need to write our own build backend based on build_meta from setuptools).

**Comment by amadio** [comment]
@StefanBruens I decided to go for the solution with the environment variable, as the cache doesn't let you pass pure CMake options like `--log-level=DEBUG` or `--debug-find`, for example. Cheers,
