### ISSUE TITLE
[Feature] XrootD do not follow symlink and leave original file intact

### ISSUE THREAD

**Issue by juztas** [xrootd/xrootd#2070]
Moving from mailing list to git issue. In case of directory structure like this:
```
/store/data/foo.root
/store/newdata/foo.root -> (symlink) to /store/data/foo.root
```
rm cmd `rm /store/newdata/foo.root` will delete symlink, but it will not follow symlink. Meaning file /store/data/foo.root will remain intact.

In XRootD (mainly we use davs) removing the symlink will follow it, and will delete the file too (gfal-rm davs://...). It would be nice to have a flag, which tells xrootd not to follow symlink and leave origin file intact.

**Comment by abh3** [comment]
Well, here is the problem. Generally, symlinks are not supoorted as a user option. We do use symlink internally but those symlinks treat the links and data as one immutable object. That is, remove the symlink then you need to remove the data that goes with it. So, all the APIs we have do not allow you to explicitly create symlinks. Yes, you can create them under the hood but you cannot avoid the standard processing of symlinks. Introduction of a flag would be confusing as symlinks visibly do not exist. I see no other option than to close this ticket since the request conflicts on how symlinks are actuyally used. Please reopen if you think I have missunderstod the issue here.
