### ISSUE TITLE
cmsd blacklist behaviour when host cannot be found

### ISSUE THREAD

**Issue by Jo-stfc** [xrootd/xrootd#2092]
Hi,
I've recently found a bug or intended behaviour that is not well documented:
If a host in the blacklist cannot be found, the cmsd managers completely ignore the blacklist after a restart.

```
Config processing blacklist file /etc/xrootd/cms.blacklist
Config Unable to blacklist '<hostname>'; Name or service not known
230925 10:16:25 375365 GetBL: Error(s) encountered in blacklist file!
```
this stops the in-memory blacklist from updating (as documented), but a service restart wipes the existing blacklist and the other valid hosts are not blacklisted.

Could this either be clarified in the cmsd documentation or caught in  XrdCmsBlackList::AddBL ?

**Comment by amadio** [comment]
Could you please test this patch?

```diff
diff --git a/src/XrdCms/XrdCmsBlackList.cc b/src/XrdCms/XrdCmsBlackList.cc
index ed5eda173..3fb81ce99 100644
--- a/src/XrdCms/XrdCmsBlackList.cc
+++ b/src/XrdCms/XrdCmsBlackList.cc
@@ -455,7 +455,7 @@ bool XrdCmsBlackList::GetBL(XrdOucTList  *&bList,
 // Return ending status
 //
    blFile.Close();
-   bList = (aOK ? bAnchor.Export() : 0);
+   bList = bAnchor.Export();
    rList = rAnchor[1].Array(rcnt);
    return aOK;
 }
```

This will try to export the list even if some entries were not added correctly.

**Comment by Jo-stfc** [comment]
Thanks Guilherme,
it now flags the specific host as not found and raises the error but then proceeds to blacklist the other hosts.

```
Config processing blacklist file /etc/xrootd/cms.blacklist
Config Unable to blacklist '<nonexistent host>'; Name or service not known
230925 14:28:52 3087232 GetBL: Error(s) encountered in blacklist file!
Config Blacklisting <host in list before>
Config Blacklisting <host in list after>
```

**Comment by Jo-stfc** [comment]
yes, that's the behaviour I wanted. Thanks!

**Comment by abh3** [comment]
As was correctly surmised, the issue stems from this documentation note:
12)  If the blacklist file is present but contains a syntax error or cannot be read, the current black is not changed.

So, yes, on a restart there is no blacklist so nothing winds up being backlisted upon startup.

Now, I agree that the above really isn't very friendly behavior. However, it was meant to force people to correct the problem instead of just ignoring the error because things mostly worked. The unfriendly behavior requires you to do something, which you actually did!

Now, I don't mind this patch. It may cause errors to be ignored or maybe not. This is really a "preference" call. all I do know is that the documentation will need to change either way. 

As for the correctness of the patch, a few things need to change as it causes a memory leak. When the GetBL() is called from the refresh loop, it does not process the new blacklist if the return is false (line 307). That causes the old blacklist to remain in effect but looses all the memory allocated to the new backlist. This problem does not exist at startup because startup knows there is no blacklist *yet* so it ignores the return code and does the obvious thing.

What is needed here is an additional parameter to getB() that says whether this is initialization or not with the default being false;
getBL(..., bool isInit=false);

When getBL() is called from line 497 the parameter should be set to true. Then line 458
bList = (aOK ? bAnchor.Export() : 0);
should be changed to
bList = (aOK || isInit ? bAnchor.Export() : 0);

You would get the desired behavior at startup but not change the blocklist (nor loose memory) upon subsequent refreshes that encounter an error, as is noted in the documentation. Perhaps a pull request is warranted here.

**Comment by amadio** [comment]
@abh. Thank you for the comments. I knew I should have waited for that. I will create a pull request with the change as you suggest above and link it to this issue.

**Comment by Jo-stfc** [comment]
thanks for the comment Andy. That would make sense and functionally this would mean it would initialise the blacklist with all valid entries, but ignore further changes (bar service restart) if any entry error out. As long as this behaviour is documented I'd be happy with the change
