### ISSUE TITLE
Xrootd significantly slower than `cat`

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#2155]
When downloading a 6.8GB file via HTTP from an underlying CephFS, I noticed that XRootD is significantly slower than `cat`:

- Time to download via HTTPS: 20s
- Time to download via HTTPS (hot cache): 6s.  [I include this case to verify that we're not being limited by HTTPS or the overhead of xrootd itself]
- Time to copy file to /dev/null via `cat`: 11s

Now why would `cat` be twice the speed of XRootD?  I verified that XRootD was issuing a nice, big sequence of 2MB reads (for reference, `cat` reads in 256KB chunks).  Since we've eliminated that xrootd or the HTTPS protocol is not the bottleneck, why would two processes issuing sequential reads have a nearly 2x performance difference?

After much experimentation, it appears the difference is `cat` issues the following system call after opening the file:

```
posix_fadvise(fd, 0, 0, POSIX_FADV_SEQUENTIAL);
```

CephFS stripes data across objects in a manner similar to RAID0.  Suppose you set the object size to 4MB, stripe size to 256KB, and stripe count to 4.  In this case, if you read 1MB, Linux will fetch from 4 objects concurrently (1MB / 256KB stripe size = 4 stripes).  If you have a stripe count of 1, then the data is written contiguously in the object; if you read 1MB, Linux will fetch the from 1 object.  Typically, the more parallelism the better -- you're likely pulling data from different storage devices.

The Ceph client's readahead setting will control the amount of data read and, hence, the number of objects read in parallel.  So, the impact of this `posix_fadvise` invocation is significantly increasing the number of ongoing parallel operations for `cat`, much beyond `xrootd`'s parallelism.  Decreasing the readahead down to 8MB (test above is at 128MB), `cat` slows to about the same speed as XRootD/HTTP.

I did a quick patch that invokes the same `posix_fadvise` call immediately after open within the xrootd framework; the time to download via HTTPS shrank to 13s (consistently slower than `cat` but much closer).

Note that the HTTP protocol could have issued a read that triggers `posix_fadvise(fd, 0, 0, POSIX_FADV_WILLNEED);`.  I tried switching the `posix_fadvise` invocation from `POSIX_FADV_SEQUENTIAL` to `POSIX_FADV_WILLNEED`; transfers took about 18s (better than the baseline 20s, but not by much).

So: is it possible to add a protocol extension (or even something hacked through the CGI parameters? or the bridge?) to allow the HTTP framework to provide this apparently-essential hint to the kernel?

@juztas, @ccaffy, and @smithdh - you might be interested in this one.

**Comment by abh3** [comment]
Hi Brian,

Please recall that the oss plugin still has all of the fadvise() logic that you introduced years ago. So, it would be good to leverage that.

Andy
________________________________
From: Brian P Bockelman ***@***.***>
Sent: Saturday, December 16, 2023 1:14 PM
To: xrootd/xrootd ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [xrootd/xrootd] Xrootd significantly slower than `cat` (Issue #2155)


When downloading a 6.8GB file via HTTP from an underlying CephFS, I noticed that XRootD is significantly slower than cat:

  *   Time to download via HTTPS: 20s
  *   Time to download via HTTPS (hot cache): 6s. [I include this case to verify that we're not being limited by HTTPS or the overhead of xrootd itself]
  *   Time to copy file to /dev/null via cat: 11s

Now why would cat be twice the speed of XRootD? I verified that XRootD was issuing a nice, big sequence of 2MB reads (for reference, cat reads in 256KB chunks). Since we've eliminated that xrootd or the HTTPS protocol is not the bottleneck, why would two processes issuing sequential reads have a nearly 2x performance difference?

After much experimentation, it appears the difference is cat issues the following system call after opening the file:

posix_fadvise(fd, 0, 0, POSIX_FADV_SEQUENTIAL);


CephFS stripes data across objects in a manner similar to RAID0. Suppose you set the object size to 4MB, stripe size to 256KB, and stripe count to 4. In this case, if you read 1MB, Linux will fetch from 4 objects concurrently (1MB / 256KB stripe size = 4 stripes). If you have a stripe count of 1, then the data is written contiguously in the object; if you read 1MB, Linux will fetch the from 1 object. Typically, the more parallelism the better -- you're likely pulling data from different storage devices.

The Ceph client's readahead setting will control the amount of data read and, hence, the number of objects read in parallel. So, the impact of this posix_fadvise invocation is significantly increasing the number of ongoing parallel operations for cat, much beyond xrootd's parallelism. Decreasing the readahead down to 8MB (test above is at 128MB), cat slows to about the same speed as XRootD/HTTP.

I did a quick patch that invokes the same posix_fadvise call immediately after open within the xrootd framework; the time to download via HTTPS shrank to 13s (consistently slower than cat but much closer).

Note that the HTTP protocol could have issued a read that triggers posix_fadvise(fd, 0, 0, POSIX_FADV_WILLNEED);. I tried switching the posix_fadvise invocation from POSIX_FADV_SEQUENTIAL to POSIX_FADV_WILLNEED; transfers took about 18s (better than the baseline 20s, but not by much).

So: is it possible to add a protocol extension (or even something hacked through the CGI parameters? or the bridge?) to allow the HTTP framework to provide this apparently-essential hint to the kernel?

@juztas<https://github.com/juztas>, @ccaffy<https://github.com/ccaffy>, and @smithdh<https://github.com/smithdh> - you might be interested in this one.

**Comment by bbockelm** [comment]
> Please recall that the oss plugin still has all of the fadvise() logic that you introduced years ago. So, it would be good to leverage that.

Yes -- sorry, my point about `POSIX_FADV_SEQUENTIAL` versus `POSIX_FADV_WILLNEED` lacked relevant context.

The fadvise logic in the OSS plugin utilizes the `POSIX_FADV_WILLNEED` flag and it works; it appears to provide a reproducible performance benefit (shrinking download time from 20s to 18s).  However, it has a much smaller impact than telling the kernel the future accesses will be sequential (which shrinks download time from 20s to 13s): that is, using the more specific flag gave about a 25% performance boost.

Since we know for this tightly controlled case (HTTP download) that the future access is going to be sequential, I'd like to leverage the implementation-defined behavior of `kXR_Qopaqug` to allow the HTTP layer to inform the bridge layer of its intentions.

**Comment by abh3** [comment]
If you take a look in the protocol docs you will see an open flag: kXR_seqio
https://xrootd.slac.stanford.edu/doc/dev56/XRdv520.htm#_Toc138799708

Currently, nothing is done with this flag if it is specified. It should be promoted through the SFS/Ofs open() option as well as the Oss open() option, so it gets to do an fadvise() the way you want it to. It would work for http as well as xroot doing it this way and is already architecturally designed. Makes sense?

________________________________

**Comment by abh3** [comment]
Oh yes, I can define the flags to be pushed across if that will make it easier for you.
________________________________

**Comment by bbockelm** [comment]
Nice!  I hadn't spotted `kXR_seqio` when I was thumbing through the protocol documentation.  I'll rework my PR to utilize that instead.

**Comment by abh3** [comment]
@bbockelm I just pushed the passing of the kXR_seqio option all the way to the Oss plugin. It's a matter of testing whether O_RSYNC is set in the open flag. So, this should now be easy to implement your pull request. We will still need xrdcp to set that flag as well but you can certainly add it to the http protocol. Remember a couple of things: 1) enable the code only if " __APPLE__" is not defined as it does not have this flag, and 2) make sure to turn off the bit if it is set. Obviously this is only for Linux so the logic will be a bit more complicated to make sure the O_RSYNC bit is turned off.

**Comment by abh3** [comment]
@bbockelm OK, I think you are likely overloaded. So, I implemented the seqio option using fadvise(). My original recommendation on implementation was too fragile in retrospect (largely due to the limitations of the OSS API). So, the fadvise() is actually implemented in the ofs layer as long as we can get a file descriptor and it is not a proxy server. Additionally, a message is written when fadvise() fails. After 4096 failures it's turned off.

**Comment by amadio** [comment]
For completeness, this has been fixed by a78586f01afc2b4536bd7d394ef13e1f07a3c341 and 432cc122cc65275cd41e664f9602ea3f320675b6, which went into v5.7.0.
