### ISSUE TITLE
metalink:: errOperationInterrupted is not IsRecoverable

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#2169]
[xrdlog.txt](https://github.com/xrootd/xrootd/files/14014899/xrdlog.txt)
Hi! Just to have this tracked here: i stumbled upon this case (see attached log) where
a weird error stops metalink to proceed to the next source (so no fallback)
It seems to me that the problem is that errOperationInterrupted is not IsRecoverable [here](https://github.com/xrootd/xrootd/blob/6a1dfa32082c2fb90a6b1a38ad8b0983133283d6/src/XrdCl/XrdClFileStateHandler.cc#L2944)
I previously had this case with errSocketTimeout and it was fixed this way by Michal :)
So, could the experts take a look please? :)
Thanks a lot!!

**Comment by abh3** [comment]
The "operation Interrupted" was due to a stream timeout (i.e. the operation took too long, likely opening a file. The error was with the mgm redirector eos-mgm.grid.pub.ro. Did the connection to the mgm use a metalink file? Clearly, the same thing happened with the connection to eos-fst-storage7.grid.pub.r but that one appeared to recover likely because the error was merely "socket timeout", though the recovery appears to last far longer than it should as it continuously timeout afterwards; which I don't quite understand so I'm not sure this was a good fix.

I guess the bottom like is what connection was using a metalink file?

**Comment by abh3** [comment]
Hi Adrian,

You are correct. Using a metalink file should simply iterate to the next entry regardless of the failure. I suspect it does for practically all errors except errOperationInterrupted for some strange reason, likely an oversight. Please cut a ticket explaining that metalinks should be immune from failure modes otherwise their value is diminished.

Andy

________________________________

**Comment by adriansev** [comment]
Hi @abh3 :) Well, last time i had this discussion with Michal, i remember that there are a errors that would be incompatible with the whole download while others should be recoverable in order to continue to the next source... but was not easy to identify which is which so after the last fix the conclusion was that if i encounter any other case just to announce my problem :) so here i am :) and this is the ticket :)
This is why i suggested to add errOperationInterrupted here just after errSocketTimeout 
https://github.com/xrootd/xrootd/blob/6a1dfa32082c2fb90a6b1a38ad8b0983133283d6/src/XrdCl/XrdClFileStateHandler.cc#L2944-L2945

And to answer to your request: the metalink sources errors should be recoverable to allow the metalink to proceed to the next source and the whole value of metalinks is the ability to have fallback between sources which are replicas of the same file. (there is also the multi source download but i do not use it because in ALICE case replicas can be way too geo distributed)

**Comment by abh3** [comment]
Thanks. Sorry, I thought you were using xrootd-l not github for this exchange. Thank you for logging the problem.,

**Comment by amadio** [comment]
Thank you for the bug report. I am adding `errOperationInterrupted` to the list of recoverable errors, and this will be in our next release, which should come out shortly due to a problem with 5.6.5.
