### ISSUE TITLE
xrootd 5.6.6 :: build failure on macos

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#2175]
Hi @amadio ! and @TimoWilken (for notification)
We just tried to build 5.6.6 in our CI and on macos i see this message:
```
[ 88%] Building CXX object src/XrdCl/CMakeFiles/XrdCl.dir/XrdClZipArchive.cc.o
gmake[2]: *** No rule to make target '/Volumes/build/alice-ci-workdir/alidist-o2/sw/osx_x86-64/UUID/v2.27.1-local2/lib/libuuid.so', needed by 'src/XrdCl/libXrdCl.3.0.0.dylib'.  Stop.
gmake[2]: *** Waiting for unfinished jobs....
[ 88%] Building CXX object src/XrdCl/CMakeFiles/XrdCl.dir/XrdClOperations.cc.o
```

This was on both our macos tests (macOS and macOS-arm) and you can see the tests here:
https://github.com/alisw/alidist/pull/5329

We are updating from 5.6.0 so, is there anything changed related to libuuid?
this is our cmake command: https://github.com/alisw/alidist/blob/master/xrootd.sh#L72

Thanks a lot!

**Comment by amadio** [comment]
Ah, on macOS we are usually taking the OS provided uuid. I think [this](https://github.com/alisw/alidist/blob/2bb6f3c550c12af705501a543048e9edac9185b6/xrootd.sh#L81-L84) is what may cause problems for you. There were some changes in 5.6.x related to this, indeed. Please take a look at commit e53d4c8dd48b497d1f2fcba7238077bde41331b2, and the full history in https://github.com/xrootd/xrootd/commits/master/cmake/Findlibuuid.cmake.

**Comment by amadio** [comment]
BTW, this is how we are building in the CI for macOS:

https://github.com/xrootd/xrootd/blob/de37caac7dc3072fb751f755eccd46fec348b4e7/.github/workflows/CI.yml#L179-L218

**Comment by amadio** [comment]
I unfortunately cannot see the build logs in alisw/alidist#5329, so if you could add `--log-level DEBUG` and paste here what's printed by the lines below, I'd appreciate it. Thanks!

https://github.com/xrootd/xrootd/blob/de37caac7dc3072fb751f755eccd46fec348b4e7/cmake/Findlibuuid.cmake#L106-L113

**Comment by adriansev** [comment]
[fullLog_macos.txt](https://github.com/xrootd/xrootd/files/14053281/fullLog_macos.txt)
[fullLog_macos_arm.txt](https://github.com/xrootd/xrootd/files/14053282/fullLog_macos_arm.txt)

I cannot do that (to make modification on a recipe the CI tests must pass, only @TimoWilken can help) but i attached the full logs given by CI, maybe they are helpful

**Comment by TimoWilken** [comment]
It's your PR, you can do whatever you like @adriansev! :) I've pushed a commit that adds `--log-level DEBUG` to the CMake invocation.

**Comment by adriansev** [comment]
ooh right!!! :tired_face:

**Comment by amadio** [comment]
If you are fine using macOS uuid from the kernel, you can try to just remove those options. Otherwise, my advice would be to set only `UUID_INCLUDE_DIR` and `UUID_LIBRARY`, and leave `UUID_LIBRARIES` and `UUID_INCLUDE_DIRS` for the module to set on its own. I say that because if you set it, it will be a cache variable, and if you let the module set it, then it will be a regular variable, and CMake has strange behavior when regular variables and cache variables with the same name have different values.

**Comment by TimoWilken** [comment]
Thanks for that suggestion @amadio! If I only remove the "plural" variables (`UUID_INCLUDE_DIRS` and `UUID_LIBRARIES`), I get the following, but the build still fails with the same error message:

```
-- Looking for uuid_generate_random
-- Looking for uuid_generate_random - found
-- Found libuuid: /Users/alibuild/Documents/sw/osx_x86-64/UUID/v2.27.1-local5/include  
-- UUID_FOUND        = TRUE
-- UUID_HEADER_ONLY  = 1
-- UUID_INCLUDE_DIR  = /Users/alibuild/Documents/sw/osx_x86-64/UUID/v2.27.1-local5/include
-- UUID_INCLUDE_DIRS = /Users/alibuild/Documents/sw/osx_x86-64/UUID/v2.27.1-local5/include
-- UUID_LIBRARY      = /Users/alibuild/Documents/sw/osx_x86-64/UUID/v2.27.1-local5/lib/libuuid.so
-- UUID_LIBRARIES    = /Users/alibuild/Documents/sw/osx_x86-64/UUID/v2.27.1-local5/lib/libuuid.so
```

**Comment by amadio** [comment]
Indeed, if the file does not actually exist, it would explain the error message you see.

`UUID_HEADER_ONLY  = 1` in this case is not by itself a problem, although it is indeed wrong for the settings you have. It's just printing true because this check succeeds without needing to link the library:

https://github.com/xrootd/xrootd/blob/de37caac7dc3072fb751f755eccd46fec348b4e7/cmake/Findlibuuid.cmake#L46

However, this does not affect how the rest of the file is processed later.

**Comment by TimoWilken** [comment]
I was slightly wrong before, it's a `.a`. Fixing the library name makes it compile properly. Removing the `UUID_LIBRARY` assignment completely also works (since I assume it can be compiled as a header-only library), but I suppose since we've already got the compiled `.a`, we might as well use it.

Fixes pushed to https://github.com/alisw/alidist/pull/5329!

**Comment by adriansev** [comment]
The problematic CIs seems to be green :grin: Thanks a lot @amadio for help!
