### ISSUE TITLE
question about socket longevity

### ISSUE THREAD

**Issue by maksiks** [xrootd/xrootd#2188]
Hi Everyone,

I have a question: how long can xrootd socket be alive during normal operations? When I look at sockets on our xrootd doors sometimes I see them as old as several hours. For, example:
2024-02-09 07:27:38.746139870 -0500 ‘/proc/30986/fd/132’ -> ‘socket:[2983822685]’
2024-02-09 06:06:21.860499383 -0500 ‘/proc/30988/fd/9’ -> ‘anon_inode:[eventfd]’
2024-02-09 06:06:21.860499383 -0500 ‘/proc/30988/fd/8’ -> ‘anon_inode:[eventpoll]’
2024-02-09 06:06:21.860499383 -0500 ‘/proc/30988/fd/5’ -> ‘socket:[2982837598]’

... this what I see at around 2024-02-09 07:27:40. As one can see there are sockets that are an hour old, at the same time I also see:
2024-02-09 06:06:21.853499032 -0500 ‘/proc/30986/fd/12’ -> ‘anon_inode:[eventpoll]’
2024-02-08 17:03:19.621114016 -0500 ‘/proc/998/fd/25’ -> ‘socket:[20111]’
2024-02-08 17:03:19.621114016 -0500 ‘/proc/998/fd/23’ -> ‘socket:[20658]’
2024-02-08 17:03:19.621114016 -0500 ‘/proc/998/fd/22’ -> ‘socket:[20657]’
2024-02-08 17:03:19.621114016 -0500 ‘/proc/998/fd/21’ -> ‘socket:[20656]’

meaning that there are sockets almost 12 hours long. 

I have 3 questions: are there options that limit socket lifetime? Are there options that can limit number of sockets? What will happen if I kill old sockets by hand myself?

Thank you, --Max

**Comment by maksiks** [comment]
Sorry about confusion, what should I call xrootd server that actually does the work and not the all.manager?
The server is installed with xrootd-server-5.6.4-1.1.osg36.el7.x86_64 and in config: all.role server.
--Max

**Comment by abh3** [comment]
Oh, that's a plain data server. So, in that case, you can configure an idle timeout for the data server using the "xrd.timeout idle" directive. See,
https://xrootd.slac.stanford.edu/doc/dev56/xrd_config.htm#_Toc152596851

Some sockets are persistent and use for system services. For instance, the eventpoll and eventfd sockets are used to service the network and are permanently open. There are others as well.The only ones that you should be concerned about are sockets that actually connect to external machines.  These are client sockets and unless the client is unusually busy have a relatively short lifetimes.

**Comment by maksiks** [comment]
Thank you, it all makes clear. 
What would be the client socket timeout you would put given that we are a CMS site?
Also, anything bad might happen to the program if I kill client socket by hand, or I can do it without breaking xrootd program? Or may be there is a built in way to terminate client sockets?
Thank you, --Max

**Comment by abh3** [comment]
The default is 5 minutes which seems to be quite reasonable. You don't want a very short duration because that would cause a lot of reconnections and performance would decrease. The envars that control client-side sockets are:
XRD_DATASERVERTTL
Time period after which an idle connection to a data server should be closed.

XRD_LOADBALANCERTTL
Time period after which an idle connection to a manager or a load balancer should be closed.

As for arbitrary killing of sockets, the client should be abele to withstand that. The bigger question is why you would ever want to do that. Socket connections are very low overhead and there really is no reason to remove them if they are being used. They do get removed when they go idle.
