### ISSUE TITLE
Can XrdOucGatherConf.hh be made public?

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#2214]
I'd like to start updating my externally-maintained modules to `XrdOucGatherConf` from `XrdOucStream`.  However, I was surprised to see that this is not currently exported.  Can we please make this a public header?

**Comment by abh3** [comment]
I think it can. I was planning to also provide it with some additional features such as echoing the line in error should you issue an error message via additional API's. So, now that you know that, do you want me to make it public on the next release (I suppose I might be able to get it done by then).

**Comment by abh3** [comment]
@bbockelm This will happen in 5.7.0. Also, please note that the class has been extended to cover much more of the normal boiler plating that most config file handlers would need to do. Additionally, the class has been redesigned so that it can be easily extended without breaking ABI. You can start migrating to this class using the devel version/ Even though the devel version is backward compatible to the one in master the devel version is far better.

**Comment by bbockelm** [comment]
Excellent, thank you!
