### ISSUE TITLE
error: non-constant-expression cannot be narrowed from type 'time_t' (aka 'long long') to 'long' in initializer list (on armv7)

### ISSUE THREAD

**Issue by yurivict** [xrootd/xrootd#2272]
Build fails on armv7 architectures:
```
/wrkdirs/usr/ports/databases/xrootd/work/xrootd-5.6.9/src/XrdSecgsi/XrdSecProtocolgsi.cc:2059:42: error: non-constant-expression cannot be narrowed from type 'time_t' (aka 'long long') to 'long' in initializer list [-Wc++11-narrowing]
         XrdSutCacheArg_t arg = {kCE_ok, now, AuthzCacheTimeOut, kCE_disabled};
                                         ^~~
/wrkdirs/usr/ports/databases/xrootd/work/xrootd-5.6.9/src/XrdSecgsi/XrdSecProtocolgsi.cc:2059:42: note: insert an explicit cast to silence this issue
         XrdSutCacheArg_t arg = {kCE_ok, now, AuthzCacheTimeOut, kCE_disabled};
                                         ^~~
                                         static_cast<long>( )
/wrkdirs/usr/ports/databases/xrootd/work/xrootd-5.6.9/src/XrdSecgsi/XrdSecProtocolgsi.cc:4681:50: error: non-constant-expression cannot be narrowed from type 'time_t' (aka 'long long') to 'long' in initializer list [-Wc++11-narrowing]
   XrdSutCacheArg_t arg = {CRLCheck, CRLRefresh, timestamp, -1};
                                                 ^~~~~~~~~
/wrkdirs/usr/ports/databases/xrootd/work/xrootd-5.6.9/src/XrdSecgsi/XrdSecProtocolgsi.cc:4681:50: note: insert an explicit cast to silence this issue
   XrdSutCacheArg_t arg = {CRLCheck, CRLRefresh, timestamp, -1};
                                                 ^~~~~~~~~
                                                 static_cast<long>( )
```

Version: 5.6.9
FreeBSD 14.0
clang-18

**Comment by yurivict** [comment]
The problem seems to be that time_t doesn't fit the array due to its size.

**Comment by amadio** [comment]
Could you please try the `devel` branch? I've changed the timeout type to `time_t` there (see #2237).

**Comment by yurivict** [comment]
Sorry, I wouldn't be able to build on armv7.
These builds only occur on the central build servers.

**Comment by ellert** [comment]
> Could you please try the `devel` branch? I've changed the timeout type to `time_t` there (see #2236 and #2237).

This is unrelated to those changes. The variables in question are already declared as time_t in the current version. Changing other unrelated variables to also be time_t will not change this:

https://github.com/xrootd/xrootd/blob/ae3391f39bf3993dc9d767c00bf55611bd20f6a5/src/XrdSecgsi/XrdSecProtocolgsi.cc#L2055

https://github.com/xrootd/xrootd/blob/ae3391f39bf3993dc9d767c00bf55611bd20f6a5/src/XrdSecgsi/XrdSecProtocolgsi.cc#L4679

This issue is that those variables are used to initialize an instance of XrdSutCacheArg_t, which is declared as:

https://github.com/xrootd/xrootd/blob/ae3391f39bf3993dc9d767c00bf55611bd20f6a5/src/XrdSut/XrdSutCache.hh#L42-L47

On a 32-bit system (where a long is 32 bits) that uses a 64-bit time_t, this will lead to an implicit narrowing.

Adding a static_cast<long>() on the two lines that cause the error as the quoted error message suggests will make the narrowing explicit and will remove the error. There will however still be a problem when the 32 bit time value overflows in 2038.
