### ISSUE TITLE
xrdmapc vs. all.export 

### ISSUE THREAD

**Issue by osschar** [xrootd/xrootd#231]
It seems xrdmapc gives some kind of precedence to all.export directives over the locate path specified on the command line.

This can lead to program not functioning properly when one of the export locations on the redirector is actually not available throughout the cluster.

**Comment by abh3** [comment]
The xrdmapc command is local and meant to merely map out a cluster. The command line path argument is there only if you wish to verify that there is access to that particular file on each node.The all.export directive has no meaning in this context because xrdmapc has no way of finding out what it is. The path argument is there merely for convenience should that file be uniformly possible to have present in the cluster. This is done by design.
