### ISSUE TITLE
dilemma when using pss.localroot

### ISSUE THREAD

**Issue by wyang007** [xrootd/xrootd#2312]
I am using a proxy to export a remote storage https://backend.com:443//dir/xrd as root://frontend.com//xrd. To archive this, I tried the following

1. "pss.origin  https://backend.com:443/dir" but this doesn't work because xrootd consider this as invalid URL. It doesn't like the path after port.
2. "pss.localroot /dir" but this also doesn't work because xrootd complains that /dir doesn't exist.

I found a workaround by creating an empty /dir on the "frontend.com" node. But can this be fixed in someway?

Also, when using oss.localroot or psslocalroot, can these values be exposed to sub-processes via an environment variable ? This will be very useful for script that calculate checksums .

Can this be addressed for both remote https:// and root:// storages?

**Comment by abh3** [comment]
As it works out, your problem is equivalent to issue 2068 (https://github.com/xrootd/xrootd/issues/2068). We addressed that problem by adding the directive pss.hostarena <text> where <text> can be anything including, in your case, /dir and this text will be inserted after the <host:port> but before the client specified <path>. This essentialially defines an API endpoint or, if you wish, restricts the origin to a particular arena. This fix will come out in 5.7.1 which will be avalable in a few weeks.

**Comment by wyang007** [comment]
what about the last request, exporting the pss.hostarena via a Unix env. for sub-processes ?

**Comment by abh3** [comment]
Good point. We didn't do that. Easy problem to fix.

**Comment by abh3** [comment]
Actually, the implementation alreaddy exports the text in envar XRDXROOTD_PROXYARENA so that issue has been addressed.
