### ISSUE TITLE
question about gsi -ca:verifyss  option

### ISSUE THREAD

**Issue by rptaylor** [xrootd/xrootd#2316]
Hello,

https://xrootd.slac.stanford.edu/doc/dev56/sec_config.htm#_Toc119617433

describes the -ca option: 
```
verifyss     verify if self-signed, issuing a warning if not;

Default is verifyss. 
```

I can understand only verifying self-signed certificates as those would be the trust anchor roots which are distributed in /etc/grid-security/certificates, but if the result of verification failure is only a warning, it seems that verifyss as the default option is insecure. Does this mean that any certificate issued by any unverified self-signed certificate would be accepted with only a warning?

**Comment by bbockelm** [comment]
> Does this mean that any certificate issued by any unverified self-signed certificate would be accepted with only a warning?

The documentation is misleading.  It says:

> Defines the CA verification level.

It really should say "define the trusted root CA verification level".

That is, if you have a fully verified chain, leading to a root CA found in the CA trust store (e.g., CA file or `/etc/grid-security/certificates`), do you check the signature on the trusted root CA itself?

Validating the trusted root CA makes little sense to me: if an attacker is competent enough to modify your CA store, they're probably competent enough to correctly self-sign their malicious CA.

At best, it's a waste of CPU cycles.  At worst, since root CAs still are permitted to be SHA-1 self-signed, it causes a failure as in #2150.

**Comment by abh3** [comment]
Hi Brian,

OK, I agree. Could you come up withe the appropriate verbiage to substitute for the existing text and the change will happen.

Andy

________________________________

**Comment by bbockelm** [comment]
How about replacing this:

> Defines the CA verification level:
> noverify    do not verify;
> verifyss     verify if self-signed, issuing a warning if not;
> verify         always verify the CA in the chain, failing when not possible.
> Default is verifyss.

with

> Defines the trusted root CA self-signature verification level.  The trusted root CAs are those installed in the CA file or directory.  Options are:
> noverify    do not verify the self-signature; this is the default behavior in OpenSSL;
> verifyss     verify the self-signature, issuing a warning if verification fails;
> verify         verify the self-signature, failing authentication when the verification fails.
> Default is verifyss.

**Comment by abh3** [comment]
Looks good to me, I'll make the documentation change. Thanks Brian.

**Comment by rptaylor** [comment]
I see, thanks for clarifying what the verification is referring to.

**Comment by abh3** [comment]
Documentation has been updated.
