### ISSUE TITLE
XRood::noauth test fails on GNU/Hurd

### ISSUE THREAD

**Issue by ellert** [xrootd/xrootd#2336]
```
$ ctest -R XRootD::noauth
Test project /home/ellert/xrootd/xrootd-5.7.1/obj-i686-gnu
    Start 91: XRootD::noauth::setup
1/3 Test #91: XRootD::noauth::setup ............   Passed    1.99 sec
    Start 93: XRootD::noauth::test
2/3 Test #93: XRootD::noauth::test .............***Failed   15.39 sec
    Start 92: XRootD::noauth::teardown
3/3 Test #92: XRootD::noauth::teardown .........   Passed    0.52 sec

67% tests passed, 1 tests failed out of 3

Total Test time (real) =  19.05 sec

The following tests FAILED:
         93 - XRootD::noauth::test (Failed)
Errors while running CTest
```
The test files used for this test contain random content:

https://github.com/xrootd/xrootd/blob/ae3391f39bf3993dc9d767c00bf55611bd20f6a5/tests/XRootD/noauth.sh#L51-L53

If this line is changed to create smaller files (e.g. changing 1024 to 64) the test no longer fails. But this is not a proper "fix". The test should work for large files too.

These lines can be seen in the client.log.
```
[2024-09-16 07:14:38.866045 +0000][Error  ][XRootD            ] [exodar:3094] Impossible to send message kXR_pgwrite (handle: 0x00000000, offset: 8388608, size: 8396800). Trying to recover.
[2024-09-16 07:14:38.866045 +0000][Debug  ][XRootD            ] [exodar:3094] Handling error while processing kXR_pgwrite (handle: 0x00000000, offset: 8388608, size: 8396800): [ERROR] Operation expired.
[2024-09-16 07:14:38.866045 +0000][Error  ][XRootD            ] [exodar:3094] Unable to get the response to request kXR_pgwrite (handle: 0x00000000, offset: 8388608, size: 8396800)
```
Logfiles from the test:
[client.log](https://github.com/user-attachments/files/17010776/client.log)
[xrootd.log](https://github.com/user-attachments/files/17010778/xrootd.log)

**Comment by amadio** [comment]
@ellert What kind of machine is running the tests? I'd indeed like to avoid decreasing the size of the files tested (this is actually the same as the `smoke.sh` test we had before, so I'm surprised it fails only now). This seems to touch on something we've discussed last week at the [FTS/XRootD Workshop](https://indico.cern.ch/event/1386888) after the presentation [Optimising Vector Read requests for RAL disk storage](https://indico.cern.ch/event/1386888/contributions/6092466/), which is how to better handle timeouts of `readv` requests, which is what the problem seems to be for you (from xrootd.log):
```
240916 07:14:34 17501 XrootdXeq: ellert.17564:8@exodar pub IPv4 login
240916 07:14:34 17501 ellert.17564:8@exodar Xrootd_Protocol: 0100 req=stat dlen=85
240916 07:14:34 17501 ellert.17564:8@exodar ofs_stat:  fn=/home/ellert/xrootd/xrootd-5.7.1/obj-i686-gnu/tests/XRootD/noauth/test-vgzkVl/01.ref
240916 07:14:34 17501 ofs_stat: ellert.17564:8@exodar Unable to locate /home/ellert/xrootd/xrootd-5.7.1/obj-i686-gnu/tests/XRootD/noauth/test-vgzkVl/01.ref; no such file or directory
240916 07:14:34 17501 ellert.17564:8@exodar Xrootd_Protocol: 0100 rc=-1 stat /home/ellert/xrootd/xrootd-5.7.1/obj-i686-gnu/tests/XRootD/noauth/test-vgzkVl/01.ref
240916 07:14:34 17501 ellert.17564:8@exodar Xrootd_Response: 0100 sending err 3011: Unable to locate /home/ellert/xrootd/xrootd-5.7.1/obj-i686-gnu/tests/XRootD/noauth/test-vgzkVl/01.ref; no such file or directory
240916 07:14:34 17501 ellert.17564:8@exodar Xrootd_Protocol: 0100 req=open dlen=104
240916 07:14:34 17501 ellert.17564:8@exodar Xrootd_Protocol: 0100 open unmt //home/ellert/xrootd/xrootd-5.7.1/obj-i686-gnu/tests/XRootD/noauth/test-vgzkVl/01.ref
240916 07:14:34 17501 ellert.17564:8@exodar ofs_open: 102-40644 (644) fn=/home/ellert/xrootd/xrootd-5.7.1/obj-i686-gnu/tests/XRootD/noauth/test-vgzkVl/01.ref
240916 07:14:34 17501 ellert.17564:8@exodar oss_Open_ufs: fd=524288 flags=10003 mode=644 path=/home/ellert/xrootd/xrootd-5.7.1/obj-i686-gnu/tests/XRootD/noauth/xrootd/home/ellert/xrootd/xrootd-5.7.1/obj-i686-gnu/tests/XRootD/noauth/test-vgzkVl/01.ref
240916 07:14:34 17501 ellert.17564:8@exodar ofs_fstat:  fn=/home/ellert/xrootd/xrootd-5.7.1/obj-i686-gnu/tests/XRootD/noauth/test-vgzkVl/01.ref
240916 07:14:34 17501 ellert.17564:8@exodar Xrootd_Response: 0100 sending 86 data bytes; status=0
240916 07:14:34 17501 ellert.17564:8@exodar Xrootd_Protocol: 0100 req=pgwrite dlen=8396800
240916 07:14:34 17501 ellert.17564:8@exodar Xrootd_Protocol: 0100 0 pgwrite 8396800@0 fn=/home/ellert/xrootd/xrootd-5.7.1/obj-i686-gnu/tests/XRootD/noauth/test-vgzkVl/01.ref
240916 07:14:34 17501 ellert.17564:8@exodar Xrootd_Protocol: 0100 pgwrite read timeout; 508 of 512 iov elements left
240916 07:14:34 17501 ellert.17564:8@exodar Xrd_Poll: sending poller 0 enable for link 8
240916 07:14:34 17501 Xrd_Poll: Poller 0 enabled fd 8 entry 1 now at 2
240916 07:14:34 17501 Xrd_Sched: running ellert.17564:8@exodar inq=0
240916 07:14:34 17501 ellert.17564:8@exodar Xrootd_Protocol: 0100 pgwrite read timeout; 507 of 512 iov elements left
240916 07:14:34 17501 ellert.17564:8@exodar Xrd_Poll: sending poller 0 enable for link 8
240916 07:14:34 17501 Xrd_Poll: Poller 0 enabled fd 8 entry 1 now at 2
240916 07:14:34 17501 Xrd_Sched: running ellert.17564:8@exodar inq=0
240916 07:14:34 17501 ellert.17564:8@exodar Xrootd_Protocol: 0100 pgwrite read timeout; 506 of 512 iov elements left
240916 07:14:34 17501 ellert.17564:8@exodar Xrd_Poll: sending poller 0 enable for link 8
240916 07:14:34 17501 Xrd_Poll: Poller 0 enabled fd 8 entry 1 now at 2
240916 07:14:34 17501 Xrd_Sched: running ellert.17564:8@exodar inq=0
...
```
This is probably not unique to GNU/Hurd, so let's see if we can manage to reproduce and fix on Linux.

FYI: @bbockelm @Jo-stfc This might be a good test to play with in your setups. If we can make it reliably reproduce the issue on Linux, we can use this to create a good fix for #2333.

**Comment by Jo-stfc** [comment]
Thanks for the info. 
I'm not an expert in ctest. what is needed to set up the environment for replicating the above?
when I try running just ctest -R XRootD::noauth it cannot find any tests.

**Comment by ellert** [comment]
> it cannot find any tests

@Jo-stfc : You need to cd into the build directory first.

**Comment by Jo-stfc** [comment]
still no luck
```
Test project /home/fur43467/xrdgit/xrootd/build
No tests were found!!!
```
calling ctest without -R works but the tests don't include noauth. is this run from the master or devel branch?

**Comment by ellert** [comment]
Are you building only clients, or are you building as root?
Either will disable the server tests:

https://github.com/xrootd/xrootd/blob/ae3391f39bf3993dc9d767c00bf55611bd20f6a5/cmake/XRootDDefaults.cmake#L45-L47

**Comment by Jo-stfc** [comment]
Thanks @ellert ,
yes I was building as root. currently doing the build as non-root

**Comment by Jo-stfc** [comment]
the test failures were due to improper teardown. on rerun they all pass currently. I'll see if I can replicate it on repeat

**Comment by ellert** [comment]
The XRootD server tests uses very short timeouts:

https://github.com/xrootd/xrootd/blob/ae3391f39bf3993dc9d767c00bf55611bd20f6a5/tests/XRootD/test.sh#L50-L52

Increasing these as in #2340 solves the issue with the failing XRootD::noauth tests on GNU/Hurd for me. If this is relevant for other issues discussed here I do not know.

**Comment by Jo-stfc** [comment]
I've tried increasing the size of the files. 10240 still passed, 102400 failed due to missing folders on an EL8 build

**Comment by Jo-stfc** [comment]
it ran out of integer range on random number generation 
`107: rand: Value "3282841600" outside integer range`

**Comment by amadio** [comment]
> The XRootD server tests uses very short timeouts:
> 
> https://github.com/xrootd/xrootd/blob/ae3391f39bf3993dc9d767c00bf55611bd20f6a5/tests/XRootD/test.sh#L50-L52
> 
> Increasing these as in #2340 solves the issue with the failing XRootD::noauth tests on GNU/Hurd for me. If this is relevant for other issues discussed here I do not know.

We want to use the short timeouts (everything runs locally) to catch and fix issues. If it turns out the the short timeout really is the issue (i.e. with clustering it might be), then we can increase them just enough to avoid problems. I'd like to avoid increasing timeouts just to make tests pass, that's not helpful. If something locally is taking over 2s on lightweight workload, then probably there's something wrong that should be looked into. The script also sets only defaults, you can override them from outside quite easily by just setting the corresponding variables in the environment (i.e. if you have a very slow system).

**Comment by amadio** [comment]
Looking at the logs more closely, this might indeed be a case in which the highly verbose logging in combination with long iovs for pgread/pgwrite could be indeed the issue on slow systems. @ellert Would a request/stream timeout of 5s work in your case? I'm happy to increase these timeouts a bit, just not to minutes instead of seconds. We could also try to tune the logging on the server side to not slow things down too much.
