### ISSUE TITLE
Timing / propagation issue in mv command

### ISSUE THREAD

**Issue by simonmichal** [xrootd/xrootd#235]
The 'FileSystemTest::MvTest' test failes at line 136 due to a timing / propagation issue. It seems that there is a race condition when two consecutive mv commands (second depending on the first one) are executed.

**Comment by abh3** [comment]
Hi Michal,

Could you provide the command sequence here? I assume this is being done via xrdfs using a redirector. What is the error message that you get? That will provide a good clue on what happened.

Andy

**Comment by simonmichal** [comment]
Hi Andy,
I observed this behaviour in the unit tests:
xrootd/tests/XrdClTests/FileSystemTest.cc -> test case: MvTest, the test was done with one metamanager, 2 managers, and 4 data servers.

There is a race condition in the following code snippet:

  CPPUNIT_ASSERT_XRDST( fs.Mv( filePath1, filePath2 ) ); // first move operation
  CPPUNIT_ASSERT_XRDST( fs.Mv( filePath2, filePath1 ) ); // second move operation

that's the error message:

FileSystemTest.cc:136:Assertion
Test name: FileSystemTest::MvTest
assertion failed
- Expression: st.IsOK()
- [fs.Mv( filePath2, filePath1 )]: [ERROR] Server responded with an error: [301
1] No servers are available to write the file.

It seems to me that the 'Mv' operation is asynchronous and sometimes the second move operation is being executed before the first one (it might be that this behaviour is correct and the test case is erroneous, this needs clarification?)

**Comment by abh3** [comment]
Hi Michal,

If the two mv operations are being performed in parallel then indeed the results are unpredictable. That said, I don’t think the test framework is does that. I believe everything is done serially. You are correct, though, that part of the mv operation is asynchronous. This is because the operation is considered complete once notifications of file registration changes have been sent but not necessarily received or even processed (i.e. this is not a 2-phase commit operation). So, it is possible that the second mv may fail because it is initiated before the first one fully completes.

Andy

**Comment by ljanyst** [comment]
They aren't.

**Comment by abh3** [comment]
This is a timing issue. When the rename happens, the xrootd sends the cmsd a message that old file no longer exists and then a second message that the new (i.e. renamed) file does exist and completes the client interaction. If it so happens that the next rename occurs before the cmsd can register the new file as existing, it will indicate that the file does not exist. Short of making this a transnational operation relative to the cmsd, this timing hole will exist. This exposure exists if the renamed file was looked up by the cmsd at some point in the past (e.g. a stat() operation on the target file) was done on the recent past. I do not propose we add that kind of capability to the cmsd as this kind of operation is rarely, if ever, done in practice.
