### ISSUE TITLE
gstream hit and miss numbers are wrong

### ISSUE THREAD

**Issue by ddavila0** [xrootd/xrootd#2366]
The hit and miss data reported by xcache (gstream) is misleading. For example, requesting 4K bytes[1] from a file, that is NOT in the cache, is reported as 100% hit[2]

[1]
```
curl --cert /tmp/x509up_u31717 --cacert /tmp/x509up_u31717 --capath /etc/grid-security/certificates/ -r 0-4194304 https://xcache-10.t2.ucsd.edu:1094//store/user/ddavila/1G -o /tmp/4M
```

[2]
```
[root@xcache-10 ddavila]# xrdpfc_print -v 1G.cinfo 
FILE: 1G.cinfo
version 4, created Thu Oct 31 21:35:04 2024; cksum net
file_size 1048576 kB, buffer_size 512 kB, n_blocks 2048, n_downloaded 18, state incomplete [0.879%]
printing 2048 blocks:
               1         2         3         4         5         6
     0123456789012345678901234567890123456789012345678901234567890123
   0 xxxxxxxxxxxxxxxxxx..............................................
  64 ................................................................
...
Record Attach         Detach         Duration     N_ios N_mrg    B_hit[kB]   B_miss[kB] B_bypass[kB]
1      241031:213504  241031:213534  0:00:30          1     0         4096            0            0
 ```

**Comment by osschar** [comment]
In this particular case, you seem to have been helped by prefetching, note that the file has 18 512kB blocks downloaded after your interaction with the cache. So, cache had the data when you asked for it. How do you want to account for prefetching? Do you want a separate field in g-stream?

Second, we know there is a problem when async reading is used and the layer above PFC chunks up read requests into 64kB pieces -- and PFC sends out a request to the remote to get a full block (512kB in this case) and would concequently, when the other 64kB async requests come in, mark them as already available in the cache. We are looking into this case with @abh3.

[ Note, with async fully supported since 5.5, you really want to reduce the size of pfc.blocksize, default is now 128kB, you might want to go down to 64kB --- unless there is a real reason why it needs to be large, e.g., when fronting an object store. ]

**Comment by ddavila0** [comment]
How could the prefetcher know what to prefetch if that file was brand new and that was the first request for such file?

The way I think of hit/miss is: if at the time I receive a request for N bytes, those bytes are already in the cache, then is a hit, else is a miss. The only time prefetch should help to increase the hit/miss ratio is when a user request N bytes, waits some time and then request the following N+d bytes (N=miss, d =hit). 

On the other hand, If a user were to request a full file in a single request and the file is not in the cache, the full file should be considered a miss.

Thanks for looking at this :)

**Comment by osschar** [comment]
Prefetcher is really stupid, it just reads the whole file. I have been planning to work on this for a long while (to do read-ahead based on the last read), make it a config option, potentially even on a per-file basis through the opaque arguments. But then there is always something else that needs to be done :smile:

**Comment by ddavila0** [comment]
that still doesn't explain how it magically brought a brand new file, that nobody has ever requested, into the cache, just before I sent the 4K request.

**Comment by osschar** [comment]
well, it does ... when cache gets open request, it starts prefetching right away, the connection to the remote is already established at this point as pss layer went out and made sure the file exists out there. when the open finishes on the client side and the read request comes back to the cache, it has already downloaded 9 MB of data.
