### ISSUE TITLE
Deadlock in Monitor Object

### ISSUE THREAD

**Issue by apeters1971** [xrootd/xrootd#248]
We found today 8 machines in CMS which threads in a deadlock. Maybe this has been resolved already, this is Xrootd 3.3.6

#0 0x00000039f060e264 in __lll_lock_wait () from /lib64/libpthread.so.0
#1 0x00000039f0609508 in _L_lock_854 () from /lib64/libpthread.so.0
#2 0x00000039f06093d7 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3 0x000000000041a2a2 in Lock (this=0x7f854b00e600, dictid=1734875904, rTot=0, wTot=0) at /usr/src/debug/xrootd/xrootd/src/XrdSys/XrdSysPthread.hh:149
#4 XrdXrootdMonitorLock (this=0x7f854b00e600, dictid=1734875904, rTot=0, wTot=0) at /usr/src/debug/xrootd/xrootd/src/XrdXrootd/XrdXrootdMonitor.cc:199
#5 XrdXrootdMonitor::Close (this=0x7f854b00e600, dictid=1734875904, rTot=0, wTot=0) at /usr/src/debug/xrootd/xrootd/src/XrdXrootd/XrdXrootdMonitor.cc:353
#6 0x0000000000426ac4 in XrdXrootdProtocol::do_Close (this=0x7f8503712200) at /usr/src/debug/xrootd/xrootd/src/XrdXrootd/XrdXrootdXeq.cc:439
#7 0x00000039f224ee69 in XrdLink::DoIt (this=0x7f84f3549008) at /usr/src/debug/xrootd/xrootd/src/Xrd/XrdLink.cc:442
#8 0x00000039f2252d05 in XrdScheduler::Run (this=0x39f1c0b900) at /usr/src/debug/xrootd/xrootd/src/Xrd/XrdScheduler.cc:307
#9 0x00000039f2252ef9 in XrdStartWorking (carg=<value optimized out>) at /usr/src/debug/xrootd/xrootd/src/Xrd/XrdScheduler.cc:84
#10 0x00000039f222165f in XrdSysThread_Xeq (myargs=0x7f8363af89e0) at /usr/src/debug/xrootd/xrootd/src/XrdSys/XrdSysPthread.cc:86
#11 0x00000039f06079d1 in start_thread () from /lib64/libpthread.so.0
#12 0x00000039f02e88fd in clone () from /lib64/libc.so.6

**Comment by abh3** [comment]
Hi Andreas, I can't answer this without seeing the stack trace for all the threads. Here I can't tell what it is deadlocking on. Could you provide a full stack trace?

**Comment by esindril** [comment]
I believe we have seen this before. I have looked into it some time ago and below you have some additional information. I also have a 5GB core file, if you need it let me know and I can put it in my public afs directory.

A thread was looping in the monitoring code around this point:
#0  0x000000000041a1c0 in do_Shift (this=0x7f11fb80e600, dictid=3290236416, rTot=<value optimized out>, wTot=670147) at /usr/src/debug/xrootd/xrootd/src/XrdXrootd/XrdXrootdMonitor.cc:882

since the right shift applied on a negative value will fill with 1 the vacant bits. Therefore, the thread will never exit the while loop and the enclosing Close method will hold the lock forever.

The source of the problem is why the xTot value is negative - I couldn't find a better explanation than a memory corruption or an overflow ...
Looking at the XrdXrootdFileTable object confirms that the xfr.read value is negative. This in principle should always be positive since it represents the number of bytes read from the file - so probably it would be best to have this value be an unsigned type.

```
(gdb) f 2
#2  0x000000000041485a in XrdXrootdFileTable::Recycle (this=0x7f119ab8c0c0, monP=0x7f11fb80e600, monF=false) at /usr/src/debug/xrootd/xrootd/src/XrdXrootd/XrdXrootdFile.cc:234
234                                     FTab[i]->Stats.xfr.write);
(gdb) print *FTab[1]
$21 = {XrdSfsp = 0x7f116b7dc000, mmAddr = 0x0, FileKey = "3141", '0' <repeats 12 times>, "9099e81c00\000ame=mam", Reserved = "ar", FileMode = 119 'w', AsyncMode = 0 '\000', isMMapped = 0 '\000', sfEnabled = 0 '\000', fdNum = 32506,
  ID = 0x7f11ab5381fc "daemon.8151:167@p05614923e75338", Stats = {FileID = 3290236416, MonEnt = -1, monLvl = 1 '\001', xfrXeq = 1 '\001', fSize = 31895106, xfr = {read = -205550562, readv = 0, write = 670147}, ops = {read = 1,
      readv = 0, write = 51, rsMin = 32767, rsMax = 0, rsegs = 0, rdMin = 2147483647, rdMax = 0, rvMin = 2147483647, rvMax = 0, wrMin = 2147483647, wrMax = 0}, ssq = {read = 0, readv = 0, rsegs = 0, write = 0}},
  static Locker = 0x7f11fb8306f0, static sfOK = 0, static TraceID = 0x4299ee "File"}
```

Notice the xfr.read value which is negative.

The only info I could extract from the coredump is the identity of the client which opened the file and then making the correlation with the log file form today is seems the connections was quite long-lived:
150526 09:27:07 28615 XrootdXeq: daemon.8151:167@p05614923e75338 disc 1794:27:30

**Comment by apeters1971** [comment]
Can this be due to request corruption? Do you have a simple checksum on requests? Probably not ...
```
struct ClientReadRequest {
   kXR_char  streamid[2];
   kXR_unt16 requestid;
   kXR_char fhandle[4];
   kXR_int64 offset;
   kXR_int32 rlen;
   kXR_int32  dlen;
};

If rlen is negative it get's added via:

// If we are monitoring, insert a read entry                                                                                                                                                          
//                                                                                                                                                                                                    
   if (Monitor.InOut())
      Monitor.Agent->Add_rd(myFile->Stats.FileID, Request.read.rlen,
                                                  Request.read.offset);

```

**Comment by abh3** [comment]
Good point Andreas. While the request would have failed the monitoring doesn't check for it. The appropriate fix would be to do both, verify the value as well as avoiding overflows.
