### ISSUE TITLE
unable to delete paths not starting with '/' via xrdfs

### ISSUE THREAD

**Issue by sponce** [xrootd/xrootd#314]
I'm running an xrootd server with ceph plugin and thus dealing with objects. By nature, their names are not always starting with a '/'. For this purpose, I have the entry 'all.export *?' in my xrd.cf file and I can happily transfer objects.
The problem comes when I want to drop one. Here is what happens :

# xrdfs lxbrl59a04.cern.ch:1095 rm testbigfile
[ERROR] Server responded with an error: [3010] Removing path '/testbigfile' is disallowed.

Obviously a leading '/' was added. Now as the object /testbigfile does not exist, I get an error, but I could as well have dropped the wrong object !

**Comment by sponce** [comment]
I confirm that while testing something else, the wrong file was deleted !
This really needs a fix !

**Comment by abh3** [comment]
Presumably the solution here is to never add the leading slash. That will change existing behavior but likely for the better since (as Sebastien points out) adding the leading slash behind one's back may indeed refer to an object that you didn't think you were referring to. However, I can see some people objecting should they have relied on this, The alternative is to add an option that suppresses the addition of a leading slash. So, give me your thoughts on:
a) Never add a leading slash, or
b) Always add a leading slash unless some option is specified (e.g. --objectid)

**Comment by abh3** [comment]
I am still waiting for comments on the previous post.

**Comment by sponce** [comment]
I did not comment as I do not have strong opinion.
In the absolute, never add a leading slash is the right thing to do, but I understand the backward compatibility issue and option b will also work for me.

**Comment by alastairdewhurst** [comment]
Hi

At RAL, we have a strong opinion to never add a leading slash.  This is what we have done with our GridFTP plugin.

Alastair

**Comment by abh3** [comment]
I think this is still open. Why did we ever add the leading slash? In any case, I think that to keep backward comparability we need to add "--objectid". On the other hand, I am prone to thinking that keeping this behavior is not a good idea as it may indeed result in the wrong file to be deleted. So, Michal, the ball is in your court.

**Comment by simonmichal** [comment]
IMHO we should drop the leading slash, I would rather consider this a bug not a feature.

The leading slash is being appended because a routine is being called that appends the cwd in front of the path and than collapses . and .. , and in batch mode the cwd is assumed to be the root directory and hence the slash.

In my opinion this routine makes sense only in case of interactive mode, and does not in case of batch mode.

**Comment by abh3** [comment]
OK, you want to  fix that in 4.4? Perhaps also an option to turn off cwd prefixing in interactive mode.
