### ISSUE TITLE
xrootd server not able to accept paths with leading slash when all.export is *?

### ISSUE THREAD

**Issue by sponce** [xrootd/xrootd#316]
Still playing with xrootd in front on an object store (ceph). Due to the fact that objects names do not have a leading '/', I have an 'all.export *?' entry in xrd.cf file.
I can happily read and write objects as long as their name as no leading slash.
But now, a leading slash break the writing with the following error : 

Run: [ERROR] Server responded with an error: [3010] Opening path '/testbigfilenewws' is disallowed.

What happens is that the Squash function called at line 2380 of XrdXrootd/XrdXrootdXeq.cc does not accept the path, as the call to Validate that is inside does not manage to match my object name (say /foo) to the given export entry (*?).
Looks like this was overlooked when the *? syntax was introduced.

**Comment by abh3** [comment]
Hi Sebastien,

You can have both. If you want a leading slash then export something with a leading slash. If you want to accept objects without a leading slash then export “*”. You can have as many exports as you like.

Andy

From: Sebastien Ponce 
Sent: Monday, December 07, 2015 7:19 AM
To: xrootd/xrootd 
Subject: [xrootd] xrootd server not able to accept paths with leading slash when all.export is *? (#316)

Still playing with xrootd in front on an object store (ceph). Due to the fact that objects names do not have a leading '/', I have an 'all.export *?' entry in xrd.cf file.
I can happily read and write objects as long as their name as no leading slash.
But now, a leading slash break the writing with the following error : 

Run: [ERROR] Server responded with an error: [3010] Opening path '/testbigfilenewws' is disallowed.

What happens is that the Squash function called at line 2380 of XrdXrootd/XrdXrootdXeq.cc does not accept the path, as the call to Validate that is inside does not manage to match my object name (say /foo) to the given export entry (*?).
Looks like this was overlooked when the *? syntax was introduced.

**Comment by sponce** [comment]
Ah ok. Got it now. When putting 2 entries like this : 
  all.export *?
  all.export /
Everything is ok.
Closing the ticket.
