### ISSUE TITLE
Do not require leading slashes in AuthDB path

### ISSUE THREAD

**Issue by alastairdewhurst** [xrootd/xrootd#392]
In the authDB the path needs to start with a / otherwise it will be assumed to be a template.  For object stores (e.g. Ceph) we do not want/need to start our path with a /.  We would like to request that a flag is added to the AuthDB configuration which will accept paths that don't start with a /.  This would avoid causing problems for anyone who has relied on the current setup from running into problems. 

Currently required AuthDB format:
u atlasprod /atlas:data/ a /atlas:scratch/ a
What we would like:
u atlasprod atlas:data/ a atlas:scratch/ a

**Comment by abh3** [comment]
This has been fixed in release 4.4, please look at the documentation

http://xrootd.org/doc/dev44/sec_config.htm#_Toc454139150

This shows how obectids without a leading slash are specified in the auth file. So, I am closing this issue as we are already in the 4.4 release cycle (RC2 is coming out soon followed by the official release).
