### ISSUE TITLE
Increase waiting time in case of refused connection

### ISSUE THREAD

**Issue by graffaele** [xrootd/xrootd#394]
In case of proxy not reachable, clients get connection refused and quickly die. Increasing wait time between retries could avoid high rates of dying clients.

**Comment by bbockelm** [comment]
What do you mean by "proxy not reachable" here?  An Xrootd proxy service?  Not on the network?

The flip side of this is short timeouts for a dead server provide faster feedback to users and potentially wastes less time...

**Comment by graffaele** [comment]
Yes, when clients for some reason get refused connection to xrootd proxy server. I don't know the current value, but, also talking with Andy, it seems that a bigger wait time can be a good trade off between fast feedback and avoiding to kill xrootd clients "too easily".

**Comment by abh3** [comment]
OK, I have gotten to the bottom of this and it's an ALICE specific problem. There are two cases here when ECONNREFUSED is encounetred:

1) The old client and old xrdcp gives up after 35 seconds. There are two envars that control thsi:
XRD_RECONNECTWAIT which specifies the wait timebetween connect() tries. The default is 5 seconds. Increasing this increasing the time it takes to give up.
XRD_FIRSTCONNECTMAXCNT which specifies the maximum number of connect() tries. Increasing this value also increases the time before a fatal error occurs.

2) The new client and new xrdcp gives up after 8 minutes.There are envar settings that can increase or decrease this window but 8 minutes is a reasonable amount of time for a server restart.

The real problem here is that ALICE uses the old client/xrdcp. I have advised GSI that the preferabele solution is to migrate to the new client/xrdcp. Otherwise, the above envars should be set to increase the time before a fatal error is declared.

**Comment by graffaele** [comment]
Thanks Andy, we'll try your advice.
