### ISSUE TITLE
Make supervisor port configurable

### ISSUE THREAD

**Issue by osschar** [xrootd/xrootd#408]
This is an enhancement request. Currently supervisors always revert to xrd.port any. This is inconvenient when a supervisor runs behind a firewall (or has a restricted iptables configuration) as it requires a full port range to be opened between xrootd servers and the supervisor.

Please provide a way to specify port or port-range for supervisors.

**Comment by osschar** [comment]
Actually, this requires a full port range to be open also for clients! Can we please bump the priority of this request?

**Comment by xrootd-dev** [comment]
Could you explain exactly what it is you want w.r.t. "full port range"?

**Comment by abh3** [comment]
Hi Matevz,

I just pushed a fix for this issue. You now get a new directive (for backward compatibility):

cms.superport {any | -p | <port>} [if ....]

The default is "any" which provides backward compatibility. The "-p" option says use whatever was specified on the command line using the "-p" option. Otherwise you can specify the port number or the service port name. You can also qualify it with an inline "if".

This will apear in 4.7.0. Of course, you can use git head if you like.

Andy

**Comment by osschar** [comment]
Excellent, thanks! I'll apply this to UCSD setup tomorrow :)

Matevz
