### ISSUE TITLE
Feature: Integration with std::istream

### ISSUE THREAD

**Issue by petrmanek** [xrootd/xrootd#412]
Hello,

For my application, I have written [a simple class](https://gist.github.com/petrmanek/2f4196a6dd5f1c0187cbeb0a0529fbc2) for buffered reading compatible with `std::istream` using `XrdCl`. It can be used like this:

```
#include <istream>
XRdInputStreamBuf buf("root://..../my_file.txt");
std::istream input(&buf);
// Handle 'input' as if it were std::ifstream or std::sstream.
```

I'm creating this thread because I thought somebody else might benefit from it too. My code can be generalized to work as convenient part of the library, and to buffer not only reads, but writes as well.

Cheers,
Petr.

**Comment by simonmichal** [comment]
Hi Petr,

Sorry for the late response!

I'm rather sceptical since this type of adapter employs synchronous calls, which are discouraged due to performance reasons. It also adds maintenance costs of another public header.
(although I agree it looks rather neat ;-)

For now I'll close it, as there was no interested in this issue.

Thanks,
Michal
