### ISSUE TITLE
Build fails on Solaris 10 due to void* used to initialize char*

### ISSUE THREAD

**Issue by klabattermann** [xrootd/xrootd#431]
The build on Solaris 10 is failing in:
[  4%] Building CXX object src/CMakeFiles/XrdUtils.dir/XrdSys/XrdSysLogging.cc.o
    "/zpool1/wilko/tmp/xrdbuild/v45/src/XrdSys/XrdSysLogging.cc", line 161: 
     Error: Cannot use void* to initialize char*.
     1 Error(s) detected.
     gmake[2]: *** [src/CMakeFiles/XrdUtils.dir/XrdSys/XrdSysLogging.cc.o] Error 2

The compiler used is Sun C 5.11 SunOS_i386 2010/08/13. It is failing in all v4 releases. It is not critical for us as we are phasing out all of our Solaris servers and running older versions is fine.
I am wondering if this is something easy to fix or a problem that the platform and compiler are pretty old.

**Comment by xrootd-dev** [comment]
Yes, it should have been "char*" and will work just fine everywhere.

Andy

**Comment by abh3** [comment]
This has been fixed in 4.6.

**Comment by xrootd-dev** [comment]
Hi Wilko,

Was this fixed?

Andy

From: Wilko Kroeger 
Sent: Wednesday, November 02, 2016 10:05 AM
To: xrootd/xrootd 
Subject: [xrootd/xrootd] Build fails on Solaris 10 due to void* used to initialize char* (#431)

The build on Solaris 10 is failing in:
[ 4%] Building CXX object src/CMakeFiles/XrdUtils.dir/XrdSys/XrdSysLogging.cc.o
"/zpool1/wilko/tmp/xrdbuild/v45/src/XrdSys/XrdSysLogging.cc", line 161:
Error: Cannot use void* to initialize char*.
1 Error(s) detected.
gmake[2]: *** [src/CMakeFiles/XrdUtils.dir/XrdSys/XrdSysLogging.cc.o] Error 2

The compiler used is Sun C 5.11 SunOS_i386 2010/08/13. It is failing in all v4 releases. It is not critical for us as we are phasing out all of our Solaris servers and running older versions is fine.
I am wondering if this is something easy to fix or a problem that the platform and compiler are pretty old.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.



--------------------------------------------------------------------------------

Use REPLY-ALL to reply to list

To unsubscribe from the XROOTD-DEV list, click the following link:
https://listserv.slac.stanford.edu/cgi-bin/wa?SUBED1=XROOTD-DEV&A=1

**Comment by klabattermann** [comment]
Hello Andy

Looks like it has been fixed. I just checked the Solaris x86 4.7.0 build and 
it didn't fail in XrdSys/XrdSysLogging.cc.o.

However it failed later on:
  CC: Warning: Option -std=c++0x passed to ld, if ld is invoked, ignored otherwise
  Linking CXX shared library libXrdUtils.so
  CC: Warning: Option -std=c++0x passed to ld, if ld is invoked, ignored otherwise
  ld: fatal: option -d has illegal argument '=c++0x'

Cheers,
   Wilko
