### ISSUE TITLE
Segmentation fault on closing an EOS file 

### ISSUE THREAD

**Issue by peremato** [xrootd/xrootd#440]
Hi,
  We have a couple of ROOT reports on crashes at exit. The XROOTD version is  4.4.1
https://sft.its.cern.ch/jira/browse/ROOT-8507
https://sft.its.cern.ch/jira/browse/ROOT-8508
This second one is very easy to reproduce on lxplus.

**Comment by esindril** [comment]
This has already been fixed by the following commit:
https://github.com/xrootd/xrootd/commit/7bfa28435a70b71257e0defa239ff963f6e0fc39

**Comment by peremato** [comment]
Thanks very much. When will you be tagging it?

**Comment by simonmichal** [comment]
This fix has been already included in 4.5.0

(https://github.com/xrootd/xrootd/releases/tag/v4.5.0)

Cheers,
Michal

**Comment by esindril** [comment]
Hi Michal, 

I don't think this is included in 4.5.0 ...
But anyway it will for sure be in 4.5.1 which we'll probably tag in January.

Cheers,
Elvin

**Comment by simonmichal** [comment]
Yes it is ;-) the last commit in 4.5.0 is e15771a3bb9ca8fd26ddfc01b3d1f62965d7227a
it is cherry-picked 7bfa28435a70b71257e0defa239ff963f6e0fc39

that's the line in question:
https://github.com/xrootd/xrootd/blob/v4.5.0/src/XrdCl/XrdClFileStateHandler.cc#L395

(the plan is to have 4.6.0 in January because of the Caching Proxy)

Cheers,
Michal

**Comment by esindril** [comment]
Ahh ... yes, you're right! :) The cherry-picking fooled me there!
