### ISSUE TITLE
xrdfs <redirector> ls Seems to Query All Gateways

### ISSUE THREAD

**Issue by dabercro** [xrootd/xrootd#462]
When I make the call:

    xrdfs xrootd.cmsaf.mit.edu ls /store/

I get multiple copies of the directory listing. This happens for other sites that I've tried, including T2_US_MIT (this call), T3_US_MIT, and T2_US_Nebraska. The number of copies seem to match the number of gateway nodes, leading me to suspect that the redirector is forwarding this request to all gateways.

In comparison, if I make this call (directly to a gateway):

    xrdfs xrootd11.cmsaf.mit.edu ls /store/

I get only one copy of the directory contents.

When under heavy load, some of the gateways might go down, giving log messages like:

    cannot allocate memory

or

    broken pipe

or

    bad file descriptor

and the redirector also returns a warning when one of the gateways fails, even if others succeed, instead of falling back to exclusively working redirectors.

Is this the desired behavior? To lessen the load while making many `ls` calls, I am currently trying to cycle through gateways myself. It might be better if there was some way to get the redirector to call only one gateway server at a time. Is there some way to do this?

**Comment by abh3** [comment]
There really is no ideal solution here. The reason is that there is a conflict between people wanting a full listing and wanting it produced in a reasonable amount of time. Hence, the xrdfs command does a parallel search. Of course, you can do this manual in a script by grabing the output of the xrdfs locate command and then cycling through each redirector one at a time. Even that is not ideal because any redirector may actually be talking to other redirectors, so it becomes less than easy to control listings. Now all of that said, I am skeptical (and always was) of doing an "ls" on a worldwide distributed directory structure relative to its usability, usefulness, correctness, and scalability. I'd say it work on a local level but makes little sense on a global level.

**Comment by dabercro** [comment]
Okay, I'll through individual doors. Now I am running into a different problem when trying to speed up that process. Let me know if I should open a new issue for this:

I'm trying to run a few calls in a parallel, but when I pass the python object XRootD.client.FileSystem into a thread (I'm spawning threads with multiprocessing.Process) the listdir function hangs. If I call the same function as I do with multiprocessing.Process without any threading, everything works just fine.

**Comment by ljanyst** [comment]
The state of multi-threading in Python is abysmal. To preserve your own sanity, just don't use it.

**Comment by ljanyst** [comment]
You can submit the request asynchronously through the XRootD API to deal with performance issues. In that case the C++ layer will handle all the threading.

**Comment by bbockelm** [comment]
@ljanyst - nah, don't use the asynchronous XRootD API from python.

It's very deadlock prone due to lock ordering issues (the same reason it's tough / impossible to use the C++ client asynchronously in a C++ application - too many callbacks occur with different sets of locks held by the framework).

I haven't been able to put together a single application that uses the asynchronous API from python that *doesn't* have a deadlock.

Only use the `multiprocessing` module.

**Comment by ljanyst** [comment]
Interesting. Do you know if `multiprocessing` forks the Python interpreter? Have you looked at what happens to the clinet's background threads? I've had multiple problems with multiprocessing that refused to work in the presence of non-picklable objects even if they were never passed between processes. Mutli-threading deadlocks with a lot of C extensions, I've seen `numpy` break if it was used on unrelated arrays in different threads.

**Comment by ljanyst** [comment]
Do you not use the async API in CMSSW anymore?

**Comment by ljanyst** [comment]
AFAIR, the client only holds locks during error callbacks, that was on the list to be redone. I have not been following closely.

**Comment by bbockelm** [comment]
Yes - `multiprocessing` forks the python interpreter.  As long as you use the synchronous API, no Python is invoked inside the client background pools - just the C++ handler.  That means the GIL isn't touched, which means the deadlocks go away.

I'm very happy with my Python scripts that use `multiprocessing` + `sync` APIs.  That's definitely the direction for @dabercro.

Yeah - CMS still uses the async API and we still have odds-n-ends issues with locks on the error recovery paths.  It's incredibly tricky and I wouldn't advice folks to go down that path if they weren't already there.  I do think it'd improve if the error callbacks were done on the background thread pool.

**Comment by ljanyst** [comment]
Well, this doesn't mean that there's anything particularly wrong with the API, there's just a well known bug that needs to be fixed.

**Comment by dabercro** [comment]
Okay, I have something that's working with the multiprocessing module. I don't know too much about the backend, but if I make an xrootd connection (making a FileSystem object) in the master thread, and then try to pass that connection to a process, it seg faults. If I make any connection in the master thread and also create a connection in a forked process, that forked process object hangs on dirlist. I have to make all the connections inside of it's own process (and do nothing in the master thread). That's not really a problem, but I have to do some queuing gymnastics when I want to retry a failed directory listing on a different door...
