### ISSUE TITLE
XRootD Client Plugin manager needs more flexibility

### ISSUE THREAD

**Issue by abh3** [xrootd/xrootd#491]
Currently, plugin selection via config file is based on a URL prefix which includes "<protocol>://<host>". However, in certain cases one would like a plugin to apply to all URL's regardless of host. For instance, plugins that want to alter the URL to direct a client to a proxy. It's not possible to do that via the configuration file. The client should minimally allow plugin selection by protocol irrespective of host. Alternatively, here should be a way to configure a plugin that applies to everything.

**Comment by ljanyst** [comment]
There is a way to have a plugin that applies to everything: https://github.com/xrootd/xrootd/blob/master/src/XrdCl/XrdClPlugInManager.cc#L141

**Comment by esindril** [comment]
Yes, Lukasz, that's true by this only works if you specify it as an env variable though XRD_PLUGIN. What we need is a bit more flexibility of the current configuration so that one can specify something like "url = *" - so that the particular plugin applies to all URLs. The env specified plugin would still have the highest priority.

**Comment by esindril** [comment]
Fixed by commit:
https://github.com/xrootd/xrootd/commit/5566276e181c0f074c87589d449de582264b4d81
