### ISSUE TITLE
Build errors with gcc 7.1

### ISSUE THREAD

**Issue by peremato** [xrootd/xrootd#514]
See for example http://cdash.cern.ch/upload/77d289524da8eceda226d08656c4b03b4ecba81c/xrootd-4.5.0-build.log

**Comment by xrootd-dev** [comment]
Hi Pere,

I will look at this. We normally do not build with the options being used 
as there are some code optimizations that trigger these pedantic warnings. 
As they may or may not be easily avoided, we recommend not using the 
extensive (and overly sensitive) gcc warning settings.

Andy

**Comment by peremato** [comment]
Hi Andy,
I am not sure what options are you referring. Looking at the recipe this is the way to build it in the LCG stack:
```
LCGPackage_Add(
  xrootd
  URL ${GenURL}/xrootd-${xrootd_native_version}.tar.gz
  CMAKE_CACHE_ARGS -DCMAKE_PREFIX_PATH:STRING=${Python_home}
  CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
             -DENABLE_PERL=FALSE
             -DENABLE_FUSE=FALSE
             -DENABLE_CRYPTO=TRUE
             -DENABLE_KRB5=TRUE
             -DENABLE_READLINE=TRUE
  DEPENDS Python
)
```

**Comment by abh3** [comment]
Hi Pere,

What I meant was the default options that are enabled in gcc 7.1 are pedantic like -Werror=format-truncation. Now, that said, I checked and found that all these issues were fixed in 4.6.0 (you are using 4.5.0 with gcc 7.1). I would recommend switching to 4.6.1 which is the latest release and is the best one we have.

Andy

**Comment by peremato** [comment]
Thanks I try to use the newest version.

**Comment by abh3** [comment]
Looks like this one was addressed.
