### ISSUE TITLE
Warnings/errors from -Woverloaded-virtual

### ISSUE THREAD

**Issue by gganis** [xrootd/xrootd#517]
ROOT builtin XRootD builds fail because of the attached errors (obtained on Ubuntu 16.04) generated by the -Woverloaded-virtual CXX flag added by ROOT build infrastructure. 

Should this flag added by default on XRootD builds?

[XROOTD-build-err.txt](https://github.com/xrootd/xrootd/files/1003706/XROOTD-build-err.txt)

**Comment by abh3** [comment]
Hi Gerri,

I am aware of this issue. We could do that. However, the more appropriate solution is to add “using” statements to the derived class. I wouldn’t mind but I do have an Ubuntu 17.02 system available. What compiler version are you using?

Andy 

From: Gerardo GANIS 
Sent: Tuesday, May 16, 2017 1:42 AM
To: xrootd/xrootd 
Cc: Subscribed 
Subject: [xrootd/xrootd] Warnings/errors from -Woverloaded-virtual (#517)

ROOT builtin XRootD builds fail because of the attached errors (obtained on Ubuntu 16.04) generated by the -Woverloaded-virtual CXX flag added by ROOT build infrastructure.

Should this flag added by default on XRootD builds?

XROOTD-build-err.txt

**Comment by gganis** [comment]
Thanks Andy!
The problem was reported by Axel using, I believe, the default compiler on Ubuntu 16.04, which is gcc 5.4.0 .
Gerri
