### ISSUE TITLE
[SSI] Metadata-only Responses have type isData

### ISSUE THREAD

**Issue by slithy** [xrootd/xrootd#546]
As I understand the comments in the code, Metadata-only Responses should have type isNone, but instead they have type isData.

To reproduce:

On the server side, call XrdSsiResponder::SetNilResponse().

On the client side, in XrdSsiRequest::ProcessResponse(), rInfo.State() evaluates to "isData" (albeit with a size of zero).

**Comment by abh3** [comment]
Unfortunately, I don't think anything can be done about this. As you surmised, the response length is zero to indicate that there is no data (i.e. a null response). The isNone setting is used to indicate that no response at all was posted and really can't do double duty in this case. A zero-length data response is perfectly legitimate.

**Comment by slithy** [comment]
In this case, I don't understand the purpose of isNone. If there is an error, the response type will be isError, and if there is a metadata-only response, the response type will be isData. If there is no response at all then the callback won't be called.

Do you mean that isNone is used internally by the framework and is not intended to be used by the application? If that is the case you should not expose it as part of the API.

**Comment by xrootd-dev** [comment]
Well, that's sort of the issue here. You can't see "isNone" becase the 
response becomes visible only when a response is posted which 
automatically changes isNone to something else. Yes, if you look with a 
debugger you'll see isNone and I think the issue here is that conceptually 
you would think that is should be isNone becuase you see it listd in the 
enum. But, prgramatically, the enum should define a "none of the below" 
value. So, I don't see the issue other than maybe a better comment or two.

Andy

**Comment by slithy** [comment]
OK, then the documentation is misleading. The SSI documentation (p.22) says, "A metadata-only response is indicated when XrdSsiRespInfo::rType is set to isNil (i.e. no response data is present)." isNil is not defined in the enum. When I looked at the headers, I found isNone, and assumed that was what was meant.

IMHO, a good API design should not expose implementation details as it can lead to unintended dependencies. It would be better to use a private member variable to store whether a Response has been received. You already have isError for invalid responses. But at the very least you could change isNone to something less confusing, like isInvalid.

Also, is there any way to tell whether a message is metadata-only, besides calling GetResponseData()? The documentation implies that there should be. I would like to avoid allocating a buffer to receive the response in the case where there is no response data.

**Comment by abh3** [comment]
Yes, the documentation is wrong. It was written before the implementation and, unfortunately, the implementation took a different path. We try hard to avoid that mistake but it does happen. We have to options (pick one considering the side-effects):
1) We correct the documentation. This is the easiest route as it does not change any code.
2) We change the code to correspond to the docs by adding an isNil response type. Not a big change and I doubt anyone will notice but it does mean anyone who is banking on isData for a null response detection will be unpleasantly surprised as this is an ABI breaker. Though we haven't yet put this in the public sphere.
so?

In this particular case I really have to disagree with you. isNone is a valid enum that you can use for any purpose you want and should not be concerned how it is used by the implementation because, frankly, your code is never exposed to it.

The last item confuses me. Where are you calling GetMetadata() from? I would hope from the ProcessResponse() callback because otherwise the return results are not guaranteed to be timely. If you call it from ProcessResponse() then you already have what the response will look like via the passed response info structure.

**Comment by slithy** [comment]
Yes, I am calling GetMetadata() from inside the ProcessResponse() callback.

I had understood from the docs that there was a distinction between a metadata-only response and a data response with length zero, but I see now that there is no such distinction. From looking at the header files I see it is possible to detect a metadata-only response by inspecting the rInfo::mdlen and rInfo::blen member variables.

The documentation should be updated to accurately describe this. The isNone enum value should be documented to make it clear that this value will never be seen in the callback.

**Comment by slithy** [comment]
After this discussion, I understand that a data response consists of exactly one metadata part (which can be of length zero) and exactly one data part (which can be of length zero). This was not clear from the documentation.

**Comment by xrootd-dev** [comment]
Agreed. One of the main reasons metadata responses were added was to make 
it more efficient to process certain serialization schemes. For instance 
Cap'n Proto, the follow-on to protocol buffers and the one many people say 
should be used. If you can provide layout information in the data packet 
(something none of the serializers allow but especialy relevant for Cap'n 
Proto) you can really optimize how you handle buffers. So, metadata 
responses are really limited to certain use cases.

Andy

**Comment by abh3** [comment]
Oh yes, I'm still waiting on your prefeed solution to the "isNil" issue 
:-)

Andy

**Comment by slithy** [comment]
I don't think we need isNil. My preferred solution would be to add a couple of methods that the application can use to determine how to process the response, e.g.:

bool XrdSsiRespInfo::hasMetadata() { return mdlen > 0; }
bool XrdSsiRespInfo::hasData() { return blen > 0; }
