### ISSUE TITLE
authdb parsing (or documentation) broken

### ISSUE THREAD

**Issue by olifre** [xrootd/xrootd#575]
Using xrootd 4.7.0, I followed the documentation ( see http://xrootd.org/doc/dev47/sec_config.htm#_Toc489606600 ) and wrote in my authdb-file:
```
= atlddm o atlas r production u ddm
= atlprod o atlas r production
```
However, on startup of xrootd I get:
```
170904 12:27:37 18899 acc_AuthFile: Invalid ID sprecifier - o
170904 12:27:37 18899 acc_ConfigXeq: No id selectors specified for atlddm
170904 12:27:37 18899 acc_AuthFile: Invalid ID sprecifier - o
170904 12:27:37 18899 acc_ConfigXeq: No id selectors specified for atlprod
```
Apart from the typo (`sprecifier`) it seems `o` is not understood as `idspec` as of yet?

**Comment by simonmichal** [comment]
Hi,

Thanks for reporting this problem.

After looking into the source code:
https://github.com/xrootd/xrootd/blob/master/src/XrdAcc/XrdAccAuthFile.cc#L162
it seems to me that a colon is expected after the ID specifier.
So something like:

= atlddm o: atlas r: production u: ddm
= atlprod o: atlas r: production

should work.

Though, it's not clear for me whether this was an intentional change in the authdb format or no.
We will have to wait for Andy to figure out.

Cheers,
Michal

**Comment by olifre** [comment]
Hi, 

many thanks for your reply! Yes, indeed: I can confirm that after adding the colons, things work fine! 
So let's wait for Andy to figure out whether this was intended (and documentation needs updating) or unintended (and code needs fixing). 

Cheers and many thanks, 
Oliver

**Comment by abh3** [comment]
I’d say the documentation is wrong. That’s easier to fix than the code at this point

**Comment by abh3** [comment]
I changed the documentation.
