### ISSUE TITLE
SSS key numbers should not increment based on the pre-existence of different named keys in the SSS keytab file

### ISSUE THREAD

**Issue by murrayc3** [xrootd/xrootd#590]
Each SSS key has a number which (please correct me if I am wrong) represents the version number of the key.  This said, adding three differently named keys to a keytab file should result in all of them being version 1.  This however is not the case.  The version number of a newly added uniquely named key is dependent on the version numbers of the keys already existing in the SSS keytab file.
```
[itdssbuild01] sss > echo y | xrdsssadmin -k key1 -u key1_user -g key1_group add allkeys.sss.keytab; xrdsssadmin -k key2 -u key2_user -g key2_group add allkeys.sss.keytab; xrdsssadmin -k key3 -u key3_user -g key3_group add allkeys.sss.keytab
xrdsssadmin: Keyfile 'allkeys.sss.keytab' does not exist. Create it? (y | n): xrdsssadmin: 1 key out of 1 kept (0 expired).
xrdsssadmin: 2 keys out of 2 kept (0 expired).
xrdsssadmin: 3 keys out of 3 kept (0 expired).
[itdssbuild01] sss > xrdsssadmin list allkeys.sss.keytab
     Number Len Date/Time Created Expires  Keyname User & Group
     ------ --- --------- ------- -------- -------
          1  32 09/25/17 18:56:45 -------- key1 key1_user key1_group
          2  32 09/25/17 18:56:45 -------- key2 key2_user key2_group
          3  32 09/25/17 18:56:45 -------- key3 key3_user key3_group
[itdssbuild01] sss >
```

The version number an SSS key should reflect its version and not the pre-existing contents of the keytab file it was added to.

**Comment by abh3** [comment]
Well, the key number is arbitrary. While it is more appealing to increment them within he same keyname, I don't see any advantage (other than aesthetics) in doing so. I do recognize that this also involves two other enhancements that have been posted. I think solving those would make this somewhat moot.

**Comment by abh3** [comment]
This has been fixed in R5 but likely not the way you wanted. The client will now report the keyname *and* keyid that it used and the server will then search for the matching combination in its keytab. Mind you you have to select that option in the server-side config file using the --keyname option. We needed to do that because some sites came up with creative solutions so that the new way of resolving keyids might not work as expected. Yeah, it sort of sucks but backward compatibility, even when bad, is still the king.
