### ISSUE TITLE
Docker container needed

### ISSUE THREAD

**Issue by ivukotic** [xrootd/xrootd#635]
Hi,

While there is already one docker hub container out there (https://hub.docker.com/r/lnielsen/xrootd/builds/), it would be nice to have an official one automatically built and correctly tagged. 

Ilija

**Comment by wyang007** [comment]
HI Ilija,

to clarify, do you want us to provide a docker image? or docker file (which will be used to build image)?

regards,

--

Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338(O)

**Comment by sjha2048** [comment]
Hi @simonmichal , I would like to take up this issue, can I work on it?

**Comment by simonmichal** [comment]
@sjha2048 : certainly, you are more than welcome to do so :-)

**Comment by sjha2048** [comment]
hello @simonmichal , I was trying to build xrootd from source on ubuntu 18.04 
I am kind of stuck.
here are the build logs:
I] Determining version from git
[I] src/XrdVersion.hh successfully generated
[  0%] Built target XrdVersion.hh
[ 21%] Built target XrdUtils
[ 38%] Built target XrdServer
[ 39%] Built target XrdHttpUtils
[ 41%] Built target XrdHttpTPC-5
[ 41%] Built target XrdHttp-5
[ 43%] Built target XrdXml
[ 52%] Built target XrdCl
[ 53%] Linking CXX executable xrdpfc_print
XrdCl/libXrdCl.so.2.0.0: undefined reference to `uuid_unparse'
XrdCl/libXrdCl.so.2.0.0: undefined reference to `uuid_generate'
collect2: error: ld returned 1 exit status
src/CMakeFiles/xrdpfc_print.dir/build.make:123: recipe for target 'src/xrdpfc_print' failed
make[2]: *** [src/xrdpfc_print] Error 1
CMakeFiles/Makefile2:385: recipe for target 'src/CMakeFiles/xrdpfc_print.dir/all' failed
make[1]: *** [src/CMakeFiles/xrdpfc_print.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2


Instead of building xrootd in the dockerfile from scratch can I fetch the rpm?

**Comment by simonmichal** [comment]
@sjha2048 : have a look at our CI build script for Debian/ubuntu: https://github.com/xrootd/xrootd/blob/master/.gitlab-ci.yml#L12-L28
you can also find rebuild deb packages at: http://storage-ci.web.cern.ch/storage-ci/debian/xrootd/

**Comment by abh3** [comment]
I'm going to close this as the community stepped up and is now providing containers as needed.
