### ISSUE TITLE
Force permissions on files created by a xrootd server

### ISSUE THREAD

**Issue by jknedlik** [xrootd/xrootd#649]
Hi,
At out site setup we need a specific feature. We want to enforce unix permissions( e.g. 664,600..,etc. ) to all files created by the xrootd data server.
I have not found a native way to do it so far in the configuration manual.
Of course, it is always possible to do so by changing them later on(with plug-ins for an example), but thats always a last resort.
Is there a native way to let xrootd enforce those permissions on files created?
Cheers,
Jan

**Comment by bbockelm** [comment]
Hi Jan,

Do you mean only unix permissions (e.g., all files created by Xrootd have permission 664) or permissions and ownership (e.g., all files created by Xrootd for Xrootd user `bbockelm` are written to the filesystem with UID corresponding to the Unix account `bbockelm`)?

Brian

**Comment by jknedlik** [comment]
Hi,
I mean only unix permissions.
We are fine with the user and already enforce a group(secondary group of the user running the server daemon) via the corresponding sticky bit.
All thats left is enforcing the "read" bit on "group" for all files.
Jan

**Comment by bbockelm** [comment]
Hm -- too bad, I already have a mechanism we use locally for doing multiple ownership that I could have shared.

For permissions - does setting the umask of the `xrootd` daemon process work?

**Comment by jknedlik** [comment]
AFAIK umask can only restrict the setting of permissions on new files, but not enforce them.

**Comment by bbockelm** [comment]
Ah - so you want to disallow Xrootd from exporting files to remote users that the `xrootd` Unix user account can otherwise read?

**Comment by jknedlik** [comment]
Quite the opposite.
External users can set permissions on files created at the data server, which we can see, since not all files created on our exported subdirectory for XRootD data have the same permissions.
We want to make them readable for one specific Unix group.
We can enforce that specific group by using the sticky bit on the exported subdirectory. But we also need to enforce the  group-"read" bit on all files created.

**Comment by olifre** [comment]
To add on this, we also need this - files created by xroot third-party-copy transfers are created with 600, i.e. they will only be readable by the user running xrootd by default, and nobody else can read them from our local shared filesystem. 
So a native solution would be very helpful. 
I'm also grateful for an existing "plugin solution", if something like this already exists. Otherwise, we'd have to recursively transverse the filesystem regularly, which is rather expensive... 

And we'd also have a usecase for the solution pointed out by @bbockelm for local multiple ownership. Is this also a plugin you are using?

**Comment by wyang007** [comment]
Hi Brian, where is that plugin?

--
Wei Yang  |  yangw@slac.stanford.edu  |  650-926-3338(O)

?-----Original Message-----

**Comment by abh3** [comment]
For third party copy you specify what runs to perform this. It can be a script that wraps xrdcp. Then you can set permissions any way you want. I do agree that it would be nice to have this integrated so a script would not be needed.

**Comment by olifre** [comment]
> For third party copy you specify what runs to perform this. It can be a script that wraps xrdcp. Then you can set permissions any way you want. I do agree that it would be nice to have this integrated so a script would not be needed.

Good idea! Yes, indeed I already use a script wrapping xrdcp to keep an updated VOMS proxy certificate ready to allow for Grid transfers (GSI auth). So adding permission setting there for the meantime is a good idea. Thanks!

**Comment by olifre** [comment]
Another point I just noted: The script-wrapper-apprach of course does not work for WebDAV copies :-(.

**Comment by abh3** [comment]
Yes, I'm not sure that WedDav uses the standard tpc path which, of course, 
would never execute your script.

Andy

**Comment by olifre** [comment]
Hi,

are there ideas on how to approach this? A common solution (or at least a solution with feature-parity) for WebDAV and xrootd TPC to hook up scripts would be really nice. Right now, we scan our filesystem for about one hour each day to fixup permissions. 

Cheers,
Oliver

**Comment by abh3** [comment]
Hi Oliver,

Perhaps I don’t understand the full problem. For XRootD TPC you already have the capability to hookup a script and set whatever permission you would like (presumably ones that still allow xrootd to access the file). For all other operations, you have the capability of adding an event stream script that could selectively notified of file creations and other operations that are permission sensitive and do whatever you need to do in that script.

Andy

**Comment by olifre** [comment]
Dear Andy,

I was mistakenly believing only `ofs.tpc` allowed hookup of a script. My conclusion was there is no way to hook up a "permission change script" to anything transferred via WebDAV. 
However - I was fully unaware of the event stream script approach (you mean `ofs.notify`, correct?). This should indeed solve my issue, and opens up a full range of other possible hooks! 

It would of course still be nice to have a way to enforce permissions / an umask in a general way without an external script, but as long as that is a possible workaround, I am happy :-). 

So many thanks for mentioning `ofs.notify`! 

Cheers,
Oliver

**Comment by abh3** [comment]
Hi Oliver,

Yes, ofs.notify is the one. Could you (and you may already have so apologies for the repeat) supply the actual requirements for the permission settings? Does the user or path alter the permission settings? Anything else or is one set of permission be sufficient. How does this impact chmod? If permission are path sensitive how does this impact rename?

Andy

**Comment by olifre** [comment]
Hi Andy,

indeed I did not yet provide what we actually want ;-). 
Right now, we actually just do a `chmod 755` on all directories, and a `chmod 644` on all files created by xrootd, to allow users to read the files directory from the POSIX filesystem. 

However, once there are improvements to our identity management system, we would like to use one of the following two solutions:
- add ACLs granting a group access to the files and directories created by xrootd
- use chown to give the files to a group (to which xrootd belongs), i.e. "the classic way"

Since ACLs are probably out of scope in any general solution (there is not even a common solution amongst all filesystems), I think the only things a general solution could provide are: 
1. Specify default mode for directories and files created by xrootd (755, 644 or whatever a user needs)
2. Specify owner / group the created files / directories should belong to. 

Of course, for 2 the administrator has to take care that xrootd itself can still access the files. 

Does that sound reasonable? 

Cheers,
Oliver

**Comment by xrootd-dev** [comment]
Hi Oliver,

Indeed it does sound reasonable. The uncertainty means that we would like use a plug-in model with a pre-post hooks across file system operations. That also fits nicely with or other effort to track user ownership via uid/gid, as this would also use the same plugin model. We could supply a default one that can be statically configured for one set of permissions (i.e. file and dir). Beyond that, you would need to write one that meets your specific needs. Sound reasonable?

Andy

**Comment by abh3** [comment]
This enhancement is scheduled to appear in 5.6.0.

**Comment by amadio** [comment]
Implemented in 8a6d7c09642db4465a3e0dfee47b9dfe0357fceb.
