### ISSUE TITLE
PSS with disk cache enabled doesn't update files changing in the backend

### ISSUE THREAD

**Issue by apeters1971** [xrootd/xrootd#668]
Once a file is cached in xCache, the local copy is never updated even if the inode, size or modification time in the backend has changed. That is very unfortunate. Can this trivial cache eviction policy be added?

**Comment by wyang007** [comment]
This is known. We had a light discussion of whether we should do this. For experiment data we should not. But for general purpose cache it seems this is a legitimate request. I think we need to understand how costly it is.

I am copying this to xcache-l@slac.stanford.edu. It is a mailing list dedicated for Xcache and is open for everyone to subscribe. So far it has zero traffic (and spam).

regards,

--

Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338(O)

**Comment by xrootd-dev** [comment]
On 03/14/18 09:11, Wei Yang wrote:
> This is known. We had a light discussion of whether we should do this. For 
> experiment data we should not. But for general purpose cache it seems this is a 
> legitimate request. I think we need to understand how costly it is.

Ah, I didn't know this was being discussed :)

And yes, once the cache has a file (even if incomplete) it will not even open 
the remote connection until it needs to get a block outside of what it already 
has. This is intentional and improves file-open performance and resilience for 
read-only data.

So, clearly we need an option to force checking if a remote file has changed on 
open ... or even have a plugin that can make this decision based on filename.

However, we are opening a can of worms here ... what if the file changes while 
it is being read? There is no way for the cache to detected that unless the 
server sends out notifications of all writes it has received.

Matevz

**Comment by abh3** [comment]
Correct. The XrootD Xcache assume read-only file. If you want that kind of flexibility then you need to use XcacheH (though only HTTP access is available). This has to to do with semantics. In the XRootD world, caching of files that change makes no sense. That is not true if the HTTP world. So, if you need that kind of flexibility, use XcacheH.
