### ISSUE TITLE
xrdfs 4.8.2 authorization problem

### ISSUE THREAD

**Issue by ghost** [xrootd/xrootd#687]
xrdfs 4.8.2 removes files even when security is in place. Tested with sec.protocol unix and sss.
No feedbacks in the logs of data server. Access is logged on redirector only.
Expected behaviour would be that xrdfs does not rm file when not permitted in Authfile.

Is this a bug or misconfiguration ?

Authfile:
u *    /xrootd lr
u root /xrootd lr
u schroete /xrootd/myTestDir a

Copy a file as user schroete:
~# XrdSecDEBUG=1 xrdcp Adapter_28022018.tgz root://glogin1//xrootd/myTestDir/test.dat
sec_Client: protocol request for host 192.168.16.122 token='&P=unix'
sec_PM: Loaded unix protocol object from libXrdSecunix.so
sec_PM: Using unix protocol, args=''
[45.08MB/45.08MB][100%][==================][45.08MB/s]

Remove file as schroete2,root or any other user on that client machine:
(Also it looks that the user name is truncated to 8 chars)
~# xrdfs glogin1 rm /xrootd/myTestDir/test.dat

Log Entry Data Server:
180413 12:52:50 1243 XrdInet: Accepted connection from 7@qc01.iup.uni-bremen.de
180413 12:52:50 1243 XrdProtocol: matched protocol xrootd
180413 12:52:50 1243 ?:7@qc01 XrdPoll: FD 7 attached to poller 0; num=1
180413 12:52:50 1245 XrdSched: running main accept inq=0
180413 12:52:50 1243 ?:7@qc01 XrootdProtocol: 0000 req=login dlen=97
180413 12:52:50 1243 schroete.22072:7@qc01 XrootdResponse: 0000 sending 16 data bytes
180413 12:52:50 1243 XrootdXeq: schroete.22072:7@qc01 pvt IPv4 login
180413 12:52:50 1243 schroete.22072:7@qc01 XrootdProtocol: 0100 req=rm dlen=26
180413 12:52:50 1243 schroete.22072:7@qc01 ofs_remove: f fn=/xrootd/myTestDir/test.dat
180413 12:52:50 1243 schroete.22072:7@qc01 XrootdProtocol: 0100 rc=0 rm /xrootd/myTestDir/test.dat
180413 12:52:50 1243 schroete.22072:7@qc01 XrootdResponse: 0100 sending OK
180413 12:52:50 1243 XrootdXeq: schroete.22072:7@qc01 disc 0:00:00
180413 12:52:50 1243 schroete.22072:7@qc01 XrdPoll: FD 7 detached from poller 0; num=0

xrootd.cf:
xrd.timeout hail 30 idle 0 kill 3 read 5
all.export /xrootd
set xrdr=glogin1.iup.uni-bremen.de
set inventory=/var/log/xrootd/inventory
all.manager $(xrdr):3121
cms.allow host *.iup.uni-bremen.de
if $(xrdr) && named cns
      all.export $(inventory)
      xrd.port 1095
else if $(xrdr)
      all.role manager
      oss.defaults rw
      xrd.port 1094
else
      all.role server
      ofs.notify closew create mkdir mv rm rmdir trunc | /usr/bin/XrdCnsd -d -D 2 -i 90 -b $(xrdr):1095:$(inventory)
      ofs.notifymsg create $TID create $FMODE $LFN?$CGI
      ofs.notifymsg closew $TID closew $LFN $FSIZE
      xrootd.seclib /usr/lib/libXrdSec.so
      sec.protocol unix
      acc.authdb /etc/xrootd/Authfile
      acc.authrefresh 60
      ofs.authorize
      cms.space min 100g 110g
fi

**Comment by hds1** [comment]
just experimented a bit more. The issue seems to be that the redirector also needs the Authentication settings. So it looks that xrdcp exchanges auth with the data servers, whereas xrdfs exchanges it with the redirector.
With the xrootd.cf below it works as expected (probably the auth section within the data.server role could be removed then)
This is reproducable. When deleting the global auth settings the "rm" is possible again for all users.

xrootd.cf:
xrd.timeout hail 30 idle 0 kill 3 read 5
all.export /xrootd
set xrdr=REDIRECTOR
set inventory=/var/log/xrootd/inventory
all.manager $(xrdr):3121
cms.allow host *.iup.uni-bremen.de

xrootd.seclib /usr/lib/libXrdSec.so
sec.protocol  unix
acc.authdb /etc/xrootd/Authfile
acc.authrefresh 60
ofs.authorize

if $(xrdr) && named cns
      all.export $(inventory)
      xrd.port 1095
else if $(xrdr)
      all.role manager
      oss.defaults rw
      ofs.forward all
      xrd.port 1094
else
      all.role server
      ofs.notify closew create mkdir mv rm rmdir trunc | /usr/bin/XrdCnsd -d -D 2 -i 90 -b $(xrdr):1095:$(inventory)
      ofs.notifymsg create $TID create $FMODE $LFN?$CGI
      ofs.notifymsg closew $TID closew $LFN $FSIZE

       xrootd.seclib /usr/lib/libXrdSec.so
       sec.protocol  unix
       acc.authdb /etc/xrootd/Authfile
       acc.authrefresh 60
       ofs.authorize
fi

**Comment by hds1** [comment]
Sorry, didn't answer your question. You can use any user account. Tried also with totally different names. The error is consistend when only the data servers get the authentication settings configuration

**Comment by wyang007** [comment]
It has been a long time when I put this thing out – hopefully I still remembers this.

I think the issue may be related to the use of "ofs.forward all”. it was there to ensure that the deletion request are “broadcast” from the redirector to all data servers (for example, a directory may exist on several data servers. Without this forwarding, old xrd and early versions of xrdfs will only delete the directory on one of them). So your xrdfs didn’t actually talk to the data servers, but only to the redirector. This may explain all the things you saw. 

One way to verify is the use xrdfs to delete a file that doesn’t exist in your cluster. Xrdfs may not give your an error because of the broadcasting. 

regards,
--
Wei Yang  |  yangw@slac.stanford.edu  |  650-926-3338(O)

**Comment by hds1** [comment]
You are right. It is down to the "ofs.forward" directive. FWIW i do use the following xrootd.cf with inventory and userbased access limit. Writing over FUSE mount is not possible. So pretty much the scenario we need.

xrootd.cf:
```bash
xrd.timeout hail 30 idle 0 kill 3 read 5
all.export /xrootd
set xrdr=REDIRECTOR
set inventory=/var/log/xrootd/inventory
all.manager $(xrdr):3121
cms.allow host *.local.domain
if $(xrdr) && named cns
      all.export $(inventory)
      xrd.port 1095
else if $(xrdr)
      all.role manager
      oss.defaults rw
      # dont use ofs.forward 14.4.2018
      xrd.port 1094
else
      all.role server
      ofs.notify closew create mkdir mv rm rmdir trunc | /usr/bin/XrdCnsd -d -D 2 -i 90 -b $(xrdr):1095:$(inventory)
      ofs.notifymsg create $TID create $FMODE $LFN?$CGI
      ofs.notifymsg closew $TID closew $LFN $FSIZE
      xrootd.seclib /usr/lib/libXrdSec.so
      sec.protocol  unix
      acc.authdb /etc/xrootd/Authfile
      acc.authrefresh 60
      ofs.authorize
      cms.space min 100g 110g
fi
```

**Comment by simonmichal** [comment]
It looks to me this issue has been resolved, can we close it?

Michal
