### ISSUE TITLE
bad calculation in CacheInfo files

### ISSUE THREAD

**Issue by ivukotic** [xrootd/xrootd#697]
xrdpfc_print gives for a file that was accessed twice (and each time read in completely):

version 2, created Mon Apr 30 17:02:29 2018
fileSize 7963383745, bufferSize 1048576 nBlocks 7595 nDownloaded 7595 complete
access 0: Mon Apr 30 17:02:29 2018, duration 00:01:56, bytesDisk=1787271105, bytesRAM=6176112640, bytesMissed=0
access 1: Mon Apr 30 17:05:59 2018, duration 00:01:08, bytesDisk=7962597313, bytesRAM=0, bytesMissed=0
access 2: Mon Apr 30 20:04:40 2018, duration 00:01:08, bytesDisk=7962335169, bytesRAM=0, bytesMissed=0
access 3: Mon Apr 30 20:05:49 2018, duration 00:01:08, bytesDisk=7962859457, bytesRAM=0, bytesMissed=0

problem is that the second access shows bytesDisk to be smaller than filesize. At first access, sum of bytesDisk and bytesRAM does give exact fileSize.

**Comment by osschar** [comment]
Interesting :)

Are you sure the clients closed the connections? cinfo file is updated periodically, only. What were you doing, xrdcp?

Perhaps a relevant observation:
(7963383745 - 7962597313) / 1024 = 768.00
(7963383745 - 7962335169) / 1024 = 1024.00
(7963383745 - 7962859457) / 1024 = 512.00

I'll check the code to make sure we don't miss anything before the final writeout of cinfo.

**Comment by ivukotic** [comment]
Yes, a simple xrdcp.each time it finished OK. Each time different result. Cinfo file is correctly read.
Ilija
________________________________

**Comment by osschar** [comment]
I have easily reproduced this :) and will try to fix it soon. I suspect there is an issue with locking of access to the stats object. I might change the stats to use atomics, will have to review the flow.

Thanks for reporting this!

**Comment by ivukotic** [comment]
Hi,

one more question - in details of reported access, when is the "detached_at" updated? What happens during the access? 

Ilija

**Comment by osschar** [comment]
It is updated when the file is closed.

During access the cinfo file is only updated if new blocks are coming in from the remote and are being written to disk. I think a sync is scheduled once every 100 blocks are written. Yes, and that happens after the data file fd is flushed (to assure consistency of data file and what proxy believes to be a set of already downloaded blocks).

[Since I went through the code -- there is undocumented pfc.flush N_blocks directive to set how often the flush happens.]
