### ISSUE TITLE
specs: cpsize and cptype fields lack some documentation

### ISSUE THREAD

**Issue by EgorMatirov** [xrootd/xrootd#724]
[Specs](http://xrootd.org/doc/dev45/XRdv310.htm#_Toc464248823) do not clarify what's the unit of the size and how type is defined (is it the name of the compression algorithm like `deflate` or `lz4`?). 

As far as I got, compressed files are not commonly used in XRootD, however, I'm working on [the XRootD protocol implementation in Go language](https://github.com/go-hep/hep/tree/master/xrootd) and would like to clarify these details in doc string if they are available.

**Comment by abh3** [comment]
Hi Mikhail,

Yes, the specs are fuzzy on this as we used to have an implementation in the forerunner to XRootD but it never got ported across. So, the specs remained fuzzy simply because we had no reason to flesh them out. I suppose, for now, never specify kXR_compress and your implementation should be safe. In the mean time, I will put compression elaboration on the list. Notethat cptype is a four byte field and if it’s null terminated (not clear it is – I have to look deeper) that leave only three characters for compression type. In any case, the idea was it was going to be like “lz4”.
Andy 
From: Mikhail Ivchenko 
Sent: Tuesday, June 05, 2018 9:06 AM
To: xrootd/xrootd 
Cc: Subscribed 
Subject: [xrootd/xrootd] specs: cpsize and cptype fields lack some documentation (#724)

Specs do not clarify what's the unit of the size and how type is defined (is it the name of the compression algorithm like deflate or lz4?).

As far as I got, compressed files are not commonly used in XRootD, however, I'm working on the XRootD protocol implementation in Go language and would like to clarify these details in doc string if they are available.

**Comment by bbockelm** [comment]
Is the idea to match what ROOT does?  If so, they have a three-byte header to specify a compression algorithm and then use the unframed version of the compression algorithm.

**Comment by abh3** [comment]
Maybe, it’s hard to tell. That part of the code has been unused for over 15 years! I need to look back in the archives.

**Comment by abh3** [comment]
I have removed the ambiguities from the kXR_open request description in v4 of the protocol documentation.

**Comment by sbinet** [comment]
thanks.

AFAICT, http://xrootd.org/doc/dev49/XRdv400.htm#_Toc517297859 doesn't document what's the expected unit for `cpsize`:
```
cpsize   is the compression page size. 
```

are those `bytes`? `kB`? `MB`? units of `_SC_PAGESIZE` ?
