### ISSUE TITLE
[SSI] Memory leak when client loses connection to server

### ISSUE THREAD

**Issue by slithy** [xrootd/xrootd#775]
When the XRootD server is restarted, the client is no longer able to use the connection, responding with `[ERROR] Invalid session`. In this case, I want to establish a new connection and delete the old one.

The only way to delete the XrdSsiServReal object is to call the Stop() method, but this only works if `actvSes == false` and there is no way for the client to ensure this condition. Sessions can only be recycled by calling `XrdSsiServReal::Recycle(XrdSsiSessReal *sObj, bool reuse)`, but the `XrdSsiSessReal *` is not exposed to the client.

This means that every time the client reconnects to the server, the old server object cannot be removed from memory and hangs around indefinitely.

The client needs a way to force the XrdSsiServReal object to clean up all its data structures and delete itself.

**Comment by abh3** [comment]
OK, it should not be necessary to create a new service object. The old IP address associated with the service is still valid. The current connection is not. However, the client should reconnect when another request is issued using the service object. So, why is it that you are creating a new service object just because you got an error?

**Comment by slithy** [comment]
I did this because of issue #776. The client can reconnect, eventually, but there is a 60s period after the server comes back online during which it cannot reconnect. There is no way to test the status of the connection during this period.

We are processing requests at around 100 Hz, so we end up with thousands of requests stuck and eventually timing out. To better handle this case, I invalidate the session and pass back an immediate error to incoming requests, until a new session can be successfully established.

**Comment by abh3** [comment]
Hi Michael,

So, could you simply adjust XRD_CONNECTIONWINDOW to be something less than 
the default 60 seconds? Say, 1 or 2 seconds?

Andy

**Comment by slithy** [comment]
This has to be solved in a way that does not require setting environment variables.

**Comment by slithy** [comment]
There is no destructor for the Service method, but you provide a method `XrdSsiServReal::Stop()`. However this method will always return false as there is no way to call `Recycle()` on the session.

This seems like a partially-implemented solution. What is the purpose of the `Stop()` method if it's actually not possible to terminate the session?

**Comment by abh3** [comment]
Just checking back if the suggestion of setting lower timeouts worked for you.

As for Stop(), the docs explicitly say that Stop() is ineffective if there are active requests. You need to call Finished() for each such request and then do a Stop(). SSI employs a Java-like system by keeping reference counts to all objects and an object can't get deleted if its reference count is not zero for obvious reasons. A false return from Stop() simply is saying there are still outstanding references to the object. I suppose we could mark it for deletion but that would be hiding reality as the object might never get deleted. Unbeknownst to you, Java happily hides deletion from you and objects continue to occupy memory but you aren't told that's the case. SSI Stop() at least tells you what you think is going to happen won't be the case.

Now, I do recognize that under the circumstances it would take a long time for things to clean themselves out and we are looking at speeding it along by using a new client feature to forcibly terminate requests in such circumstances. Even then, someone has to call Finished() in the end to unhook the reference. However, setting the connection timeout to a lower value should also speed things along and may be sufficient for now until we get a faster system in place.

**Comment by slithy** [comment]
On the suggestion of setting of lower timeouts: the XRD_CONNECTIONWINDOW setting is controlling two separate things: (1) the amount of time taken to establish a connection, and (2) the amount of time to wait after a failure before attempting to reestablish a connection. We don't want to set these things to the same value. I discussed with Michal and he is taking a look to see if he can come up with a better solution.

On `Stop()`, it is not possible to call `Finished()` on each request because the active requests are not exposed through the API. Ownership is passed to the framework when we call ProcessRequest(), but then there is no way to get back a list of in-flight requests or query which requests have or have not been processed. You need to provide a way for the user of the framework to cancel in-flight requests.

In any case, I don't think that this is the problem in our test case. It is not active **Requests** which are blocking `Stop()` in this case, but active **Sessions**. The private method `XrdSsiServReal::Recycle` decrements `actvSes`, which would allow `Stop()` to work, but again this is not exposed through the API. So even if there are no active requests, an active session will prevent deletion of the service object.

**Comment by abh3** [comment]
Ah, for Stop() not so! Reference counts are transitive. If A references B and B references C then C's reference count can't be decremented until the reference to B is reduced to zero. Simply replace A with request, B with session, and C with service. This is an n to m to 1 mapping. It  works that way in every reference counting system.

SSI really can't give you a representative snapshot of requests because whatever it would give you would be potentially incorrect. Why? There are non-SSI threads that may change the state of a request at any point. Only the application knows the actual state because it knows the meta-state. SSI only knows the current transitory state and by the time it reports it to you that state may have changed. That's why SSI can't do it. It's really the application that is in control here.

This issue arises because, unlike most RPC-type system (think NFS, AFS, or even hitting the X button on your browser), SSI allows you to asynchronously cancel a request at any point. This was an imperative from LSST to solve the control-C problem (I launch a request and then change my mind). A request had to be cancelled immediately no matter what. That necessarily shifted the burden of keeping track of requests to the application layer (easily done using std::set).

**Comment by abh3** [comment]
OK, I reread your post. If indeed, there are no active requests then the issue is that there are reusable session that are preventing the Stop() from happening. I can solve that one.

**Comment by slithy** [comment]
Yes, I think that is the problem in this case.

**Comment by abh3** [comment]
OK, did a deep dive and unfortunately that's not the problem. When a shared resource goes idle it makes sure to unhook itself from the service object (i.e. it's reference count goes down). So it's really that there are hung requests out there. Back to the more difficult road, sigh.

**Comment by abh3** [comment]
OK, I'm found the edge case that causes this problem. The patch I will be posting should cleanup in the case of a communications failure. The interaction with Stop() is still somewhat in the air but, in general, you need not call it after a communications error occurs, assuming you wish to continue using the service at the end-point. In other words, calling ProcessRequest() after a failure will simply queue the requests until the server comes back up. All requests prior to the failure will be cleaned up and the original resource will be made non-reusable. In theory, you need not special case this particular error. That said, we shall know when this occurs in practice (my test show it works as expected).

**Comment by slithy** [comment]
I re-tested with version 4.8.5-0.experimental.490579.b490c5d6.

If I understood you correctly, after the patch it should not be necessary to recreate the client-side Service object?

Testing with the patch and without recreating the client-side Service object:

* If I stop the server and restart it immediately, the client gives **[ERROR] Invalid session** as before. However, it never reconnects.
* If I stop the server and do not restart it, the client gives **[ERROR] Invalid session** as before. Previously the client would subsequently give **[ERROR] Operation expired**, but now it does nothing.

So with this patch it is still necessary to recreate the Service object after a disconnection. Am I missing something?

**Comment by xrootd-dev** [comment]
Hi Michael,

Yes, in order to be able not to leak memory we can’t have clients hanging about for an indeterminate amount of time. That was essentially the problem before. So, now the such an error simply does a callback to ProcessResponse() You should be able to reissue the request using the same service object. When an error occurs the session object is immediately marked not reusable so that it will be deleted. Calling ProcessRequest() with the same resource name plus reuse attribute simply creates a new session and tries again. At this point, retry logic would kick in as the the target might not be accessible. Well, that’s the idea but I see that there is a client retry aberration in git head that I have to figure out first.

So, the answer is that you are responsible for retrying when ProcessResponse() is call with an error. You can ruse the same service (no need to reallocate). I will email you once I understand this strangeness in the client.

Andy

**Comment by xrootd-dev** [comment]
Hi Michael,

As an update, I finally narrowed down to what the problem is and it's a 
recovery issue in the basic client. That needs to get solved. We are 
working on getting the best solution here. We are also looking at the 
"invalid session" error -- it's understood but not in the way we like. 
However, the upshot is that once we get this straightened out, the service 
object need not be recreated. It will automatically sequence to a new 
connection on the next request. I also need to address the timeout issue 
because as it stands, the full timeout would apply as things stand and I'd 
like to get around that snit.

Andy

**Comment by slithy** [comment]
OK, thanks. I will wait for your next update.
