### ISSUE TITLE
query/opaque information on kXR_mv source path

### ISSUE THREAD

**Issue by paulmillar** [xrootd/xrootd#850]
We have observed kXR_mv requests with a source path like:

    //foo/my-file?xrd.gsiusrpxy=/opt/domatests/x509up&xrd.wantprot=gsi,unix

This kind of construction is allowed for [kXR_Open](http://xrootd.org/doc/dev49/XRdv400.htm#_Toc517297859), but not for [kXR_mv](http://xrootd.org/doc/dev49/XRdv400.htm#_Toc517297858).

However, such requests are succeeding when given to the SLAC xrootd server, with the server stripping off this opaque/query part and processing the kXR_mv request as if the source path has no query part.

Either the xrootd protocol allows the client to specify opaque/query part in the kXR_mv source path or it does not.

If the xrootd protocol allows an opaque part in the kXR_mv source path, could the protocol documentation be updated to reflect this?

If the xrootd protocol does not allow the kXR_mv source path to have an opaque part, could the xrootd clients be updated so they do not send it?

**Comment by xrootd-dev** [comment]
Hi Paul,

CGI elements are allows wherever a path is allowed, that include rename and the old name and new name can have cgi elements that differ. All that information is passed down to the file system layer. Now, XRootD doesn’t specifically support the anchor elements and if it exists, it does not get stripped. It’s up to the underlying file system to make heads or tails of the element. So, I suppose we just need a statement saying anywhere where a path exists may also include CGI elements. I though that was obvious but apparently it is not.

Andy

From: Paul Millar 
Sent: Friday, October 26, 2018 2:13 AM
To: xrootd/xrootd 
Cc: Subscribed 
Subject: [xrootd/xrootd] query/opaque information on kXR_mv source path (#850)

We have observed kXR_mv requests with a source path like:

//foo/my-file?xrd.gsiusrpxy=/opt/domatests/x509up&xrd.wantprot=gsi,unix
This kind of construction is allowed for kXR_Open, see:

http://xrootd.org/doc/dev49/XRdv400.htm#_Toc517297859
However, my reading of the kXR_mv suggests that this isn't allowed:

http://xrootd.org/doc/dev49/XRdv400.htm#_Toc517297858 
However, such requests are succeeding when given to the SLAC xrootd server, with the server stripping off this opaque/query part and processing the kXR_mv request as if the source path has no query part.

Either the xrootd protocol allows the client to specify opaque/query part in the kXR_mv source path or it does not.

If the xrootd protocol allows an opaque part in the kXR_mv source path, could the protocol documentation be updated to reflect this?

If the xrootd protocol does not allow the kXR_mv source path to have an opaque part, could the xrootd clients be updated so they do not send it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.



--------------------------------------------------------------------------------

Use REPLY-ALL to reply to list

To unsubscribe from the XROOTD-DEV list, click the following link:
https://listserv.slac.stanford.edu/cgi-bin/wa?SUBED1=XROOTD-DEV&A=1

**Comment by paulmillar** [comment]
Hi Andy,

Thanks for the clarification.

Yes, it would be helpful if there was something in the spec that says any path may include CGI elements.  For me, this wasn't obvious and I don't believe the current version of the spec says this anywhere.

If I may suggest, the section on kXR_open could also then be reworked slightly, to reference this ability.

In the mean time, we'll update xrootd4j to reflect this.

Cheers,
Paul.

**Comment by abh3** [comment]
Ah, this was added to the spec a few years back when describing client specified paths.
