### ISSUE TITLE
[XrdCl] retry policy changes

### ISSUE THREAD

**Issue by simonmichal** [xrootd/xrootd#950]
0. A virtual redirector (e.g. a metalink) should be treated as a meta-manager.

1. For meta-managers EACESS should be treated as a retriable error (the list of non-retriable errors should be reviewed because potentially there are others that could be retried in case of meta-managers).

2. In case a data server responds with a `kXR_redirect` and we fail at the node where we were redirected to, the original data server should be included in the `tried` and `triedrc` cgi.

**Comment by xrootd-dev** [comment]
Hi Michal,

Perfectly captures the issues at hand. Thanks!

Andy

From: simonmichal 
Sent: Thursday, March 28, 2019 8:32 AM
To: xrootd/xrootd 
Cc: Subscribed 
Subject: [xrootd/xrootd] [XrdCl] retry policy changes (#950)

  0.. A virtual redirector (e.g. a metalink) should be treated as a meta-manager.

  1.. For meta-managers EACESS should be treated as a retriable error (the list of non-retriable errors should be reviewed because potentially there are others that could be retried in case of meta-managers).

  2.. In case a data server responds with a kXR_redirect and we fail at the node where we were redirected to, the original data server should be included in the tried and triedrc cgi.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.



--------------------------------------------------------------------------------

Use REPLY-ALL to reply to list

To unsubscribe from the XROOTD-DEV list, click the following link:
https://listserv.slac.stanford.edu/cgi-bin/wa?SUBED1=XROOTD-DEV&A=1

**Comment by simonmichal** [comment]
It has been all implemented in 0bb70d3b7cd3310d6635fa98547f5e1b786d9d18

@abh3 : we still need to discuss whether we want to extend the list of retriable errors beyond EACESS for metamanagers.

**Comment by simonmichal** [comment]
After having a quick look at the possible error codes, my candidates for problems retriable at meta-managers are:
- `kXR_NoMemort`
- `kXR_NoSpace`
- `kXR_Unsupported`
- `kXR_overQuota`
- `kXR_Overloaded`

**Comment by xrootd-dev** [comment]
Correct, I will look hrough the errors again and make some suggestions. 
Feel free to disagree :-)

**Comment by wyang007** [comment]
I tried the two studying cases with githead (which has 0bb70d3). It looks promising. 

In the case where BNL dcdoor11 was the first URL in the metalink, xrdcp switches to the second URL after the first one run into permission deny error.

In the case where SFU is the the first URL in the metalink, the problem we used to have is the SFU front node direct us to the backend node which is not internet visible. However, the situation chanced. The file is no longer at SFU, so we are redirected upstream to atlas-fax-us.usatlas.bnl.gov (they still live in FAX age), and since there is no longer a DNS name, atlas-fax-us.usatlas.bnl.gov, it failed, and xrdcp moved to use the second URL in the metalink, which is good.

So I will need to find a file that exist at SFU and somewhere else, and try again.

**Comment by wyang007** [comment]
I put the file back to SFU and tried the case. It works - XrdCl was able to detect that the backend dCache node was not internet accessible, and still both the backend and frontend at SFU, and move to the next URL in the metalink.

**Comment by simonmichal** [comment]
I love good news :-)

**Comment by xrootd-dev** [comment]
Here is my list with the following caveat:

If the redirector is a meta-manager or is virtual (i.e. actually a 
metalink) then go back to the redirector and ask for a different server.
The "tried=" CGI value should indicate the hostname of the failing 
server. The kXR_refresh should not be turned on. For kXR_NotAuthorized, 
recovery should not be attempted more than three times in a row.

kXR_FileLocked
kXR_NotAuthorized
kXR_Unsupported

Comments on your candidates:

kXR_NoMemory and kXR_Overloaded are already noted as retriable in the 
protocol spec so simply make sure that they really are being retried.
See http://xrootd.org/doc/dev49/XRdv400.htm#_Toc532936559

kXR_NoSpace and kXR_overQuota should not be retried. These are connected 
to write requests and writes pin the client to a particular server so 
logically they cannot be retried (as per protocol spec). Furthermore, do 
you really want to leave file turds across the world?

Andy

**Comment by simonmichal** [comment]
@abh3 : 

- regarding `kXR_refresh`, just from curiosity, why  shouldn't it be set for metamanagers?

- regarding `kXR_NotAuthorized`, limiting the retries to 3 seems to me a very arbitrary choice ;-), I would rather make it configurable

- regarding `kXR_NoSpace` and `kXR_overQuota`, I thought those are returned in case of open request with `oss.asize` cgi info, if they are meant only for writes I agree they shouldn't be retried

- regarding `kXR_NoMemory` it's unclear to me what the client should do in case of a data server according to the spec (http://xrootd.org/doc/dev49/XRdv400.htm#_Toc532936559) - option B

**Comment by simonmichal** [comment]
@abh3 : I've just pushed e82e27706c56328c3bd0ba84ffa508cecad279ee, I think it addressed all your comments (note: I made `kXR_NoMemory` simply retriable). Is there anything else, or can I close this issue?

**Comment by abh3** [comment]
What did you decide to do with kXR_NotAuthorized? Yeah, 3 is arbitrary and 
likely should simpl be a default. I'm a little hesitant to introduce yet 
another client-side knob.

Andy

**Comment by simonmichal** [comment]
@abh3 : `kXR_NotAuthorized` is being retried by default up to 3 times, this can be changed using `XRD_NOTAUTHORIZEDRETRYLIMIT`

**Comment by abh3** [comment]
Great, can we update the man page to include this setting (or is it now the client documentation).

**Comment by simonmichal** [comment]
@abh3 : I'm ahead of you, man page has been already updated. I'll update client docs before we do 4.10.0

I suppose I can close this one?

**Comment by xrootd-dev** [comment]
I think you can :-)
